### ISSUE TITLE
Dividende pro Stück

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#101]
Aus dem Wertpapier Forum.

In der Wertpapier Detailansicht, ggf. in der Buchungsliste?

**Comment by debegr92** [comment]
Ich bin auch der Meinung, dass eine Art "Ausschüttung" in das Wertpapier gehört. Dividenden können aktuell nicht so wirklich eingetragen werden, jedoch könnte man dann automatisch die aktuelle Dividenden Rendite anzeigen und filtern. Also wann es sich lohnt einzusteigen, wenn eine Aktie aktuell mal wieder zu teuer ist.
Ich würde davon absehen das ganze als Attribut einzubauen.

Also zusätzlicher Reiter nach den Stammdaten zur Eingabe der jährlichen Ausschüttung. 
Möglichkeit zur Anzeige zwei neuer Spalten: "Jährliche Ausschüttung" und "Ausschüttungs Rendite" automatisch berechnet zum aktuellen Preis.

Was meint ihr? Ich denke das wäre eine super klasse Funktion!
