### ISSUE TITLE
Feature: Durchschnittliche Haltedauer anzeigen

### ISSUE THREAD

**Issue by Marfir** [portfolio-performance/portfolio#1092]
Als nettes Mini-Feature könnte man unter Performance noch die durchschnittliche Haltedauer der Aktien/Fondsanteile/Anleihen des Gesamtportfolios anzeigen.

**Comment by Ragas13** [comment]
@Marfir
Kannst du deine Idee etwas ausführlicher beschreiben? Wie sollte das ganze dargestellt und berechnet werden? Stichwort Teilverkäufe und Sparpläne.

Gruß 
Marco

**Comment by Marfir** [comment]
@Ragas13 
Ich führe parallel zu PP eine Tabellenkalkulation mit all meinen Käufen und Verkäufen. Dort habe ich die durchschnittliche Haltedauer einfach auf abgeschlossene Transaktionen bezogen und nicht gruppiert nach Wertpapieren. Das könnte man in PP natürlich eleganter lösen oder einfach beide Varianten anzeigen.

Übersichts-screen Performance:
Hier gibt es allgemeine Performance-Kennzahlen über alles. Entsprechend könnte man hier die Durchschnittliche Haltedauer nur über alle Verkäufe berechnen. Dann wäre offensichtlich ob jemand eher kurz-, mittel- oder langfristig anlegt.
Formel:
Haltedauer in Tagen = Tag Verkauf - Tag Kauf

Das ist deutlich einfacher zu berechnen als die portfolio turnover rate und erfüllt seinen Zweck auch.

Performance-Wertpapiere:
Hier könnte man die Haltedauer je Wertpapier bestimmen, anstatt wie im Übersichts-screen nur auf einzelne Transaktionen zu schauen.
Bei Teilverkäufen wird es aber schwierig. Dann könnte man nur die Haltedauer für die Teilverkäufe berechnen und ignoriert die noch offenen Positionen.

**Comment by Ragas13** [comment]
Und das mit den Teilverkäufen ist genau der pudels Kern, denn interessant dürfte es werden programmtechnisch die Daten auszuwerten. Wenn ich nur einen Kauf vs. Verkauf habe ist es kein Problem, sobald Perioden sich überschneiden oder Mengen sich ändern wird es knifflig. Adhoc würde es mE im worst case bedeuten auf 5-Nachkommastellen nach FIFO

**Comment by buchen** [comment]
> Bei Teilverkäufen wird es aber schwierig. Dann könnte man nur die Haltedauer für die Teilverkäufe berechnen und ignoriert die noch offenen Positionen.

Ich hatte vor ein paar Monaten mal angefangen eine Auswertung für "Trades" zu machen. (Ich sehe gerade der Branch ist von August 2017) Den "Trade" habe ich definiert als ein abgeschlossener Kauf und Verkauf. Dazu muss man den Verkauf den passenden Kauf nach FIFO zuordnen - und unter Beachtung ob das Wertpapier in ein anderes Depot umgebucht wurde oder ob es nur Teilverkäufe gab, oder ob ein Verkauf sich auf mehrere Käufe bezieht etc.

Wenn man diese Zuordnung von Trades hat, kann man natürlich auch relativ einfach eine Haltedauer für den Trade errechnen.

Ich kann mal schauen ob ich den Code in einen Branch hier auf Github pushen kann. Allerdings habe ich gleichzeitig mich an einem anderen Tabellenwidget versucht (https://www.eclipse.org/nattable/index.php). Mit diesen Tabellen könnte man schöne Sachen machen: dynamisch gruppieren, Spalten fixieren, bessere Kontextmenüs, ... Allerdings sehe ich gerade dass die letzte Release vom März 2017 ist. Das Widget scheint nicht mehr wirklich gepflegt zu werden. Auch die Commit nehmen kontinuierlich ab: https://projects.eclipse.org/projects/technology.nebula.nattable Das heißt für mich das sollte man nicht miteinander verbinden.

**Comment by buchen** [comment]
Ich habe den Branch [feature_trades](https://github.com/buchen/portfolio/tree/feature_trades) auf Github gepusht. Aktuell sieht man "nur" etwas wenn man den TradeCollectorTest ausführt.

Wenn ich das Beispiel "Allianz" anschaue, dann hätte man zwei "Trades": einer über 10 Stücke der geschlossen ist (hier kann man auch eine Haltedauer errechnen) und einen offenen Trade über 80 Stücke (die hält man aktuell noch).

Für beide könnte man eine Haltedauer errechnen. Und ob er positiv war, etc. Wenn es da Interesse gibt, könnte man das weiter ausbauen. 

```
----- Adidas AG
02.01.2012 - open
47
	02.01.2012 BUY               EUR  2.397,60 Adidas AG
----- Allianz SE
02.01.2012 - 13.01.2012
10
	02.01.2012 BUY               EUR    737,81 Allianz SE
	13.01.2012 DELIVERY_OUTBOUND EUR  1.605,00 Allianz SE
02.01.2012 - open
80
	02.01.2012 BUY               EUR  5.902,49 Allianz SE
----- BASF SE
----- Commerzbank AG
01.01.2012 - 10.01.2012
74,8
	01.01.2012 BUY               EUR  1.019,80 Commerzbank AG
	10.01.2012 SELL              EUR    688,36 Commerzbank AG
----- DAX
----- Linde AG
01.01.2012 - open
33
	01.01.2012 BUY               EUR  3.813,58 Linde AG
----- MAN SE
12.01.2012 - open
10
	12.01.2012 DELIVERY_INBOUND  EUR    934,50 MAN SE
----- Apple Inc.
16.01.2012 - open
2
	16.01.2012 BUY               USD    476,48 Apple Inc.
	18.01.2012 BUY               EUR    391,35 Apple Inc.
```

**Comment by Marfir** [comment]
Danke für dein schnelles feedback.
Ja das reicht doch erst mal, wenn für die durchschnittliche Haltedauer die 10 Allianz Aktien einbezogen werden. Wie du schon sagst, kann man das später noch ausbauen, wenn es genug positive Resonanz gibt. Bis dahin keep it simple.

Zur nebula NatTable:
Die würde ich auch nicht einbinden, wenn dort keine Releases mehr erfolgen. Alternativ könnt Ihr euch mit JavaFX beschäftigen. Als Swing-Nachfolger sollte der Support noch eine weile anhalten.

**Comment by Marfir** [comment]
Kannst du das bitte mit ins nächste Release packen? Ich wollte jetzt keine Beta Version testen. ;-)

**Comment by buchen** [comment]
> Kannst du das bitte mit ins nächste Release packen?

Das sowieso. Wird aber noch eine Woche dauern.

**Comment by Marfir** [comment]
Kein Problem. Danke!
