### ISSUE TITLE
Release ohne JDK (auch auf Github)

### ISSUE THREAD

**Issue by SebRut** [portfolio-performance/portfolio#1122]
Wie in #1006 erwähnt würde ich mich freuen, wenn es PP auch ohne gebundeltes JDK/JRE für Windows geben würde. Steht diese Option noch im Raum? Alternativ kann man wohl in der `PortfolioPerformance.ini` ne eigene Runtime eintragen/den `-vm`-Befehl weglassen, dass würde ich aber ungern automatisch für jeden Nutzer per Script ändern.

**Comment by buchen** [comment]
Hi @SebRut,

die binares habe ich auch weiterhin auf Bintray publiziert:
https://bintray.com/buchen/downloads/portfolio-performance
Und gibt es auch die "windows ohne JRE" Version.
(Die letzten Version 0.39 hatte ich hochgeladen, aber nicht freigegeben).

Ich werde die bei Gelegenheit auch nach Github publizieren - allerdings wollte ich erst mal sehen ob ich von Github kontaktiert werden, weil ich ja doch relative viele Binares hochladen.

**Comment by SebRut** [comment]
> die binaries habe ich auch weiterhin auf Bintray publiziert

Ah ich sehe gerade meinen Fehler, in der Standardansicht für Version bei bintray werden nicht alle Dateien angezeigt, nur beim Klick auf einen extra Reiter.

> Ich werde die bei Gelegenheit auch nach Github publizieren - allerdings wollte ich erst mal sehen ob ich von Github kontaktiert werden, weil ich ja doch relative viele Binares hochladen.

[Hier](https://help.github.com/en/articles/about-releases#limitations-on-binary-files) ist zumindest davon die Rede, dass es keine Limit für die Anzahl an Binaries gibt. Wenn die Releases aber nur bei Bintray verfügbar sind, wäre das für mich allerdings auch ok.
