### ISSUE TITLE
java.lang.UnsupportedOperationException, wenn Steuermitteilung durch PDF Import 0,00€

### ISSUE THREAD

**Issue by robertdue** [portfolio-performance/portfolio#1131]
![image](https://user-images.githubusercontent.com/32411533/53866566-22cce680-3ff2-11e9-9b9c-c69c18cd8294.png)

Wenn ich eine Steuermitteilung von comdirect importiere, die aber 0,0€ umfasst, wird diese so eingetragen. Wenn ich aber anschließend auf das Wertpapier klicke, kommt es zum angezeigten Fehler. Öffne ich die Steuermitteilung manuell, bekomme ich auch die Meldung, dass 0,00€ kein valider Wert ist.

**Comment by Nirus2000** [comment]
Hello @robertdue 
Kannst du uns einen PDF-Debug zur Verfügung stellen?

Regards
Alex
