### ISSUE TITLE
Historische Kurse via CSV import von URL

### ISSUE THREAD

**Issue by timroes** [portfolio-performance/portfolio#1149]
Ein praktisches bisher noch fehlendes Feature, wäre eine Möglichkeit beim Konfigurieren eines historischen Kurses neben der schon bestehenden Möglichkeit der Laden einer Tabelle auf einer Webseite auch das Laden eines CSV von einer URL zu ermöglichen. Man hinterlegt also eine URL, welche ein CSV downloaded, welches anschließend (mit einer immer gleichen Konfiguration geparsed wird).

Ich denke dies wäre eine sinnvolle Erweiterung da ich festgestellt habe, das es oftmals historische Kurse sehr viel genauer und weiter zurückreichend als CSV als als HTML Tabelle zu finden gibt. So bietet z.B, ariva.de einen CSV Download aller historischen Kurse auf der [historischen Kurse Seite](https://www.ariva.de/arero_-_der_weltfonds-fonds/historische_kurse) unten rechts an. Daraus lassen sich problemlos wiederverwendbare URLs erstellen (z.B. https://www.ariva.de/quote/historic/historic.csv?secu=101427053&boerse_id=8&clean_split=1&clean_payout=1&clean_bezug=1&min_time=7.4.2010&max_time=7.4.2019&trenner=%3B&go=Download)

Hätte man nun eine Möglichkeit diese URL zum automatischen Download historischer Kurse zu hinterlegen, hätte man eine sehr genaue Möglichkeit historische Kurse über 10 Jahre (oder mehr) hinweg abzubilden, welche es oft bei Yahoo Finance nicht gibt. Mir ist bisher keine ähnlich gute Möglichkeit bekannt welche diese Anzahl an Kursen als HTML Tabelle bereit stellt. Mein bisheriger Workaround ist natürlich das manuelle Importieren der selbigen CSV Dateien. Ab einer bestimmten Menge an Positionen im Depot wäre ein automatischer Import jedoch sehr viel Zeitsparender.

**Comment by buchen** [comment]
Gute Idee! Mit den speicherbaren Konfigurationen gibt es ja jetzt die Möglichkeit die Konfiguration zu hinterlegen.

Eine Sache muss ich mir noch überlegen: aktuell werden die Konfigurationen für den Benutzer lokal abgelegt (also im Workspace Verzeichnis) und nicht in der Datei gespeichert. Damit wäre die Datei dann aber nicht mehr "Portable". Andrerseits will ich die Konfigurationen auch nicht immer "nur" in der Datei speichern - man soll sie ja auf alle Importe anwenden können. Da muss ich mir noch was intelligentes überlegen.
