### ISSUE TITLE
Steuerbuchung mit Bezug auf Wertpapier

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#115]
Aus dem Wertpapier Forum:

> Weiters kann ich keine Steuern beim Verkauf von Positionen eingeben. Da diese aber gleich beim Verkauf einbehalten werden (zumindest hier in Österreich die KeSt) wäre es toll, wenn man die auch sofort dort eintragen könnte. Wenn ich sie wie vorgesehen auf dem Konto verbuche habe ich keine Verbindung mehr zwischen Steuer und Position.

**Comment by chirlu** [comment]
Ist das noch ein offenes Problem? Man kann mittlerweile Steuern bei Wertpapierverkäufen erfassen.
