### ISSUE TITLE
Gebühren bei der Anzeige "Erträge" berücksichtigen

### ISSUE THREAD

**Issue by sebasbaumh** [portfolio-performance/portfolio#1185]
Bei der neuen Anzeige "Erträge" werden nur Dividenden und Zinsen erfasst.
Ich würde aber gerne auch noch die angefallenen Gebühren auf den Konten berücksichtigen.

Zum Beispiel buche ich Kosten für die Bereitstellung von Echtzeit-Kursdaten für NASDAQ etc. als Gebühr auf das zugehörige Konto.
Diese schmälern ja den Ertrag des Kontos.

Vielleicht könnte man das auch optional machen? Momentan kann man ja auch das Ganze als Bruttodividende anzeigen (was dann die Steuern berücksichtigt).

**Comment by Ragas13** [comment]
Hm, die echten Buchungen von Gebühren und ggf. Steuern und dann konsolidiert als eigener Menüpunkt wie bspw. "Kosten könnte ich mir gut Vorstellen. Aber, wie sieht es mit den Gebühren u. Steuern bei Kauf-/ Verkaustransaktionen aus? Sollten diese dann mit betrachtet werden? Dann müssten im [ViewModel](https://github.com/buchen/portfolio/blob/c9ab12ed365b2eb4e14512ca9f3edc37f1a41142/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/earnings/EarningsViewModel.java) auf die [AccountTransactions](https://github.com/buchen/portfolio/blob/c9ab12ed365b2eb4e14512ca9f3edc37f1a41142/name.abuchen.portfolio/src/name/abuchen/portfolio/model/AccountTransaction.java#L16-L22) unterschiedliche abgefragt werden.

**Comment by sebasbaumh** [comment]
Die echten Gebühren (also ohne Bezug zum Wertpapier) finde ich wichtig, der Rest sollte ja bereits bei der Unterscheidung Brutto-/Netto-Dividende behandelt werden.
Denn momentan werden zwar Zinserträge bzw. -abzüge bereits berücksichtigt.
Es gibt aber genauso Gebühren ohne konkreten Wertpapierbezug - wie zum Beispiel für Echtzeitkursdaten.

**Comment by Ragas13** [comment]
Ich überlege halt gerade, ob es nicht übersichtlicher bzw. auch für den ein oder anderen neben dem Bereich "Erträge" einen neuen Abschnitt wie bspw. "Gebühren & Steuern" zu erstellen, der die Kosten isoliert von den Erträgen betrachtet. Da ich gedenke den ```earning```-Code zu übernehmen, sollten die Gebühren und Steuern dann sowohl mit Bezug zumWertpapier als auch zum Konto aufgeführt werden.

Wenn der Kostenblock zu dem Diagramm d. Einnahmen gepackt wird, würde ansonsten der Balken  ins negative laufen und die Erträge ins positive. Das könnte zusätzlich Fragen aufwerfen, daher meine Überlegung nach "Erträge" und "Gebühren & Steuern" zu isolieren.

@sebasbaumh
Was meinst du wäre die bessere Lösung? Die reinen Kosten mit Bezug zum Konto, oder "Gebühren & Steuern" mit Bezug zum Konto und Wertpapier als neuer Abschnitt in der Navigation links?

**Comment by sebasbaumh** [comment]
@Ragas13 die Gebühren sollten da auch negativ erscheinen, so wie Zinsen wenn diese negativ sind (Negativzinsen oder Kreditzinsen). Da läuft dann quasi Ertrag und Kosten auseinander - sieht bestimmt gut aus mit einer Linie des Ertrages nach Kosten in der Mitte oder ein Balken dafür.

Ich denke aber zu detailliert braucht das gar nicht sein.
Im Großen und Ganzen nutze ich im Abschnitt "Erträge" die "Erträge" (Dividenden-Zinsen und später -Gebühren) und "Dividenden".
Die Erträge sind damit die wirklich zur Verfügung stehenden Ausschüttungen vs. die "Dividenden", der eigentliche Ertrag, wenn man Zinsen und Gebühren eliminieren würde.

**Comment by mierin12** [comment]
Done since [release 0.43.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.43.0) with https://github.com/portfolio-performance/portfolio/commit/7898eef807b48e67dc1a3068e96e3d2810d5c1dc from https://github.com/portfolio-performance/portfolio/pull/1213
