### ISSUE TITLE
VIAC/CS Quote Feed wird nicht mehr upgedated

### ISSUE THREAD

**Issue by KopolJunam** [portfolio-performance/portfolio#1296]
Beim Start des Programms wird der VIAC/CS Quote Feed (Klasse CSQuoteFeed) nicht mehr automatisch upgedated. Geht man auf die Eigenschaftsseite eines solchen Wertpapiers, so funktioniert es im Reiter "Historische Kurse" immer noch.

**Comment by KopolJunam** [comment]
Unterdessen habe ich rausgefunden, dass es zu einem Timeout kommt. Interessanterweise gibt es keinen Timeout, wenn man das über die Eigenschaftsseite abruft. Ich werde das mal analysieren.

**Comment by Ragas13** [comment]
Ursache (nur bei den CS Seiten) scheint das Socket Zeitfenster zu klein zu sein, aber nicht immer. Zeitfenster erhöhen?

**Comment by KopolJunam** [comment]
Ich will es noch ein bisschen untersuchen. Vielleicht könnten ich dann noch eine virtuelle Methode machen, bei welcher ein Feed die Default Timeouts übersteuern kann. Das wäre ja keine grosse Sache.

**Comment by Ragas13** [comment]
@KopolJunam 
Ohne dir jetzt deinen Auswertungen zuvor zu kommen, anscheinend tritt dieses Problem immer nur temporär auf. Am 8.12. um 12 Uhr hatte ich mit den vorhandenen Socket timings Probleme und musste auf > 1 Minute stellen. Um 20 Uhr gab es keine Probleme, die 20 Sekunden haben ausgereicht.

Ich habe gesehen das die Seite ```amfunds.credit-suisse.com``` von Amazon AWS ghosted wird. Hier gab es erst kürzlich massive Probleme beim Download vom dort gehärtetem Content. 100 MB brauchte mehrere Stunden, daher bin ich nicht sicher ob sich da Programms einige etwas machen lässt. Vielleicht findest du ja mehr...
