### ISSUE TITLE
PDF-Import erzeugt NullPointerException - Konto deaktiviert

### ISSUE THREAD

**Issue by gaertnermarkus** [portfolio-performance/portfolio#1299]
Ist das Konto deaktiviert, dann öffne sich das Dialogfenster mit dem PDF-Import mit einer NullPointerException. 
Die Buchung kann natürlich nicht importiert werden.

Selbst wenn dies prizipiell richtig sein soll, und kein Import ohne eine vorhandenes/aktives Konto möglich ist - so sollte im ImportDialog etwas schön darauf hingewiesen werden.

**Comment by Nirus2000** [comment]
This issue is fixes with #3258
