### ISSUE TITLE
(Krypto)Währung nachträglich manuell hinzufügen

### ISSUE THREAD

**Issue by kingfraenky** [portfolio-performance/portfolio#1314]
Hallo erstmal danke für das Top Programm.

Es währe schön wenn du eine Möglichkeit hinzufügen könntest das man (Krypto)Währungen auch manuell einflegen könnte. Das würde das erfassen von Trades zwischen Kryptos sehr vereinfachen ausserdem möchte ich gerne Zinsen erfassen die ich mit Coins generiere und die ich in Coins erhalte.

**Comment by Ragas13** [comment]
Ich verstehe das Problem nicht wirklich, du kannst doch eigene Währung/Umrechnungskurse anlegen? 

https://help.portfolio-performance.info/waehrungen/

**Comment by buchen** [comment]
Ich verstehe das es cool wäre auch Kryptowährungen direkt anlegen zu können. Stand heute geht das nur sehr limitiert: ein ungenutztes Währungskürzel auswählen und Kurse hinterlegen. Das Hauptproblem ist aber: Beträge auf Konten werden **nur mit 2 Nachkommastellen** gespeichert - das ist für Kryptowährungen meist viel zu ungenau.

Kurse könnten 4 Nachkommastellen haben, Anteile können 6 Nachkommastellen haben. Darum ist es aktuell besser eine Kryptowährung als Wertpapier anzulegen.

Die Währung aufzubohren ist ziemlich aufwändig. Ich glaube nicht dass ich in nächster Zeit dazukommen werde:
* beliebige Währungskürzel unterstützen
* pro Währung die Nachkommastellen definieren (ich befürchte ansonsten läuft man in Rundungsprobleme rein)
* das XML Format erweitern so dass man Beträge mit beliebigen Nachkommastellen speichern kann (aktuell werden immer Cents gespeichert - also ganze Zahlen ohne Bruchteile)
* alle Rechnungen anpassen, dass die im Kontext der Währung richtig runden

**Comment by kingfraenky** [comment]
Okay das mit den Nachkommastellen kann man ja umgehen indem man halt in der kleinstmöglichen einheit rechnet und für die Anzeige nur das komma/punkt verschiebt. Hab ich mal so ähnlich in einem Phyton script gesehen.

**Comment by tralafiti** [comment]
Zumindest die Möglichkeit eigene Währungskürzel anzulegen, würde mir schon sehr helfen. Ich versuche den Handel mit Futures zu erfassen. Das klappt mit dem zweckentfremden einer bestehenden Währung plus händisch angelegten Wechselkurs für diese Währung schon ganz gut. Probleme bereitet es mir, sobald zwei Währungswechsel ins Spiel kommen. 

Beispiel:
* Future Micro-Emini S&P (Kürzel MES). Als Wertpapier angelegt, Währung "ISK".
* Wechselkurs ISK->USD angelegt. Manuell 1 ISK = 5 USD erfasst. Passt soweit
* Mein Hauptkonto wird aber in Euro geführt. Nun geht PP z.B. in Wertpapiert-Performance-Bericht hin und nutzt den EZB-Kurs für ISK->EUR. Richtig wäre hier aber die Verkettung ISK->USD->EUR.

Meine Versuche ein Wechselkurs ISK->EUR anzulegen führen leider nicht weit, weil ich hier ja eine dynamische Berechnung für den Kurs bräuchte: Aktueller EUR-USD-Kurs * 5. Könnte ich ein eigenes Währungskürzel ohne schon vorhandene Wechselkurs-Quelle anlegen, entstünde dieses Problem nicht - außer ich unterliege einem Denkfehler :D

**Comment by Xyz00777** [comment]
Was ist den hier der Stand? Könntest du nicht eine Währung hinzufügen die Krpyto heißt und man selber muss dann die Kürzel Infos setzten zb BTC oder XRP, sodass PP diese Währung sich dann lokal hinterlegt und zwar so das es keine Probleme gibt und die kryptos die angelegt werden dann einfach als float speichern? (meine Programmierkenntnisse sind nicht gut aber ein bischen ist aus meiner Ausbildung hängen geblieben :D, deswegen frage ich. Sollte ich falsch liegen gerne Bescheid sagen :) )
@tralafiti im Grunde kannst du dies machen, in dem du in der xml datei rump pfuscht und zb ISK mit dem abänderst, was du gerne hättest zb BTC, habe ich ausprobiert und ging. Ob dies nicht doch irgendwann mal noch zu Problem führen kann weiß ich aber nicht.

**Comment by tralafiti** [comment]
@Xyz00777 Habe ich auch gesehen, wollte da aber nicht drin rumbasteln aus den gleichen Gründen wie du sie erwähnst. Habe stattdessen im Interface noch ein zweiten Wechselkurse angelegt und "missbrauche" ISK weiterhin als MES-Indexpunkte: Neben dem oben beschriebenem ISK->USD noch ein ISK->EUR. Dieser zieht sich den Kurs aus einem extra dafür angelegtem Google Spreadsheet mit `=GoogleFinance("USDEUR"; "price"; "01.01.2020"; "31.12.2030"; "Daily")` plus einer Spalte namens "Close", welche den so erhaltenem Wechselkurs noch * 5 nimmt. Diese dann als "Tabelle auf einer Website" als Kurslieferant im PP, funktioniert bisher wunderbar.
