### ISSUE TITLE
Anzeige für Dividenden Historie 

### ISSUE THREAD

**Issue by tsohst** [portfolio-performance/portfolio#1328]
* Es wäre sehr Hilfreich eine Historische Anzeige (Tabelle bzw. Diagramm) aller Dividendenausschüttungen + Zahlungsdatum einer Aktie zu sehen.
* Mit der Yahoo API scheint man das Abfragen zu können.

**Comment by cmaoling** [comment]
Please have a look into https://github.com/buchen/portfolio/pull/732. This was a proposal I made some time ago, which seems to address this... At least I use this to collect dividend and split events automatically from Ariva, but Yahoo would be possible as well...
