### ISSUE TITLE
0.44.0: Managing Filters: no adding possible

### ISSUE THREAD

**Issue by ronnykrijt** [portfolio-performance/portfolio#1375]
With 0.44.0, managing Filters is possible, as in changing the name and deleting entries from a filter. Adding a new entry to an existing filter is not possible.

**Comment by oduudo** [comment]
It would be very helpful, since I manage the assets of my whole family spreaded over many accounts, so changing the filters would help a lot!

**Comment by OnkelDok** [comment]
Fixed with 6e5471dff53c0f3f45190158662d1e0219d2cc27 (#2495)
