### ISSUE TITLE
Wöchentliche Buchungen für Sparplan

### ISSUE THREAD

**Issue by Taschentuch9** [portfolio-performance/portfolio#1396]
Echt tolles Programm, benutz es jetzt seit einem Jahr und alles geh super!

Eine Anregung: Würds praktisch finden wenn man für das Sparplan-Intervall auch "wöchentlich" als Option hätte. Überweisungen auf mein P2P-Konto sind zum Beispiel wöchentlich.

Beste Grüße!

**Comment by buchen** [comment]
Ja, diesen Feature Request habe ich schon mal bekommen. Ist notiert. Leider ist das nicht ganz trivial weil ich das Datenmodell etwas anders ist. Bis es sich ändert, muss man wohl 4 monatliche Sparpläne anlegen die jeweils im "Versatz" buchen. Nicht ganz so praktisch (man wollte wohl nach Wochentagen buchen), ich weiß.

**Comment by mierin12** [comment]
Done on [release 0.72.0 and 0.72.1](https://github.com/portfolio-performance/portfolio/releases/tag/0.72.0) from https://github.com/portfolio-performance/portfolio/pull/4347
