### ISSUE TITLE
UI-Fehler unter Windows

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#1408]
Ich selber nutze Windows ganz selten, aber gerade auf der VMWare Installation sind mir ein paar Fehler aufgefallen:

**Open**: Rebalancing View hat die "handles" zum Aufklappen falsch formatiert
<img width="433" alt="Bildschirmfoto 2020-02-29 um 07 46 43" src="https://user-images.githubusercontent.com/587976/75602819-c7301e80-5ac8-11ea-93e4-dc5b6e155b85.png">

✅ Labels mit farblichen Hintergrund zu nah platziert
<img width="332" alt="Bildschirmfoto 2020-02-29 um 07 45 19" src="https://user-images.githubusercontent.com/587976/75602829-ea5ace00-5ac8-11ea-8935-47cd874297eb.png">

✅ Drop Down Box der QuoteProvider mit doppelter Scrollbar
<img width="456" alt="Bildschirmfoto 2020-02-29 um 07 44 37" src="https://user-images.githubusercontent.com/587976/75602833-f9da1700-5ac8-11ea-89b2-ad95b981cc65.png">

✅ Info Labels falsch platziert; Labels mit Border
<img width="525" alt="Bildschirmfoto 2020-02-29 um 07 43 51" src="https://user-images.githubusercontent.com/587976/75602840-1d9d5d00-5ac9-11ea-92eb-e36178d41b3d.png">

**Comment by Flippo24** [comment]
Das Bild 2 und 4 ist bei mir auf meinem PC auch so zu sehen. Habe die Scalierung im Windows auf 110%, falls das hilft.

**Comment by DanielOberlechner** [comment]
@buchen sorry ich habe eine kurze Offtopic Frage, und die waere mit welcher App hast du denn dein Profilbild gemacht? Gefaellt mir sehr gut, moechte ich auch gerne probieren ... habe ein iPhone X gibts dafuer deine App? :) Wirklich sorry, ist mir aber eben aufgefallen ...

**Comment by buchen** [comment]
Ich glaube das was „Prisma“

**Comment by Pnda87** [comment]
Bild 2, 3 und 4 ist bei mir unter Win10 genauso.

Bild 1 kann ich so bei mir nicht bestätigen:
<img width="306" alt="asset allocation" src="https://user-images.githubusercontent.com/34549632/75918003-3d32dd80-5e5b-11ea-9227-fd46ec8bd4e2.png">

Ich habe noch 2 weitere Stellen mit unschöner Darstellung gefunden:
Wertpapiere - Datenqualität:
<img width="320" alt="wertpapiere - datenqualität" src="https://user-images.githubusercontent.com/34549632/75918068-53d93480-5e5b-11ea-95e8-018e2e743851.png">

Suchfunktion oben rechts:
<img width="231" alt="wertpapiere - suche rechts oben" src="https://user-images.githubusercontent.com/34549632/75918082-589de880-5e5b-11ea-992a-9d73da97048e.png">

**Comment by Pnda87** [comment]
Die Tooltips sehen auch in der View Erträge & Ausgaben nicht korrekt aus:
<img width="258" alt="earnings_tooltips" src="https://user-images.githubusercontent.com/34549632/75920780-5427fe80-5e60-11ea-8bfa-e6cf99dfdc18.png">

Habe dafür mal einen PR gestellt: #1412

**Comment by Pnda87** [comment]
noch ein paar weitere fixes: #1423 

betrifft den Rahmen um Path to date und Path to Close bei JSON Quotes (siehe Abbildung 4 oben)
sowie die Info Symbole, die teilweise verdeckt sind, siehe meine Abbildung oben

noch ein Hinweis:
- die Info Symbole werden unter Historical Quote fälschlicherweise auch oben links in der Ecke angezeigt
- die ComboViewer der Quote Provider sollte vielleicht am besten analog zu Taxonomies gesetzt werden. Dort wird die Größe korrekt gesetzt.


noch ein weiterer Bug der aufgefallen ist:
<img width="623" alt="securities chart 10Y" src="https://user-images.githubusercontent.com/34549632/76126367-3218b280-5fff-11ea-913e-07d9ef8584d8.png">

**Comment by buchen** [comment]
> noch ein weiterer Bug der aufgefallen ist: **10**

Ich glaube ich habe das damals mit "10" benannt damit die Buttons nicht zu breit werden. Aber YTD ist sowieso breiter. Das fixe ich.

> die ComboViewer der Quote Provider sollte vielleicht am besten analog zu Taxonomies gesetzt werden. Dort wird die Größe korrekt gesetzt.

In den Drop Downs für die Taxonomy kürze ich den Text manuell auf 80 Zeichen. Das ist aber auch ein Problem weil in der Mitte schon relevante Informationen verloren gehen können. Ich habe jetzt mal unter Windows eine andere Combo Box verwendet. Damit scheint es besser auszusehen.
