### ISSUE TITLE
CSV Importer - Uhrzeit ignoriert

### ISSUE THREAD

**Issue by chrisaut** [portfolio-performance/portfolio#1409]
Versuche gerade meine Kontobewegungen per CSV importer einzupflegen. Es scheint dass obwohl man eine Spalte als Uhrzeit deklariert, diese weder im nächsten Schritt bei der Vorschau als spalte angezeit, noch in der finalen Buchung importiert wurde.

```
"Datum";"Wert";"Uhrzeit"
"01.02.2001";"-100,11";"10:43"
```
Eine Testdatei mit diesem Inhalt müsste doch funktionieren oder? Habe auch Versucht Uhrzeit mit Sekunden (10:43:45) bzw mit Abstand in die Datumsspalte (01.01.2001 10:45) aber kriegst einfach nicht hin.

Ist das ein Bug/missing feature?

**Comment by chrisaut** [comment]
Ich hab debugged...
https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/csv/CSVAccountTransactionExtractor.java#L143

Hier (und in ein paar andere Stellen, sowie wahrscheinlich auch bei anderen extractortypes) wird explizit die Uhrzeit wieder auf null gesetzt, obwohl diese etwas vorher 
```Java
getDate(Messages.CSVColumn_Date, Messages.CSVColumn_Time, rawValues, field2column);
```
richtig getsetzt worden wäre.

Komischerweise wurde das mit dem commit gemacht der eigentlich sagt er fügt die Uhrzeit dazu beim import.
https://github.com/buchen/portfolio/commit/3af8de36aed9f6675577c916c23b872578b59e38

Ich weiss nicht ob ich da was nicht richtig verstehe, jedensfalls wenn ich das .withHour/withMinute auskommentier wird die Transaktion korrekt mit Uhrzeit importiert.

Aber bevor ich PR schicke, verstehe ich das was falsch, irgendwas muss man sich ja dabei gedacht haben die Uhrzeit hier wieder explizit auf null zu stellen?

Danke

**Comment by Nirus2000** [comment]
This issue is closed with 3af8de3
