### ISSUE TITLE
Coding Support: getHigh() getLow()

### ISSUE THREAD

**Issue by MarcDahlem** [portfolio-performance/portfolio#1456]
Hallo Andreas,

ich wollte eben ein gefühlt sehr billiges Feature umsetzen, bekomme allerdings nicht die richtigen Models zum Befüllen der View.

Und zwar wollte ich in der Wertpapier Bottom-Bar im Tab Kurshistorie zusätzlich zum normalen Kurs auch Tageshoch und Tagestief anzeigen.

Siehe https://github.com/MarcDahlem/portfolio/tree/feature_enhanced_asset_history

Allerdings hat das Model "SecurityPrice" nur getValue(), nur der "LatestSecurityPrice" hat auch getHigh() und getLow().

Ich habe allerdings das Gefühl, dass der LatestSecurityPrice nicht gespeichert/wiederhergestellt wird, außer für den wirklich letzten historischen Kurs.

Kannst du mir hier eventuell kurz einen Tipp geben, wie ich an die Highs und Lows der kompletten Historie komme?

Danke & Grüße

**Comment by debegr92** [comment]
Genau so ist das auch. Hatte mich anfangs auch sehr verwirrt. Es scheint wirklich so gewollt zu sein, dass nur der letzte Kurs eine komplette Kerze mit Open, High, Low und Close speichert. Alle historischen Daten speichern nur den Close Preis.

Begründung ist, dass PP keine Charting Software ist, sondern Performance berechnen soll, dafür wird das nicht benötigt und spart unmengen an Speicherplatz.
