### ISSUE TITLE
Targobank PDF Import funktioniert nicht

### ISSUE THREAD

**Issue by Fail-Unsafe** [portfolio-performance/portfolio#1476]
Moin,

in der Version: 0.46.0 (März 2020) von PP scheint der Import von Targobank-PDFs nicht möglich zu sein. Ähnlich wie die Comdirect erstellt die Targobank zwei Dokumente: eine "Steuerbeilage" und eine "Ertragsgutschrift".
[Steuerbeilage (WPX040) TARGO 00000000538051871310 am 2020-03-14.pdf.txt](https://github.com/buchen/portfolio/files/4430269/Steuerbeilage.WPX040.TARGO.00000000538051871310.am.2020-03-14.pdf.txt)
[Ertragsgutschrift (WPX024) TARGO 00000000538051871310 am 2020-03-13.pdf.txt](https://github.com/buchen/portfolio/files/4430270/Ertragsgutschrift.WPX024.TARGO.00000000538051871310.am.2020-03-13.pdf.txt)

**Comment by inv-trad** [comment]
Ist mit Pull Request https://github.com/buchen/portfolio/pull/1631 in Version 0.46.6 implementiert.

**Comment by Nirus2000** [comment]
This issue is closed with #1631
