### ISSUE TITLE
comdirect REST API

### ISSUE THREAD

**Issue by doncristobal** [portfolio-performance/portfolio#1496]
Könnte es eigentlich interessant sein, die comdirect REST API, die es seit letzten November gibt, einzubinden? 
Ich vermute, man könnte entweder automatisiert die Orderabrechnungen aus der Postbox herunterladen, oder einen automatischen Depot- oder Kontoabgleich machen etc.

Details unter https://www.comdirect.de/cms/kontakt-zugaenge-api.html

Was kann ich mit dem REST API tun?
Das REST API wird kontinuierlich weiterentwickelt. Die folgenden Geschäftsvorfälle stehen u. a. zur Verfügung:

- Abruf Depotübersicht
- Aufgabe von Orders (alle im Web verfügbaren Orderarten und Handelsplätze)
- Änderung/Streichung von Orders
- Handeln im LiveTrading
- Abruf Salden für Konten, Karten und Depots
- Abruf Kontoumsätze
- Abruf Dokumente aus der PostBox
- Session-TAN ermöglicht einmalige TAN-Eingabe für alle API-Transaktionen der Session

**Comment by buchen** [comment]
Gibt es irgendwo das API zu sehen (außer wenn man sich registriert)?

Mich würde mal interessieren welche Details es zu "Abruf Kontoumsätze" gibt. Zumindest under PSD2/XSA2 sind die Daten dürftig - da bekommt man keine Steuern, Gebühren, o.ä. mit.

Die Dokumente in der Postbox wären dann da - könnte man natürlich auch parsen.

Schwer zu beurteilen wie aufwändig die Anbindung ist.

**Comment by WGPSenshi** [comment]
Diese Dokumente werden von Comdirect zur Verfügung gestellt und sollten ohne Zugang einsehbar sein:
https://kunde.comdirect.de/cms/media/comdirect_REST_API_Dokumentation.pdf
https://kunde.comdirect.de/cms/media/comdirect_REST_API_Postman_Collection.json
https://kunde.comdirect.de/cms/media/comdirect_REST_API_Postman_Collection_readme.pdf
https://kunde.comdirect.de/cms/media/comdirect_rest_api_swagger.json

Wenn "Test-Output" zu einzelnen Routen benötigt wird, kann ich vielleicht helfen, bastle gerade an ein paar einfachen Python-Bindings (wenn auch erstmal nur für PDF Abruf).

Prinzipiell steckt ein OAuth-Verfahren dahinter, welches mit Session-, Request- und TAN-Sessions arbeitet (inkl. Refresh-Workflow).
Der Aufbau der Session besteht zwar aus 4-6 Challenges und ist an vielen Ecken nicht die logischste und konsequenteste aller Architekturen, aber andere Banken haben schon viel fiesere Brocken ausgerollt :) .

**Comment by johanneshiry** [comment]
Hallo zusammen,
ich bin hier drüber gestolpert, nachdem ich gestern überlegt habe, meinen PostBox-Download zu automatisieren um nicht alle paar Tage die Dokumente manuell herunterladen + importieren zu müssen. Könnte das natürlich iwie anders lösen, aber wenn hier Interesse besteht allgemein die REST API von comdirect anzubinden wäre das natürlich noch komfortabler. 
Ich hätte entsprechend auch Interesse an einer Anbindung der comdirect REST API und könnte mir auch vorstellen dazu beizutragen. 

Deshalb zwei Fragen:
- Gibt es in der Sache bereits Fortschritte? 
- Hat noch jemand Interesse daran sich mit mir da dran zu setzen?
