### ISSUE TITLE
Bug bei Kurse aktualisieren (Selektiertes Wertpapier)

### ISSUE THREAD

**Issue by debegr92** [portfolio-performance/portfolio#1516]
Bei der Aktualisierung von Kursen kommt es bei meiner Linux Version bei allen Datenquellen zu folgendem Problem:
Ich selektiere einige Wertpapiere und klicke: _Online -> Kurse aktualisieren (selektiertes Wertpapier)_
Dabei wird jedoch **nur der Kurs des obersten Elements in der Liste aktualisiert**, kein weiteres.
Wenn ich kein Wertpapier selektiere und nur auf _Online -> Kurse aktualisieren_ klicke, dann steht ganz kurz 137 Operationen dran und keine Sekunde später ist diese Anzeige wieder weg und kein Element hat ein Update bekommen.
Mein Workaround ist jedes einzeln anklicken und über das Kontextmenü den Kurs aktualisieren.

Seit wann ist das so und wie kam das rein? Ist mir erst kürzlich aufgefallen.

**Comment by debegr92** [comment]
Gerade nochmals geprüft, ob das nur bei den Kurslieferanten Kraken und Bitfinex auftritt. Leider funktioniert das auch nicht richtig in den Aktien Watchlists, wenn diese Yahoo als Kurslieferant haben.

**Comment by buchen** [comment]
Leider wird aktuell nur das erste selektierte Wertpapier aktualisiert. Das liegt daran wie die Selektion weitergereicht wird. Ich befürchte das keine ganz kleine Sache. Das muss ich noch mal ändern.

**Comment by debegr92** [comment]
Hallo Andreas,
okay, dann hatte ich den Punkt so falsch verstanden. Dachte immer, bevor ich das Wertpapier selektiere und oben Kurs aktualisiere kann ich das ja auch einfach über einen Rechtsklick.
Leider funktioniert bei mir jedoch auch das Update der gesamten Watchliste nicht wirklich. Es steht für einen sehr kurzen Augenblick viele aktive Operationen in der Statusleiste, jedoch kurz drauf wieder nicht. Als würde der Vorgang abstürzen. Kann ich hier Logs generieren, oder sehen an was es liegt?

**Comment by myrdd** [comment]
Ich habe eine "quick & dirty" Implementierung erstellt. Habe es noch nicht ausgiebig getestet. Außerdem fehlen noch einige Übersetzungs-Korrekturen.

https://github.com/myrdd/portfolio_performance/tree/update-quotes-of-selected-securities

**Comment by myrdd** [comment]
Der „Bug“ ist ab Version 0.71.0 behoben (https://github.com/portfolio-performance/portfolio/pull/4212), dieser Issue kann geschlossen werden. :slightly_smiling_face:

**Comment by Nirus2000** [comment]
Done
