### ISSUE TITLE
Feature request: Make it possible to see invested capital for a taxonomy

### ISSUE THREAD

**Issue by lsolesen** [portfolio-performance/portfolio#1529]
Right now it is only possible to get invested capital on a graph for the entire portfolio. It would be very helpful if it was also possible for a taxonomy.

See https://forum.portfolio-performance.info/t/is-it-possible-to-show-invested-capital-only-for-some-of-the-portfolio/8957/10

**Comment by mierin12** [comment]
Invested Capital for any data series (for any combination of accounts, for Taxonomies) is now available in the Assets graph with release [0.73.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.73.0) from https://github.com/portfolio-performance/portfolio/pull/4403
