### ISSUE TITLE
Eintrag duplizieren / duplicate entry

### ISSUE THREAD

**Issue by uok** [portfolio-performance/portfolio#1588]
Bitte einen einfache Möglichkeit einbauen, um einen Eintrag, z.B. Zinsen, zu duplizieren - per Rechtsklick oder Tastenkombination z.B. Strg+D. Der Eintrag wird dupliziert und das Bearbeitungsfenster öffnet sich. So kann man sehr schnell ähnliche Einträge hinzufügen! 
Danke!

Please create simply way to duplicate an entry, e.g. interest - with right click or keyboard shortcut e.g. Ctrl+D. The entry is duplicated and the edit window opens. This way you can add similar entries very fast!

**Comment by dylan09** [comment]
I also would like to have such feature. I think it would save me and a lot people tons of work.

**Comment by mierin12** [comment]
The "Duplicate transaction" action was added by https://github.com/portfolio-performance/portfolio/commit/f3cca30485476b4cd6a632a8be3cc60fc12245a2 in release [0.66.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.66.0), and the shortcut CTRL+D has been added in release [0.73.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.73.0) with https://github.com/portfolio-performance/portfolio/pull/4398
