### ISSUE TITLE
Benchmark / Datenreihe Suche nach Plus-Zeichen nicht möglich

### ISSUE THREAD

**Issue by tknuppe** [portfolio-performance/portfolio#1599]
Beim Hinzufügen einer Datenreihe oder Benchmarks zum Performance-Diagramm kann man nicht nach Papieren suchen, die ein Plus-Zeichen enthalten. Die suche nach s+p500 beispielsweise liefert kein Ergebnis. Man muss in dem Fall nach s\+p500 oder p500 suchen. Kommt vermutlich selten vor aber meiner Meinung nach sollte man nach allen druckbaren Zeichen suchen können. Wenn man auf die Idee kommt, ein '*' als Wildcard einzugeben kommt sogar eine Java-Fehlermeldung.

Ich schätze mal, das betrifft auch andere Such-Felder. Habe es aber dort zuerst bemerkt.

**Comment by mierin12** [comment]
Fixed in [release 0.69.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.69.0) with https://github.com/portfolio-performance/portfolio/pull/1278 and https://github.com/portfolio-performance/portfolio/pull/3965
