### ISSUE TITLE
Request: Widget für Performanceneutrale Bewegungen

### ISSUE THREAD

**Issue by SgtWinter** [portfolio-performance/portfolio#1642]
Für die Auswertung des Portfolios nach Zeiträumen finde ich ein Widget für die Performanceneutralen Bewegungen im Zeitraum praktisch. Die Tabelle "Performanceberechnung" ist mir zu unübersichtlich für diesen Zweck.

**Comment by mierin12** [comment]
Done since  [release 0.54.3](https://github.com/portfolio-performance/portfolio/releases/tag/0.54.3) with https://github.com/portfolio-performance/portfolio/pull/2381
