### ISSUE TITLE
latest version fails to start after install

### ISSUE THREAD

**Issue by smurfer** [portfolio-performance/portfolio#1712]
latest version does not start after update from previous version (on Windows 10).

Error log at
[1598938074783.log](https://github.com/buchen/portfolio/files/5154136/1598938074783.log)

**Comment by buchen** [comment]
Thanks for the log.

If you start it a second (or third) time, did PP then start correctly? (This is an behavior that I sometimes see)

**Comment by smurfer** [comment]
Thanks for the quick response: the fourth attempt was successful!. Would you need the three error logs?

**Comment by Sieboldianus** [comment]
Same for me, latest update and Portfolio Performance doesn't start anymore, even after the fourth restart..

**Comment by buchen** [comment]
> Would you need the three error logs?

No. This issues comes up when the framework updates itself (this time I updated the Eclipse libraries to 2020-06 version). I am using the Eclipse p2 self-updater - it is unclear to me why the cleanup of the previous version does not work correctly (which leads to dangling bundle requirements which prevent the startup).

**Comment by yetipenguin** [comment]
I encounter the same error on Kubuntu 18.04.5 LTS. See the attached log.
On the second start the missing modules seemed to be loaded.

[1598954177764.log](https://github.com/buchen/portfolio/files/5158864/1598954177764.log)

**Comment by p-vogt** [comment]
(Windows 10) I tried to start it multiple times (more than 4 times, I think version 0.48.0). Did not work. Then I started it with admin rights and it worked. Then I installed another update (0.48.1) while still having admin rights and now I can start it without admin rights. Everything seems to work again.

**Comment by bbatsov** [comment]
I've had the same issue on Mac OS, but it starts from the second try.
