### ISSUE TITLE
Augsburger Aktienbank AG und Netbank => gleicher Broker 

### ISSUE THREAD

**Issue by Ehsanollah** [portfolio-performance/portfolio#1721]
Varibel die hier unten verwendet wurden, fangen mit % an.

PDF Autor: ''
PDFBox Version: 1.8.16
-----------------------------------------
Augsburger Aktienbank AG
Augsburger Aktienbank AG 86135 Augsburg Augsburg, 01.09.2020
Valuta 01.09.2020
Ex-Tag 28.08.2020
Herrn
%Vorname %Name
%Straße %Hausnummer
%PLZ %Stadt
Wertpapierabrechnung
Depotnummer: %Depotnummer
Depotinhaber: %Vorname %Name
DIVIDENDENGUTSCHRIFT
Deutsche Post AG Namens-Aktien o.N.
ISIN DE0005552004 WKN 555200
Zahlungszeitraum von 01.01.2019 bis 31.12.2019
ST %Anzahl(Format z.B: 1,00)
Zins-/Dividendensatz EUR %Dividende(Format z.B: 1,00)
Brutto EUR %Dividende(Format z.B: 1,00)
zu Gunsten Konto %Konto EUR %Dividende(Format z.B: 1,00)

**Comment by Nirus2000** [comment]
Hello @Ehsanollah 
Please create a PDF debug and post it [here](https://forum.portfolio-performance.info).
The best way to see how this works is to watch the video tutorial.

Video Tutorial:
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)

Greetings
Alex
