### ISSUE TITLE
No icon in the dock on Ubuntu 20.04 using GNOME

### ISSUE THREAD

**Issue by bbatsov** [portfolio-performance/portfolio#1738]
I guess that's best illustrated with a screenshot of Ubuntu's app dock:

![image](https://user-images.githubusercontent.com/103882/92356593-09c55a00-f0ef-11ea-93d3-2f8db0d42210.png)

That iconless item is Portfolio Performance. I'm assuming that's because it doesn't ship a `.desktop` file. E.g. IB's TraderWorkstation (another Java app) has this file `Trader Workstation.desktop`:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=Trader Workstation
Exec="/home/bozhidar/Jts/tws" %U
Icon=/home/bozhidar/Jts/.install4j/tws.png
Categories=Application;
StartupWMClass=install4j-jclient-Launcher
```

I assume Portfolio Performance needs something similar. 

**Desktop (please complete the following information):**
 - OS: Ubuntu using GNOME
 - Version: 20.04

**Comment by ohmer1** [comment]
This do the job for me:

```ini
[Desktop Entry]
Type=Application
Name=Portfolio Performance
Exec=/path/to/PortfolioPerformance/PortfolioPerformance
Icon=/path/to/PortfolioPerformance/icon.xpm
Categories=Application;
StartupWMClass=Portfolio Performance
```
