### ISSUE TITLE
[Ubuntu] IllegalArgumentException on focus lost 

### ISSUE THREAD

**Issue by bbatsov** [portfolio-performance/portfolio#1739]
**Describe the bug**

Often I get an exception when the app window loses focus. It looks like:

![image](https://user-images.githubusercontent.com/103882/92357059-e2bb5800-f0ef-11ea-9662-00ad3c2c315c.png)

**To Reproduce**
1. Go to some report (e.g. Earnings)
2. Switch to another app
3. Go back to Portfolio Performance

**Expected behavior**

No error. :-)

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Version: 20.04

**Comment by cmaoling** [comment]
@bbatsov Can you share the more detailed stack trace, which hopefully is present under Help-'Show error log'?
I am using PP under 20.04 and are not able to reproduce...

**Comment by bbatsov** [comment]
Sure. I'll try to get more data next time I encounter this.
