### ISSUE TITLE
Digits Shown for Purchase Price (MA)

### ISSUE THREAD

**Issue by metal450** [portfolio-performance/portfolio#1907]
Since we've now got the Preferences->Presentation->Formatting->Display precision, would it be possible to also apply that to "Purchase Price (MA)" as shown on Statement of Assets?  Since Purchase Price is a calculated value, it seems like this would be a reasonably minor change.

The rationale is the same: for crypto, price differences below 0.01c can be a significant percentage of the value.  Many cryptos are valued in the cents, so even if you lower your average cost by a significant amount, this may show the same value due to rounding.

**Comment by mierin12** [comment]
Done since [release 0.50.3](https://github.com/portfolio-performance/portfolio/releases/tag/0.50.3) with https://github.com/portfolio-performance/portfolio/pull/1979
