### ISSUE TITLE
Fees based on Shares deduction

### ISSUE THREAD

**Issue by RomainD2** [portfolio-performance/portfolio#1993]
Hi,

Thanks for this amazing program!

I would love to use it for all my financial products, however, there is a limitation because of some specific financial product which have fees based on securities shares deduction. For example :
![portfolio2](https://user-images.githubusercontent.com/4403383/104944018-e1ac0880-59b6-11eb-92df-97fc3e7a29f6.PNG)

You can see in "Nombre de Parts" which are deduced from my Shares. I found a way to do that, but with two operations. I need to sell this amount, and then, to add fees with the same amount, so two transaction.

Maybe the best way would to be able to add these fees with the same amount when selling this share, but it is not possible to save due to soft limitation :
![image](https://user-images.githubusercontent.com/4403383/104944516-9cd4a180-59b7-11eb-97b9-7fe7773db369.png)

Maybe there are a better way to implement that, adding for example the way to use Shares under the Fee option, for example (Quick photoshop ^^)
![image](https://user-images.githubusercontent.com/4403383/104944901-313f0400-59b8-11eb-94ec-cec3980fe1d3.png)

What do you think about this feature ?

Thanks

**Comment by debegr92** [comment]
I think this feature will be also very helpful for some crypto investors. Most exchanges have fees in a specific crypto currency instead fiat. Maybe combine this with https://github.com/buchen/portfolio/issues/1960 to also allow share based fee for transactions between security accounts.

**Comment by zr40** [comment]
This would be useful for my pension plan. They deduct their monthly fees directly as a percentage of shares.

**Comment by zr40** [comment]
You can actually do this already. Go to the Securities account, and instead of "Sell" or "Fees", use "Delivery (Outbound)". Specify the number of shares that were deducted and make sure that the fees are equal to the value of the shares.

For example:

![Screenshot from 2021-01-30 16-44-54](https://user-images.githubusercontent.com/616299/106360739-88c76300-631a-11eb-9ddf-dffa7d4e0df6.png)

**Comment by mierin12** [comment]
In release [0.73.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.73.0) a hint to use Outbound Delivery instead of a Sell in case of a zero sell amount has been added from #4401
