### ISSUE TITLE
Hourly quotes & deltas?

### ISSUE THREAD

**Issue by naps62** [portfolio-performance/portfolio#2070]
**Is your feature request related to a problem? Please describe.**

With markets in high volatility (both stock and crypto), my global metrics (e.g.: true-time IRR) change drastically over a period of a few hours. It would be useful to have visibility into which assets fluctuated the most in a shorter timeframe than the current 24h delta provides

**Describe the solution you'd like**

It seems to me this is a two-part problem:

1. Allow more granular quotes, (e.g.: hourly)
2. With that info now in place, provide the ability to add delta columns for a shorter timeframe. This could either be hardcoded columns (e.g.: delta 1h / delta 4h / delta 12h), or the ability for us to define these columns somehow

**Describe alternatives you've considered**

---

**Additional context**

----

**Comment by Ragas13** [comment]
Just some thoughts from the substitutes' bench. Most quote providers supply the prices only on dsily bases. it's will be challenging to show hourly data which are not published anywhere free of charge 😉

**Comment by debegr92** [comment]
I think the first step would be, to allow the historic quotes to have more information. The first time I took a look into to code, I realized, that only the close price is saved. As @Ragas13 already said, it will be hard to get 1h quotes, but most sources provide complete open, high, low, close, volume data. With high/low prices per day, you can also calculate intraday volatility.
I would be happy to see candlestick charts with volume in PP!

**Comment by naps62** [comment]
While I agree that high/low/close prices would be useful, they wouldn't really solve my original problem (which I now realise I may not have explained as well as I should)

There were a few points during recent days where I looked at my portfolio a couple of times (e.g.: before dinner, and then once again after getting back), and saw a considerable spike, but no ability to see which assets caused that

So it wasn't so much about keeping historical data, but rather about more close to real-time information

**Comment by debegr92** [comment]
Sounds like this is a problem you can't solve with PP. It is more designed to look at it a few times a week/month/year to keep track of your financial success.
