### ISSUE TITLE
Request: Ability to search the 'Trades' screen

### ISSUE THREAD

**Issue by metal450** [portfolio-performance/portfolio#2075]
The 'Search' box at the top of the 'All Transactions' screen is indispensable.  It'd be extremely useful to have the same on the 'Trades' screen.

**Comment by mierin12** [comment]
Done since [release 0.68.4](https://github.com/portfolio-performance/portfolio/releases/tag/0.68.4) with https://github.com/portfolio-performance/portfolio/pull/3926
