### ISSUE TITLE
CSV Export Inconsistent Date Format

### ISSUE THREAD

**Issue by metal450** [portfolio-performance/portfolio#2077]
When exporting CSV from the 'Trades' screen, the format of dates is inconsistent: dates that don't have a time are able to be understood by i.e. Excel, but dates that have a time end up as text, i.e. "Jan 19, 2021, 12:22 AM."  This text representation isn't sortable in a spreadsheet in a coherent way.

I would suggest having all dates output to CSV in a format that would be sortable, whether or not a time is present. i.e.

yyyy/mm/dd hh:mm (where hours would be 24hr).

Thanks!

**Comment by flywire** [comment]
I've seen a mix of with and without times and two and four-digit years in the same column,

eg View, Securities, (select one), Transactions - Date: `19 Jul. 2021`

Where did the `.` come from?

Even dates entered/imported wrongly they should be reformatted.

**Comment by Nirus2000** [comment]
This issue was fixes with [b14cff8](https://github.com/portfolio-performance/portfolio/commit/b14cff8c22bb83df7f4575a5e6ccbdc0b81e71fd)
