### ISSUE TITLE
New "Trades" Screen Filtering Forgets Filter When Leaving Screen

### ISSUE THREAD

**Issue by metal450** [portfolio-performance/portfolio#2174]
The ability to filter the Trades screen by open/closed was recently added; however, the software "forgets" the filter setting as soon s you leave that page (aka when you return, it resets to no filter).  Filters on other screens retain their settings when you leave & return.

**Comment by mierin12** [comment]
Done since [release 0.68.4](https://github.com/portfolio-performance/portfolio/releases/tag/0.68.4) with https://github.com/portfolio-performance/portfolio/pull/3919
