### ISSUE TITLE
Save button disabled while selling a share

### ISSUE THREAD

**Issue by K1llsh0t** [portfolio-performance/portfolio#2214]
**Describe the bug**
Unable to sell when credit note is 0.

**To Reproduce**
1. select any share and sell.
2. make sure credit note shows as 0 value 
3. See save button disabled

**Expected behavior**
It should allow saving when the credit note is 0.

**Screenshots**
<img width="657" alt="Screenshot 2021-04-14 at 6 38 44 PM" src="https://user-images.githubusercontent.com/28539587/114731015-6efebf00-9d52-11eb-8da2-70530b87861d.png">

**Desktop (please complete the following information):**
 - OS:  macOS

**Comment by chirlu** [comment]
That’s intentional. There is a separate transaction type (not sure what it’s called in English) for selling a security without a corresponding account transaction.

**Comment by K1llsh0t** [comment]
> That’s intentional. There is a separate transaction type (not sure what it’s called in English) for selling a security without a corresponding account transaction.

Thanks for the reply. I see a Buy, Sell and dividend options. Can you please help me with a screenshot where you were able to sell a security with 0 return?

**Comment by EliasZepf** [comment]
> Can you please help me with a screenshot where you were able to sell a security with 0 return?

Rather late, but maybe it helps: You can use the "Delivery (Outbound)" transaction for this purpose.

![DeliveryOutbound](https://user-images.githubusercontent.com/77249873/118293679-2dd90680-b4da-11eb-96e2-ce8a0471a8d2.PNG)

**Comment by mierin12** [comment]
In release [0.73.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.73.0,) a hint to use Outbound Delivery instead of a Sell in case of a zero sell amount has been added from https://github.com/portfolio-performance/portfolio/pull/4401
