### ISSUE TITLE
Report interval: dynamic "last month" option

### ISSUE THREAD

**Issue by pat-s** [portfolio-performance/portfolio#2228]
In the report interval selection there are some predefined intervals likes "this month" or "this year".

Others can be created by going back in time by a specific amount of days/months/years.

However, these are all relative to the current date, i.e. if one selects "last 1 month" this will show the last 30 days.

I find myself often in the situation in which I one want to see the performance of the last month, agnostic from the day of the current month.

I.e. if the current date is the 7th of May, I would want to have an easy option to see the performance from 01.04 - 30.04 without having to define a custom report interval for this period of the current year.

Doing so clutters the list of report intervals and one would always need to delete this interval again after creating it to keep the list clean.

**Comment by mierin12** [comment]
Done since [release 0.54.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.54.0) with https://github.com/portfolio-performance/portfolio/commit/2073f0983fc548550d40a0d57734f5102e25a261
