### ISSUE TITLE
CSV import of account transfers using different currencies shows an error message

### ISSUE THREAD

**Issue by ryivus** [portfolio-performance/portfolio#2250]
PP Version: 0.52.0

### Summary
There seems to be an issue with importing account transfers between accounts using a different currency.

### Steps
1. Create a transfer between two deposit accounts using different currencies
2. Export both Deposit Accounts to CSV
-> Or use attached files

[Example.zip](https://github.com/buchen/portfolio/files/6461254/Example.zip)
(Created a ZIP archive as CSV files are not allowed...)

3. Delete transactions in both deposit accounts
4. Try importing files
-> PP will cross out the account transfer with an error message saying the currency of the transaction does not match:
![grafik](https://user-images.githubusercontent.com/66179113/117866069-f9c1d380-b296-11eb-9b79-a6f993b31797.png)

It does not help to select different accounts from the drop downs.
Clicking around too much in this dialog might also lead to an illegal argument exception, but this is not the main concern of this bug entry.

![grafik](https://user-images.githubusercontent.com/66179113/117866595-9e441580-b297-11eb-8599-b4353d56293a.png)

**Comment by raschle** [comment]
Same problem as described here: https://forum.portfolio-performance.info/t/import-csv-datei-umbuchungen/7932

This is the only issue preventing a full import of all interactive brokers data into pp.
