### ISSUE TITLE
Error using "(" as search character in view "Performance", dialog "Datenreihe wählen"

### ISSUE THREAD

**Issue by 0mynona0** [portfolio-performance/portfolio#2273]
**Describe the bug**
Using "(" as seacrh character in view "Performance", dialog "Datenreihe wählen" leads to an internal error.

**To Reproduce**
1. Go to view "Performance", 
2. For any widget, right-click and open dialog "Datenreihe wählen".
3. Enter any search term including "(" (without "").

**Expected behavior**
"(" (without "") should be accepted as a search character and not lead to an exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/76954290/121185725-a7101300-c866-11eb-92bf-8c8e249224e1.png)

**Desktop:**
 - OS: Windows
- Version: 0.52.0 (Apr. 2021)
- Platform: win32, x86_64
- Java: 11.0.4+11-LTS, Azul Systems, Inc.

**Comment by chirlu** [comment]
You could try escaping the parenthesis with a backslash: `\(`

**Comment by mierin12** [comment]
Fixed in [release 0.69.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.69.0) with https://github.com/portfolio-performance/portfolio/pull/3965
