### ISSUE TITLE
Klassifizierungen: Suchfunktion wäre toll // search in classifications

### ISSUE THREAD

**Issue by MichaelMeier99** [portfolio-performance/portfolio#2275]
Just an idea:
PortfolioPerformance has this great feature: Klassifzierungen (classifications), which allows the user to set up his own criteria for his stocks.

If you have used this excessively, - it would be great to have a SEARCH function for this.
Just the same as for stocks, I make an upload, how the search looks there.

Is it hard to portate this to the 'classification' element?
Unfortunately I am not able to do this by myself.

Thousand thanks, if somebody is able to and does it.
![upload](https://user-images.githubusercontent.com/49785471/121732344-6af0e280-caf2-11eb-88e6-924bb6119c26.png)

**Comment by mierin12** [comment]
Done since [release 0.54.1](https://github.com/portfolio-performance/portfolio/releases/tag/0.54.1) with https://github.com/portfolio-performance/portfolio/commit/494870d01c385816324685787a00301e0d6a6d4f
