### ISSUE TITLE
PDF import for sberbank direct

### ISSUE THREAD

**Issue by martinspaniol** [portfolio-performance/portfolio#2362]
Currently direct pdf import of sberbank direct is not supported. Is it possible to implement?

The extracted pdf text using the debug functions is attached.
[Kontoauszug_sberbank.pdf.txt](https://github.com/buchen/portfolio/files/6912820/Kontoauszug_sberbank.pdf.txt)

**Comment by Nirus2000** [comment]
Hallo @martinspaniol 
could you please post several examples? 
For example, for the purchase and sale of shares or ETF's, and for dividends?

**Comment by martinspaniol** [comment]
Hi @Nirus2000,
sberbank only handles a savings account. You can't buy or sell shares there. So basically you deposit money and get interest over time. Currently I have no bank statement with interest listed. I think I might have one the next month. So if you need this I will upload it as soon as I got it. Thank you.

**Comment by Nirus2000** [comment]
Hello @martinspaniol 
that would be very good for the PDF importer to work properly.
Bye Alex

**Comment by Nirus2000** [comment]
It would be good if you please register in the forum at https://forum.portfolio-performance.info/ and create a post 
with the name "_PDF importer from Sberbank Direct_". 
Then please post the PDF debugs here.

You can see how it works in the video tutorial.

Video tutorial:
[Extract PDF documents for debugging](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)
