### ISSUE TITLE
Add hide data series in charts via single click in addition to context menu

### ISSUE THREAD

**Issue by tknuppe** [portfolio-performance/portfolio#2397]
The function to hide data series in charts is a great new feature. Let's make it even better by hiding data series in charts also via single click on the item in the legend in addition to context menu.

**Comment by mierin12** [comment]
Done on [release 0.71.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.71.0) with https://github.com/portfolio-performance/portfolio/commit/f7cd967b8476d42a68b83b189c04291ec781cbd6 (via double click).
