### ISSUE TITLE
Statement of Assets - Option To Show Total At The Top

### ISSUE THREAD

**Issue by metal450** [portfolio-performance/portfolio#2409]
Statement of Assets is the 'main' screen I use more than any other. However, as I have a large number of positions, each time I need to scroll to the bottom to check my 'total.' It would be great if there were a way to instead list the total at the top of the Statement of Assets page, to avoid the need to scroll to the bottom each & every time :)

**Comment by mierin12** [comment]
Done since [release  0.56.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.56.0) with https://github.com/portfolio-performance/portfolio/pull/2449
