### ISSUE TITLE
Trade Republic - Error when importing PDF documents with Bitcoin purchase

### ISSUE THREAD

**Issue by Photographix** [portfolio-performance/portfolio#2468]
**Describe the bug**
Error when importing PDF documents with Bitcoin purchase

**To Reproduce**
1. buy bitcoin at Trade Republic
2. Export Buy Order
3. Import into Portfolio Performance
4. error only 2 of 3 patterns recognised

**Expected behavior**
No problem importing - similar to shares at Trade Republic

**Screenshots**
![image](https://user-images.githubusercontent.com/16647382/137888999-99290703-d21a-4fc1-9156-476398502ed5.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [Server 21H2]
 - Version Portfolio Performance [0.55.0]

**Comment by Photographix** [comment]
PDF Autor: ''
PDFBox Version: 1.8.16
-----------------------------------------
TRADE REPUBLIC BANK GMBH  KASTANIENALLEE 32  10435 BERLIN
XXXXXX XXXXXX SEITE 1 von 1
XXXXXX XXXXXX DATUM 06.10.2021
XXXXXX XXXXXX ORDER e010-35b5
AUSFÜHRUNG fc83-aeb4
CRYPTO-WALLET BitGo
DEPOT 0125809301
ABRECHNUNG CRYPTOGESCHÄFT
ÜBERSICHT
Market-Order Kauf am 06.10.2021, um 21:10 Uhr (Europe/Berlin) im außerbörslichen Handel (Bankhaus 
Scheich).
Der Kontrahent der Transaktion ist Bankhaus Scheich Wertpapierspezialist AG.
POSITION ANZAHL KURS BETRAG
Bitcoin (BTC) 0,0026 Stk. 47.772,95 EUR 124,21 EUR
GESAMT 124,21 EUR
ABRECHNUNG
POSITION BETRAG
Fremdkostenzuschlag -1,00 EUR
GESAMT -125,21 EUR
BUCHUNG
VERRECHNUNGSKONTO VALUTA BETRAG
DEXXXXXXXXXXXX 06.10.2021 -125,21 EUR
Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.
Die Cryptowerte werden in einer zentralen Wallet bei dem Cryptoverwahrer BitGo Deutschland GmbH verwahrt.
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Düsseldorf Geschäftsführer
Kastanienallee 32 service@traderepublic.com AG Düsseldorf HRB 85864 Andreas Willius
10435 Berlin USt-ID DE307510626 Karsten Müller


I have "anonymized" the extract with some XXXXXXX

**Comment by Nirus2000** [comment]
Hello @Photographix 
now its time... the first crypto currency was supported...

Regards
Alex

**Comment by OnkelDok** [comment]
@Photographix: you have to wait for the next release. The current version (``0.65.1``) was released on [Aug 14, 2023](https://github.com/portfolio-performance/portfolio/releases/tag/0.65.1).
[The fix](https://github.com/portfolio-performance/portfolio/pull/3524) was merged 3 days ago.

Please test again with the next release.

**Comment by Nirus2000** [comment]
I have check this... and with the next release... it works.
