### ISSUE TITLE
Filter for security type not considered when adding a security to the portfolio

### ISSUE THREAD

**Issue by ogig33** [portfolio-performance/portfolio#2483]
**Describe the bug**
When adding a new security to the portfolio the filter option (stock/bond) is ignored, e.g. when selecting stock the result nevertheless lists bonds.

**To Reproduce**
1. Go to 'Alle Wertpapiere'
2. Click on (+) at the top right and select "Neues Wertpapier"
3. Enter e.g. "Sberbank" in search field and select "Aktie" as filter
4. Result list contains securities of type "Anleihe"

**Expected behavior**
Result list does only contain securities of the type selected in the search filter.

**Screenshots**
See screenshot.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Version: Portfolio Performance 0.55.0
<img width="634" alt="Bildschirmfoto 2021-10-29 um 13 06 27" src="https://user-images.githubusercontent.com/66212774/139424472-24c6287a-1904-4199-a3e4-865d3996590f.png">

**Comment by OnkelDok** [comment]
Currently the filter value is directly passed to the server which answers with a list of results (no filter on client side). It seems the server doesn't use this filter.
PP is searching for securities by this request:

https://www.portfolio-report.net/search?q=sberbank&securityType=share

As you can see if you enter the URL into browser, the selected security type is ignored. So it seems like a bug on server side and should be reported here: https://github.com/tfabritius/pr-www

However, if it will not be fixed on server side there is the possibility to filter results on client side (PP).

**Comment by ogig33** [comment]
Thanks for analysis and reporting the bug to the server team!

**Comment by OnkelDok** [comment]
The bug was fixed on server side: tfabritius/pr-www#223
This issue can be closed.

**Comment by OnkelDok** [comment]
> The bug was fixed on server side: [portfolio-report/pr-www#223](https://github.com/portfolio-report/pr-www/issues/223) This issue can be closed.
