### ISSUE TITLE
Chart with percentage securities grow/loss instead of absolute price value

### ISSUE THREAD

**Issue by wgebis** [portfolio-performance/portfolio#2569]
**Is your feature request related to a problem? Please describe.**
There is no possibility to view historical percentage changes on the chart of securities. Only absolute price values are presented on axis-Y.

**Describe the solution you'd like**
Add different axis-Y values (grow/loss in percentages).

<img width="356" alt="Screenshot 2021-12-05 at 22 52 45" src="https://user-images.githubusercontent.com/32294473/144766097-653dde14-3c89-455e-81dd-b1c6f0f92e6c.png">

**Comment by mierin12** [comment]
Done on [release 0.63.0]( https://github.com/portfolio-performance/portfolio/releases/tag/0.63.0) with https://github.com/portfolio-performance/portfolio/pull/3006
