### ISSUE TITLE
Total TTWOR on "Statement of Assets"

### ISSUE THREAD

**Issue by wgebis** [portfolio-performance/portfolio#2570]
**Is your feature request related to a problem? Please describe.**
Statement od Assets is the one of the greatest vie in PP. I don't know why in row where total values are presented there in no values of certain columns e.g. TTWOR, it should be pretty useful. 

<img width="277" alt="Screenshot 2021-12-05 at 23 18 56" src="https://user-images.githubusercontent.com/32294473/144766235-ea645e70-7a55-4f9a-a6a0-7f16a8af33b3.png">

**Comment by mierin12** [comment]
Done since [release 0.71.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.71.0) with https://github.com/portfolio-performance/portfolio/commit/0f7eb387d416f556cef9a4429a82cde5f4373db7
