### ISSUE TITLE
How to Merge security ?

### ISSUE THREAD

**Issue by vipuldamani** [portfolio-performance/portfolio#2616]
**Is your feature request related to a problem? Please describe.**

Import data via *.CSV in some family account , all security show different security,

if any name change of symbol or security name via take over by other group, in that case also face issue of security merge. 

**Additional context**
![image](https://user-images.githubusercontent.com/57120750/148018652-9faa5d24-1ae6-46b6-82c1-6192853b734e.png)

**Comment by Nirus2000** [comment]
this issue is fixes with a7446a870a77aeaa13bad2bfe75e20d67c840327
