### ISSUE TITLE
[Mac] Standard Mac entries like About, Preferences are not translated

### ISSUE THREAD

**Issue by vogella** [portfolio-performance/portfolio#2652]
Starting the application under Mac with a German local uses in most cases German. 

Unfortunately, the default entries from Mac are not translated.

![image](https://user-images.githubusercontent.com/139910/150128481-c7ec8c36-80c6-43f3-b074-129a08e3e792.png)

Is this possible? https://github.com/buchen/fix-info-plist-maven-plugin seems to do the right thing but maybe it is necessary to overwrite certain properties?

**Comment by tquellenberg** [comment]
My guess:

When i look at [Display.java](https://git.eclipse.org/c/platform/eclipse.platform.swt.git/tree/bundles/org.eclipse.swt/Eclipse%20SWT/cocoa/org/eclipse/swt/widgets/Display.java) from `org.eclipse.swt.cocoa.macosx.aarch64_3.117.0.v20210906-0842.jar` the code searches for a `DefaultApp.nib` file (Line 5657) to create the system menu. But the current MacOS Monterey doesn't provide this file. This happened in the past with older versions of MacOS (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=520176 ).

In `Display.java` there is a fallback, when the `DefaultApp.nib` is not found. ( `createMainMenu()` ). This fallback uses `SWT.getMessage("Preferences...")` and looks in the properties file of the language pack (`org.eclipse.swt.nl_de_4.21.0.v20210925020001.jar`). But there is no entry for the key "Preferences...". And so the english text is used.

I don't know if I'm right, but to me this looks like a problem of SWT and/or MacOS. 
Any ideas @vogella ?

**Comment by vogella** [comment]
Thanks @tquellenberg for the detailed analysis. We discussed that on the Eclipse mailing list and opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=578406 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=578405 to fix that on the SWT side. 

Thanks for the analysis, this resulted in the bug reports.

**Comment by tquellenberg** [comment]
You are welcome. Searching for bugs is my passion ;-)

**Comment by buchen** [comment]
Fixed (by updating to the latest Bable translation files)
