### ISSUE TITLE
Abstand zum höchsten Kurs je Wertpapier (innerhalb der Haltedauer)

### ISSUE THREAD

**Issue by simpsus** [portfolio-performance/portfolio#266]
Also eine Variante des Drawdowns die die Frage beantwortet: Wie weit sind wir momentan vom neuen Hoch entfernt. Notiere ich auch. Ist hier die % Differenz interessant oder auch der Abstand in Zeit seit dem letzten Hoch?

Auch hier wieder der 3 Satz:
- Daten sammeln
- Berechnen. Hier muss nicht die Vola berechnet werden, das ist etwas einfacher, aber muss auch für jedes Papiert gemacht werden
- Anzeigen. Wieder das Problem: Wie bindet man das sinnvoll in das Programm ein?

**Comment by buchen** [comment]
> Wie weit sind wir momentan vom neuen Hoch entfernt.

Oder, anders formuliert, wie viel Prozent liegt die aktuelle Position unter der Höchstbewertung, oder?
Muss man nicht einfach (aktuellen Wert) / (Höchstkurs in Berichtszeitraum * Anzahl Stücke) rechnen? 


> Anzeigen. Wieder das Problem: Wie bindet man das sinnvoll in das Programm ein?

Für mich wäre das eine Spalte in der Wertpapier-Performance.

**Comment by mbs2016** [comment]
es wäre meines Erachtens aufschlussreich, wenn man über eine Periode alle Drawdowns, sofern diese existieren, auflisten würde. Ich habe, beispielhaft für WP LU0322253906 (db X-trackers MSCI Europe Small Cap (DR) 1C), die Ergebnisse - wie ich sie mir als sinnvoll vorstelle - dargestellt.

[sample output Drawdown.txt](https://github.com/buchen/portfolio/files/102379/sample.output.Drawdown.txt)

Die Tabelle kann man einfach erzeugen aus der Rendite geschenkt bekommt bei der Berechnung des TTWRORs.
