### ISSUE TITLE
Klassifizierung: Berichtszeitraum für das Flächendiagramm

### ISSUE THREAD

**Issue by Fruchtzwerg94** [portfolio-performance/portfolio#2686]
**Issue:**
Der im Flächendiagramm verwendete Berichtszeitraum für Wertpapierklassifizierungen orientiert sich immer am aktuell gewählten Berichtszeitraum der in den Diagrammen der Vermögensaufstellung oder der Performance festgelegt wurde:
![grafik](https://user-images.githubusercontent.com/29866610/152655581-d828fadf-ecbe-40d0-ad8b-d8d537355e5e.png)
Der Berichtszeitraum lässt sich jedoch nicht direkt im Flächendiagramm für Wertpapierklassifizierungen festlegen:
![grafik](https://user-images.githubusercontent.com/29866610/152655592-a8495d24-4b12-449c-86e5-81278a2ced8e.png)
Somit muss zum Festlegen des Zeitraums jedes mal die Seite gewechselt werden.

**Solution:**
Die Auswahl des Berichtszeitraums soll auch im Flächendiagramm für Wertpapierklassifizierungen möglich sein.

**Comment by mierin12** [comment]
Done with [release 0.65.2](https://github.com/portfolio-performance/portfolio/releases/tag/0.65.2) with https://github.com/portfolio-performance/portfolio/pull/3285
