### ISSUE TITLE
Depotübertrag von 1822direkt

### ISSUE THREAD

**Issue by JokerGermany** [portfolio-performance/portfolio#2764]
```
PDFBox Version: 1.8.16
-----------------------------------------
Postfach · 60255 Frankfurt am Main
Depotnummer 1234567890
Kundennummer 1234567
Max Mustermann
Auftragsnummer 123456/78.00
Herrn Datum 30.03.2022
Max Mustermann Ihr Berater 1822direkt
Muster Str. 9 Telefon 069 94170-0
12345 Musterstadt , Musterbunde Umsatzsteuer-ID DE123456789
Depotbuchung - Belastung
unentgeltlicher Depotübertrag, Gläubigeridentität
Anschaffungsdaten werden soweit vorhanden und gesetzlich vorgesehen übermittelt.
Nominale Wertpapierbezeichnung ISIN (WKN)
Stück 3 XTR.(IE) - MSCI WORLD IE00BJ0KDQ92 (A1XB5U)
REGISTERED SHARES 1C O.N.
Wertpapierrechnung Lagerland Irland
Schlusstag 28.03.2022 Auftrags-Nr. 123456/10.00
Valuta 30.03.2022 externe Referenz-Nr. IR12345
Nominale Wertpapierbezeichnung ISIN (WKN)
Stück 2 LYXOR MSCI EMERG.MKTS U.ETF LU0635178014 (ETF127)
INH.-AN. I O.N.
Girosammelverw. mehrere Sammelurkunden - kein
Stückeausdruck -
Schlusstag 28.03.2022 Auftrags-Nr. 123456/11.00
Valuta 30.03.2022 externe Referenz-Nr. KP12345678901234
Empfängerdaten
Depotkonto-Inhaber Max Mustermann
Depotkonto-Nr. 1234567890
Baader Bank AG
Die entsprechenden Werte haben wir Ihrem Depotkonto belastet.
Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.
1234.56789012.34567890D12

```

**Comment by JokerGermany** [comment]
Hier sollte die Funktion Umbuchung genutzt werden.

**Comment by Nirus2000** [comment]
Gibt es denn schon ein PDF-Debug von deinem neuen Broker für die Einbuchung?

**Comment by JokerGermany** [comment]
> Gibt es denn schon ein PDF-Debug von deinem neuen Broker für die Einbuchung?

Jetzt schon
`PDFBox Version: 1.8.16
-----------------------------------------
Scalable Capital GmbH 
Seitzstraße 8e
80538 München 
service@scalable.capital
Seite 1/1
Herrn München
30.03.2022
Max Mustermann
Muster Str. 9 Max Mustermann
12345 Musterstadt Stamm-Nr.: 1234567    Portfolio: 1
Depot-Nr.: 1234567890
Vorgangs-Nr.: 123456
Referenz-Nr.: 123456789
Depoteinlieferung
Nominale ISIN: IE00BJ0KDQ92 WKN: A1XB5U
STK 3 Xtr.(IE) - MSCI World
Registered Shares 1C o.N.
Verwahrart: Girosammelverwahrung Handelstag: 28.03.2022
Lagerstelle: 100 Valuta: 30.03.2022
Lagerland: Deutschland
Nominale ISIN: LU0635178014 WKN: ETF127
STK 2 Lyxor MSCI Emerg.Mkts U.ETF
Inh.-An. I o.N.
Verwahrart: Girosammelverwahrung Handelstag: 28.03.2022
Lagerstelle: 100 Valuta: 30.03.2022
Lagerland: Deutschland
Bitte prüfen Sie diese Mitteilung. Etwaige Einwendungen bitten wir unverzüglich zu erheben. 
Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.
Scalable Capital GmbH • Geschäftsführung: Erik Podzuweit, Florian Prucker, Martin Krebs, Peter Gaubatz • HRB 217778, Amtsgericht München • USt-IdNr. 
DE300434774 • www.scalable.capital
 
Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft • Weihenstephaner Straße 4 • 85716 Unterschleißheim • Deutschland
Vorstand: Nico Baader (Vorsitzender), Dietmar von Blücher, Oliver Riedel • Vorsitzender des Aufsichtsrates: Dr. Horst Schiessl • Amtsgericht München 
HRB 121537 • Sitz der Gesellschaft: Unterschleißheim • StNr. 123/456/78901 • USt-IdNr. DE123456789 • LEI: 123456JF7PPEDUR89H01
T 00800 00 586336* • service@baaderbank.de EINLIEFERUNG-012.345
* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.
 
`
