### ISSUE TITLE
PDF import from Scalable

### ISSUE THREAD

**Issue by mrinker-dev** [portfolio-performance/portfolio#2872]
**Describe the bug**
Import of Scalable PDF does not work properly. Only deposits are recognized, all other bookings are missing. 

**To Reproduce**
Import PDF (e.g from may)

**Expected behavior**
All bookings are imported

**Screenshots**
will follow. 

 - OS: Windows
 - Version 0.58.3

**Comment by Nirus2000** [comment]
n the periodic account statement transactions, purchase, sale and dividends were previously also read out. This works, but is not correct. No fees or taxes are recorded for these entries.
We therefore limit ourselves only to deposits and deliveries, as well as any fees for the account. The purchases, sales and dividends are recorded in other documents with fee's and taxes.

**Comment by mrinker-dev** [comment]
Thanks. It worked before (for me) and was more easy, because only one import was needed. Maybee it should be a feature request

**Comment by mees** [comment]
I can reproduce this bug, though it seems from reading also in the forum that this change was supposed to be a feature rather than a bug. It's very cumbersome to have to download one pdf per transaction and import them manually, rather than just importing one pdf with the monthly summary. Please revert this change ASAP.

**Comment by jdnumm** [comment]
Can confirm this as well. I think it should be avoided to import wrong values, at least without a warning. 

I inform scalable about this issuer and requested a bulk download for Transactions, like they already have for the Mailbox. Maybe it helps if other user open a similar request.

**Comment by Alexander-Shukaev** [comment]
Just for the record, as per #2882, sometimes fees are still booked directly from cash account (perhaps when it has enough value), so the periodic account statement document is still important to import together with all the separate transaction documents.

**Comment by Alexander-Shukaev** [comment]
@mees, you can import multiple PDFs in one action by selecting all of them.  So the only usability issue here is downloading separately those PDFs.  If they can be bundled somehow by Baader or Scalable, this would solve the problem.

**Comment by johseg** [comment]
I'm also affected by this. I tried exporting them automatically, but the interface is very script unfriendly. If that could be solved with the easy to export monthly statements this would be appreciated

**Comment by funnym0nk3y** [comment]
> @mees, you can import multiple PDFs in one action by selecting all of them. So the only usability issue here is downloading separately those PDFs. If they can be bundled somehow by Baader or Scalable, this would solve the problem.

Unfortunately that hasn't happened half a year later. As they aren't accessible for batch download one needs to open each transaction and download the detailed statement seperately. 

@jdnumm Did they reply to your request?

**Comment by jdnumm** [comment]
@funnym0nk3y no, not really. I ended up using the Baader website and some JavaScript in the dev console to start a batch download. But maybe some browser plugins will do the same (not tested) https://addons.mozilla.org/de/firefox/addon/link-bulk-downloader/

**Comment by funnym0nk3y** [comment]
> @funnym0nk3y no, not really. I ended up using the Baader website and some JavaScript in the dev console to start a batch download. But maybe some browser plugins will do the same (not tested) https://addons.mozilla.org/de/firefox/addon/link-bulk-downloader/

That did work for cash transactions and purchases of stocks?
