### ISSUE TITLE
Percentage chart

### ISSUE THREAD

**Issue by Rubengarber** [portfolio-performance/portfolio#2881]
Add in Scale Selection Percentage Chart
![Percentage chart](https://user-images.githubusercontent.com/77247699/172333487-ebf98566-acf4-47d3-8aee-fe5ebff25588.jpg)

**Comment by OnkelDok** [comment]
I have created a PR for a percentage axis here: #3006
Would that meet your request? Then I would reference this issue there.

**Comment by Nirus2000** [comment]
This issue is closed with #3006
