### ISSUE TITLE
PDF Import merkt sich letzen Pfad nicht mehr

### ISSUE THREAD

**Issue by fragger1991** [portfolio-performance/portfolio#2887]
**Describe the bug**
Der zuletzt verwendete Pfad für den PDF Import geht immer verloren, ich muss mich also jedes mal wieder durch den Pfad klicken.

Ich speichere meine Dokumente auf meiner NAS, hier speichere ich auch die Dokumente in jeweils verschiedenen Ordnern. Ich habe z.B. für Dividenden, Ertragsgutschriften und Wertpapierabrechnungen einen Ordner. Wenn ich nun, wie heute, in jedem Ordner jeweils ein Dokument habe, muss ich für alle Importe mich immer durch den kompletten Pfad durchklicken, das ist sehr nervig und umständlich.

**To Reproduce**
Auf "Datei" -> "Importieren" -> "PDF Bankdokumente" klicken, die Dokumente importieren und anschließend noch mal. Der letzte Pfad ist weg.

**Expected behavior**
Ich erwarten, dass der letzte Pfad gespeichert bleibt - so wie es vor 1 oder 2 Updates auch der Fall war.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Version 0.58.4 (Juni 2022)

**Comment by Connum** [comment]
Scheint mit der 0.59.1 behoben zu sein?
