### ISSUE TITLE
Windows installer does not set DisplayVersion when registering the uninstaller

### ISSUE THREAD

**Issue by l-c-g** [portfolio-performance/portfolio#3016]
**Describe the bug**
Windows installer does not set DisplayVersion when registering the uninstaller. This is used by winget to determine the currently installed version and to compare it to the newest available version during `winget upgrade`. See [ItzLevvie's comment on winget issue 1356](https://github.com/microsoft/winget-cli/issues/1356#issuecomment-895409232).

**To Reproduce**
1. Use the installer on Windows (or run `winget install buchen.portfolio`)
2. Check in the registry for the DisplayVersion value in 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Portfolio Performance' 
3. Notice that there is no DisplayVersion value
4. (Alternatively, wait for a new Portfolio Performance release and notice the warning during `winget upgrade` about unknown version numbers. Checking the registry is faster.)

**Expected behavior**
DisplayVersion should exist and contain the currently installed version of the application.

**Desktop (please complete the following information):**
 - Windows 11 22H2
 - Portfolio Performance 0.59.2

**Comment by Morpheus1w3** [comment]
Well, Portfolio Performance has a very well implemented self-update which checks every start, if the software is up to date. External update clients are omitted, as they have often have difficulties with Java compiled software.

**Comment by CanePlayz** [comment]
@l-c-g The installer definition is located in `portfolio-product/installer/installer.nsi`. The version should be set in line 74 with this `WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$APPNAMEFULL" "DisplayVersion" "${SOFTWARE_VERSION}"`. Now, I don't know where this variable is coming from, but there seems to be an issue with it

@Morpheus1w3 Would there be anything you could do now with this new information?

**Comment by l-c-g** [comment]
@CanePlayz I know where this registry entry is set, I made [the pull request](https://github.com/portfolio-performance/portfolio/pull/3017) that added [the line](https://github.com/portfolio-performance/portfolio/blame/6608f7bbb80e6c995c8c8861e1b598c4ea3636f8/portfolio-product/installer/installer.nsi#L74).

In fact, when your comment came in, I was surprised to see this still open. @buchen had merged the code and my original issue with winget has been resolved ever since. I did not follow up on this issue after that but I am closing it now.

**Comment by CanePlayz** [comment]
@l-c-g Ah, thanks for fixing it. I hadn't re-installed PP in quite a while so I didn't notice that it had been fixed, but it totally makes sense with the custom upgrade behaviour.
