### ISSUE TITLE
[Feature Request] Please add weblink field to Securities

### ISSUE THREAD

**Issue by forReason** [portfolio-performance/portfolio#3021]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when researching securities which I have in portfolio performance. 
I have to google the Company/Webpage, which can be cumbersome.

**Describe the solution you'd like**
It would be highly convenient if it was possible to add a string field for a web-url
![image](https://user-images.githubusercontent.com/12736950/199128703-7a602c2f-a092-4a1b-8e7d-316ae6508025.png)

With an additional context-menu entry "open homepage in browser"
![image](https://user-images.githubusercontent.com/12736950/199129024-25c6d012-9486-4c00-8847-db3a7d7b6971.png)

**Describe alternatives you've considered**
Right-click -> bookmarks -> select bookmarks also seems cumbersome to me
maybe, allowing to set a bookmak as default there.

**Additional context**
it is just a more convenient/quick way to open the companies/projects webpage (or whatever you want to add as default)

**Comment by dylan09** [comment]
You could easily add additional entries for the "Open in Browser" menu.
Take a look on "Settings" at the bottom of the sidebar. I have created an entry for IR homepage, one for links to  SEC   / OSCAR, ...Simple and flexible

**Comment by flywire** [comment]
Try this:
1. In Statement of Attributes
2. Show or hide columns
3. Attributes
4. Website

Click the arrow on the left side of the Website column to go to the link.

**Comment by sebasbaumh** [comment]
You can also just add an URL in the "Notes" section of the security like that:
![PortfolioPerformance_2023-01-29_12-30-27](https://user-images.githubusercontent.com/670885/215323185-d082d26a-773f-4861-8b56-03ff90beecda.png)

It will show up in the context menu like that:
![2023-01-29_12-30-47](https://user-images.githubusercontent.com/670885/215323192-bfa496b1-5ba2-41e5-b31c-eeab8edbc238.png)

You see, multiple URLs are possible as well.

This functionality was integrated in this PR: https://github.com/buchen/portfolio/pull/1318

**Comment by pfalcon** [comment]
@chirlu: There seems to be multiple quality solutions offered for this feature request, perhaps it can be closed now?

**Comment by flywire** [comment]
> can be closed now?

The issue seems to be a lack of documentation, for English at least. That should be fixed before it is closed.

**Comment by OnkelDok** [comment]
@forReason, do you think this issue should remain open?
In previous comments several ways were descibed to add url/weblinks to a security.

@flywire: in case of missing documentation, please use the [corresponsing git repo](https://github.com/portfolio-performance/portfolio-help) to insert issue or (even better) create a pull request to extend the [help page](https://help.portfolio-performance.info/en/).

**Comment by Nirus2000** [comment]
Solution:

https://github.com/portfolio-performance/portfolio/assets/45203494/6747df6d-26f8-4608-8584-d4291c117906
