### ISSUE TITLE
CSV Interpreter misinterprets small share values

### ISSUE THREAD

**Issue by jdohm** [portfolio-performance/portfolio#3022]
**Describe the bug**
When importing using the csv importer, small shares values such as 0.00000198 are interpreted as 1.98. 

**To Reproduce**
1. Create/Change a portfolio transaction CSV with an shares entry with a small value.
2. Go to File -> Import -> CSV Files
3. Open CSV file containing small shares value
4. See shares displayed as 1.98e-6, click on next
5. See error, as shares display 1.98 now

**Expected behavior**
Value should never change. The expectation would be to either see 0.00000198 or still 1.98e-6.

**Screenshots**
![image](https://user-images.githubusercontent.com/9203094/199286559-ea1a6253-3389-404e-a4b3-02a4a8b5b242.png)
![image](https://user-images.githubusercontent.com/9203094/199286898-d1007afb-c1ca-4e2a-802c-1adb662c22d6.png)

**Desktop (please complete the following information):**
 - OS: (Arch)Linux - Flatpak
 - Version 0.59.2

**Comment by Nirus2000** [comment]
Hallo @jdohm 
Please create a test file and upload it here. Then we will have a look at it.

Alex

**Comment by jdohm** [comment]
Hi Alex, good points, here is a sample csv
[csv_example.csv](https://github.com/buchen/portfolio/files/9913488/csv_example.csv)

**Comment by Nirus2000** [comment]
Hallo @jdohm 
I have looked at the CSV.
So, you would need to format the column beforehand, so import it into Excel once and set the cell formatting. Then export it back to CSV.
PP checks the numbers before importing and removes all characters which do not correspond to `0-9,.-`. Because your values are displayed with exponent. To develop a solution is very difficult, because the exponent notation can be very different in the different office programs.
Therefore, the simplest solution is to format the cells (numbers) correctly before importing.

Alex

**Comment by jdohm** [comment]
Good morning @Nirus2000 
so sorry should have checked that. OnlyOffice shows it as 0.00000198... Will check to change the export/conversion to end up without exponent. Thanks for your help, I will report back once tested to verify that it works when exported correctly. Just in case someone else runs into the same issue :)

**Comment by Morpheus1w3** [comment]
@Nirus2000 
Did you know if it's possible somehow to combine https://stackoverflow.com/a/36884961 with 
https://github.com/buchen/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/datatransfer/csv/CSVExtractor.java#L105-L107 ? Maybe this could be fix this problem in here?!

**Comment by jdohm** [comment]
I just confirmed, that using 0.00000198 instead of 1.98e-6 works just fine. 
@Morpheus1w3 solution could work i guess, but unless there is a real need I would suggest closing the issue and leaving the code as is. Thanks for your Help, great community!

**Comment by Nirus2000** [comment]
Halle @jdohm and @Morpheus1w3 
I'll try my luck with the pull request. 

Greetings
Alex
