### ISSUE TITLE
Performance-neutral transfers doesn't take first day into account

### ISSUE THREAD

**Issue by ucczs** [portfolio-performance/portfolio#3064]
**Describe the bug**
**Performance-neutral transfers** doesn't take bookings at **first day** into account for both the widget in "Performance" and in the "Calculation" view.

**To Reproduce**
1. Add a deposit (e.g. 1000 €) for the 01.01.2022
2. Go to "Calculation"
3. Select Report Interval: From 01.01.2022, To 31.01.2022
4. Under "Performance neutral Transfers", Deposit shows zero value.
5. Same behavior in a "Performance neutral Transfers" widget.

**Expected behavior**
Since the deposit took place during the selected report interval, the deposit should be listed in "Performance neutral Transers" under calculation and in the widget.

**Screenshots**
Screenshot attached:
![MissingDeposit](https://user-images.githubusercontent.com/33268453/205494187-4a713fc2-42d1-4952-adff-7f0188ce39d9.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.59.4

**Additional Info**
A similar issue was already reported and fixed here. But it seems like the problem is still around. 
https://github.com/buchen/portfolio/issues/1600

**Comment by chirlu** [comment]
Not a bug. “Report Interval: From 01.01.2022, To 31.01.2022” means that 2022-01-01 is excluded (or that the reporting period starts at end-of-day of 2022-01-01, if you prefer).
