### ISSUE TITLE
winget not able to retrieve version number

### ISSUE THREAD

**Issue by CanePlayz** [portfolio-performance/portfolio#3198]
**Describe the bug**
winget is not able to retrieve the version number of Portfolio Performance.

**To Reproduce**
1. Do "winget upgrade" in your terminal of choice

**Expected behavior**
See version number

**Screenshots**
![image](https://user-images.githubusercontent.com/81419612/221043566-37920913-9242-4efa-8a3b-f1e7d14c4903.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.61.2

**Comment by OnkelDok** [comment]
@CanePlayz: is this related to #3016?

**Comment by CanePlayz** [comment]
> @CanePlayz: is this related to #3016?

Unfortunately, I don't understand the technical details hence I cannot tell this for sure, but since the old issue has been closed as completed and the issue still persists, I think we should leave this open. Just my opinion though.

**Comment by Morpheus1w3** [comment]
Well, I'm not sure at all if Portfolio Performance was registered at Microsoft's installl engin platform, however https://learn.microsoft.com/en-us/windows/package-manager/package/manifest should give a first indication of requirements and additional workloads

**Comment by OnkelDok** [comment]
> but since the old issue has been closed as completed

No the issue #3016 is still open. The other one describes that the version was not set correctly. And your issue reports that the winget cannot determine the version (because it was not registered before).

**Comment by CanePlayz** [comment]
Oh yeah sorry, my bad.

**Comment by CanePlayz** [comment]
Sorry if I sound impatient or impolite, but wouldn't it be easy to show the app's version in the Windows settings? 😅 Most other applications do that as well.

**Comment by CanePlayz** [comment]
Closing as duplicate of #3016
