### ISSUE TITLE
Consider verification on Flathub

### ISSUE THREAD

**Issue by mikeGolf08** [portfolio-performance/portfolio#3199]
**Is your feature request related to a problem? Please describe.**

It would be beneficial to get "Portfolio Performance" verified on Flathub because it'll be trustworthy to see for the user. The list of verfied apps getting bigger and bigger day by day (https://beta.flathub.org/apps/collection/verified) and since it is a beta version of Flathub but is going to be rolled out in 2023 it is better jump on the train sooner then later.

**Describe the solution you'd like**

As far as I know the developer @buchen has to login with his Github account at the Flathub developer account but to give you three sources about this:
- https://linuxnews.de/2023/02/16/verifizierte-flatpaks-bald-auf-flathub/
- https://discourse.flathub.org/t/how-do-you-get-a-flathub-submission-verified/3714
- https://discourse.flathub.org/t/situation-report-new-flathub-website-work-app-verifications-logins-etc/2259/9#verified-apps-2

**Thanks**

To @buchen for the great work and to @deisi for the work on getting the application on Flathub !

**Comment by mikeGolf08** [comment]
Any considerations yet?

Flathub's new website (https://flathub.org/) is now live so users are able to see verifications now and can filter them.
Might be the time to think about verification or @buchen ?

**Comment by deisi** [comment]
Thanks for the flowers :)
Maybe @buchen  wants to have a decent flatpak first, and not just a wrapper around the appimage.

**Comment by buchen** [comment]
I am happy to do the verification.

I logged into Flathub with my Github account, but it says "no apps to show".

I am not sure whether this is due to the recent transfer of the repository (see #3458) or because I am not associated with the flathub repository of PP.

Let's first complete the transfer. I have created a PR flathub/info.portfolio_performance.PortfolioPerformance#78 that updates the URLs

**Comment by buchen** [comment]
FYI, I was able to trigger the verification process. The Flathub site says: "Your app is currently verified by your website portfolio-performance.info". I assume it will take some time for the blue checkmark to appear.

**Comment by buchen** [comment]
The blue checkmark showed up.
