### ISSUE TITLE
Allow option to disable hover preview for Realised Gains & Unrealised Gains in Security View

### ISSUE THREAD

**Issue by dakkusingh** [portfolio-performance/portfolio#3225]
Hi,
when you have a LOT of trades for a given security, the hover preview in Security View for Realised Gains & Unrealised Gains columns can take crash the UI - i imagine its trying to render all the trade calculations for the hover!

It would be great if there was an option to disable the hovering popup functionality.

For now, I have to remove the Realised Gains & Unrealised Gains columns, its very easy to accidentally trigger the popup and crash the app.

**Comment by buchen** [comment]
Thanks @dakkusingh for the bug report.

I'll check how to limit the data shown to a reasonable amount
