### ISSUE TITLE
Coingecko no more quotes

### ISSUE THREAD

**Issue by metal450** [portfolio-performance/portfolio#3369]
**Describe the bug**
As of the past day or two, it has suddenly stopped receiving quotes from Coingecko. These are all securities that previously worked, and have not been edited. When I edit the security and go to the "Historical Quotes" tab, it shows "Loading..." for a moment and then the table is empty. The "Show server response" button is dimmed, so there is no way to debug what it's getting back from the server.

**To Reproduce**
1. Go to All Securities
2. Observe that any securities that was downloading quotes from Coingecko is no longer receiving quotes (per description above)

**Expected behavior**
Should receive quotes from COingecko

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.62.1

**Comment by Nirus2000** [comment]
is done.
