### ISSUE TITLE
scalable capital cash transfers

### ISSUE THREAD

**Issue by funnym0nk3y** [portfolio-performance/portfolio#3467]
**Is your feature request related to a problem? Please describe.**
I like to import all relevant transactions from the accumulated monthly statement scalable offers. However cash transactions prior to investment plan execution are classified as "Einlagen"/"deposits". However I also track the reference bank account from where the deposits are from with portfolio. This creates the situation where the use of the import funciton is kind of odd because AFAIK there isn't the possibility to change the type of the transaction to "transfer". 

**Describe the solution you'd like**
I'd like to have the possibility to change the transaction type from "deposit" to "transfer" and add a source account. It would be even better if the source account could be infered from the IBAN (part) given in the accumulated statement.

**Comment by Nirus2000** [comment]
PDF-Debug?!

**Comment by funnym0nk3y** [comment]
I don't think it belongs to PDF debug specifically. Could be the case for any bank. 
Portfolio does recognize everything it could infer from the bank statement (a transfer can be seen as a deposit if the source account is unknown). But in this case the source account is also modelled in portfolio so I'd like to add information portfolio couldn't infer.

**Comment by Nirus2000** [comment]
Well, just rename the ISSUE correctly and describe your concern accurately and extensively. So this ISSUE / Feature simply confuses...

**Comment by funnym0nk3y** [comment]
Unfortunately I can't change the issue title because I don't have permission to do so.
