### ISSUE TITLE
Zeiträume auch in der Klassifikation ändern / anzeigen

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#347]
> Im Moment kann man Zeiträume nur unter "Berichte" in den Dropdown-Menüs jeweils oben rechts abspeichern und verändern. Die dortigen Einstellungen werden anschließend auch für "Klassifizierungen" verwendet, obwohl man die Zeiträume dort weder sehen noch verändern kann. Das macht die Sache etwas intransparent. Idealerweise würde der augenblicklich betrachtete Zeitraum für das gesamte Programm (global) an derselben Stelle (z.B. in der linken Navigationsleiste) dargestellt und verändert.

**Comment by mierin12** [comment]
Done since [release 0.65.2](https://github.com/portfolio-performance/portfolio/releases/tag/0.65.2) with https://github.com/portfolio-performance/portfolio/commit/cd0beebcf3e0979fc3c79ebb22cc55ac76db1244 from https://github.com/portfolio-performance/portfolio/pull/3285
