### ISSUE TITLE
Deactivation of notes in the importers

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio#3500]
Add a checkbox in settings to disable notes extracted by PDF and IB-Flex import.
With the CSV Importer, the user can decide for himself by configuring the splitter. therefore, the feature is not needed here.

**Default value is:** Notes are set by importer.

_Perhaps this deactivation should be made selectable on every importer. 
PDF importer: deactivation of notes
IB-Flex-Importer: deactivation of the notes_

**Comment by buchen** [comment]
Could this be an option on the "review imported items" screen?
Then the user can decide to not include a) notes and b) source fields

**Comment by Nirus2000** [comment]
> Could this be an option on the "review imported items" screen?
> Then the user can decide to not include a) notes and b) source fields

Then the user would have to select each element of say 20 imported documents. Not a good idea.
I can imagine that in the settings the user generally gets the option if he wants to import notes via the importers. 
And second, whether he wants to import notes in the import dialog itself.
![grafik](https://github.com/portfolio-performance/portfolio/assets/45203494/81a26a8f-2c02-4e6d-a389-48d2121df757)

---

The source field should not be touched. (Other feature idea)
Here is still the idea in the main settings to store a path, which is searched by the source field and the file is then opened. 
Later also to store the file name itself.
