### ISSUE TITLE
add Traditional Chinese (zh-TW) translation 

### ISSUE THREAD

**Issue by edotlitw** [portfolio-performance/portfolio#3529]
Hi!

I would like to make translation to Traditional Chinese. I have registered POEditor.  Now, I am wait for an approve to start translation work.

**Comment by Nirus2000** [comment]
Hello @edotlitw 
Which language do you want to add?
Please tell us this...

Choose your language and tell us
![grafik](https://github.com/portfolio-performance/portfolio/assets/45203494/cc03fde9-39f7-44ff-8431-6cf5b936b053)
![grafik](https://github.com/portfolio-performance/portfolio/assets/45203494/b6a69e3c-299c-4e78-a2d8-a95ed759893d)

**Comment by buchen** [comment]
I believe I have approved you in the app.


In general, the translation is pretty much complete and I already got some feedback from translators. I plan to include it in the next release of PP.

**Comment by edotlitw** [comment]
Thank you for approving my request. I got approved to start translation work but found nothing I could do. Other translators has finished translation of zh-TW. I'm looking forward to using zh-TW in next release.
