### ISSUE TITLE
[macOS] unexpected signature change

### ISSUE THREAD

**Issue by core-code** [portfolio-performance/portfolio#3534]
without any kind of heads-up
the security-relevant codesignature has changed in the newest release:
```
Andreas Buchen (9CRL3WKCZ8)
=> 
MSM Mannheimer Software-Manufaktur UG haftungsbeschrankt (P3N6NZSUQK)
```
is the new release legit despite the unexpected signature?

**Comment by buchen** [comment]
Fair point. Yes the signature change is valid. I should have added it to the release notes.

I was trying to save the 100 Euros on my personal developer account...

Out of curiosity, how did you notice? I did not expect anybody to see this as it is relevant only to new installations.
