### ISSUE TITLE
(macOS) PP opens as two windows

### ISSUE THREAD

**Issue by milaan-muc** [portfolio-performance/portfolio#3536]
Since the the last patches i suddenly get two windows when opening PP.

![Bildschirmfoto 2023-09-06 um 08 45 44](https://github.com/portfolio-performance/portfolio/assets/3469112/8f9ae1f9-a904-42b5-b625-278ce41d05b4)

The left one can be moved arround independently. If i drag the right one, it also moves the left one.

macOS Ventura 13.5.1 and PP 0.65.3

**Comment by Morpheus1w3** [comment]
@milaan-muc 
The only chance to get rid of this behaviour is to reset the GUI via the help menu. Duly be informed, all made settings so far disappear.

**Comment by milaan-muc** [comment]
> @milaan-muc The only chance to get rid of this behaviour is to reset the GUI via the help menu. Duly be informed, all made settings so far disappear.

That actually helped. Thank you very much.
