### ISSUE TITLE
Prevent faulty transaction without currency to crash Import UI with NPE

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#3549]
If an importer, for whatever reason, cannot extract the currency, then currently the UI crashes.

See discussion in #3548

**Comment by buchen** [comment]
Thinking about it:

I think it is a special situation for the Deutsche Bank importer. The Deutsche Bank importer extracts the currency from the context because it is not available for each transaction line.

In normal cases, the missing transaction would prevent the matching of a section. Hence a transaction without currency would not be created. 

I think the solution is: check in the context transaction if a currency has been found. If not, fail early and do not extract any transaction.

@Nirus2000 What is your thinking?

**Comment by Nirus2000** [comment]
Hello @buchen

hmm... I understand the problem.
In other importers also need to read various variables in such for-loop.

What do you think about the idea that we implement a function in the ExtractorUtils.java, that we have the possibility to set various variables in these loops, if necessary also optional variables, which have to be set mandatory. 

If these variables are not found, this imported file will be marked as "FAILURE" with a corresponding error message?
This would work better globally.

Greetings
Alex

**Comment by buchen** [comment]
Fixed with #3556 

By using the default parsing logic, we also fail if required attributes are not found.
