### ISSUE TITLE
Upload PDF debugs from application to forum

### ISSUE THREAD

**Issue by tfabritius** [portfolio-performance/portfolio#3559]
Currently, end users have to copy & paste the anonymized PDF debugs to a new post in the forum (in the right topic). In addition to this option, PP could offer an easy way to post the PDF debug from the application via API.

Posting with credentials of the end user is not trivial and not all users have a forum account. Therefore, a technical/anonymous forum account could be used. (Drawback: Users cannot be contacted.)

That would make it easier for end users to contribute their PDF debug to development of importers.

Portfolio Report provides two endpoints for this purpose:
1. `GET api.portfolio-report.net/v1/pdfimport/institutes` returns a list of all known bank institutes with `code` and `name`. `name` can be displayed to the user for selection. `code` is the technical identifier only to be used in this API.
2. `POST api.portfolio-report.net/v1/pdfimport/docs` posts a PDF debug into the forum in the respective topic. Expected body:
    ```jsonc
    {
      "instituteCode": "...", // code as retrieved from institutes endpoint, can be left empty if not in list
      "language": "...", // preferred language of end user ("en", "de", ...), will determine forum category - if topics in multiple languages exist
      "debugText": "...", // the actual pdf debug
      "comment": "..." 
    }
    ```
    This endpoint returns `{ "postUrl": "..." }`.

The endpoint allows an additional `comment` that will be added to the post. E.g. explaining why the current importer is wrong.

After submitting the data, user could be provided with a link to the respective post as returned by the API.

@buchen @Nirus2000

**Comment by pfalcon** [comment]
> Currently, end users have to copy & paste the anonymized PDF debugs to a new post in the forum (in the right topic).

Yeah, but what happens next? Developers *have to* look thru those reports, dig something useful out of them, and make code changes from that. If users wouldn't bother to do a bunch of keypresses to paste their stuff at right place, why would developers be interested to invest 100 or 1000 times more effort into resolving their issues?

**Comment by tfabritius** [comment]
Importing transactions from PDF files is an integral part of PP. The nature of this task requires regular submission of new/changed/wrongly interpreted documents. That's currently the only way the importers can be improved and kept up-to-date. Thus, it should be as easy and user-friendly as possible to submit documents. This can both increase the number of documents received as well as the quality.

What do you suggest?

Should we make sure, submitting a document is as much effort as changing the importer's source code? 😉

**Comment by pfalcon** [comment]
> What do you suggest?

Only that it would be better developers' investment of time to work on improving PP functionality (like, core portfolio management functionality), then on developing complete new subsystem to submit/store user PDF docs.
