### ISSUE TITLE
[meta] Feature Shortlist Project - General Discussions

### ISSUE THREAD

**Issue by OnkelDok** [portfolio-performance/portfolio#3561]
Just an issue where we can discuss general topics of this project.

My first question is how we should remove itmes which are done? By "Archive" or "Delete from project"? In my understanding "Archive" sounds good. But I want to make sure. ;)

**Comment by pfalcon** [comment]
My rough guess is that this may be related to https://github.com/orgs/portfolio-performance/projects/15

**Comment by Nirus2000** [comment]
Hello @OnkelDok 
When you're done with the project/issue, we'll leave it set to "Done" automatically via the workflow when you "merge" At some point later, you can move them to the "Archive". I think the limit is 1500.
I would not delete them.

Regards
Alex
