### ISSUE TITLE
Automatically detect the encoding for files with BOM in the CSV import dialog

### ISSUE THREAD

**Issue by 7Z0t99** [portfolio-performance/portfolio#3570]
**Is your feature request related to a problem? Please describe.**
When I import a csv files with quotes that starts with the UTF-8 BOM 0xEF 0xBB 0xBF, I have to manually select UTF-8 encoding in the import dialog, because the default encoding is windows-1252.

**Describe the solution you'd like**
I would like the import dialog to automatically detect UTF-8 encoding when the file starts with the UTF-8 BOM, and similarly for other encodings when the file starts with a BOM.

**Comment by Morpheus1w3** [comment]
Well, you cannot determine the encoding of a arbitrary byte stream. All other proposals give you ways (and libraries) to do best guessing. But in the end they are still guesses

**Comment by 7Z0t99** [comment]
I agree that technically it is an educated guess, but the byte stream that the importer expects is not totally arbitrary. I think that an educated guess for the most common encoding on the web today (UTF-8) is better than using a default encoding based on the system locale, and would lead to few false positives, if any.

**Comment by Morpheus1w3** [comment]
It is definitiv arbitrary, only the encoding decides how many digits need to combine for each printable char. However, if you habe a Java code snippet how to do it, please feel free. Actually their is no program known who is able to fo this already for text files.

**Comment by buchen** [comment]
What we can do: remember the last encoding used. Then users have to change it once, but in the future it feels right.

What do you think?
