### ISSUE TITLE
Englisch-Version

### ISSUE THREAD

**Issue by githubman100** [portfolio-performance/portfolio#358]
Gibt es eine Englisch-Version für Ihr Produkt. Dies ist ein nettes Tool Ich mag es!

Thks!

**Comment by buchen** [comment]
If you download it, start it, go to "Hilfe" -> "Einstellungen" (help -> settings), you can change the language setting to English.

As I am not a native speaker, I have been hesitant to make this more prominent.
If you have feedback on the wording, menu items, dialog titles, context menus, whatever - feel free to share them.

**Comment by CMCDragonkai** [comment]
Just noticed a couple things:

`Indizes` in the "Add Instruments" dialog should be `Indices`.

I can keep posting any corrections I find here, or would you prefer somewhere else?

**Comment by buchen** [comment]
Hi @CMCDragonkai - I am thankful for every typo. Keep them posted to this issue if you want.

> Indizes in the "Add Instruments" dialog should be Indices.

I have trouble finding exactly which label you mean. Is it the "search dialog"? If you have a screenshot it would be very helpful (you can drag & drop files into the edit area here).
