### ISSUE TITLE
Unable to import CSV file with semicolon as delimiter

### ISSUE THREAD

**Issue by kmietas** [portfolio-performance/portfolio#3580]
**Describe the bug**
The software doesn't recognize semicolon as a delimiter properly and doesn't split the data into colums. As Alphavantage doesn't support function=TIME_SERIES_DAILY_ADJUSTED as a free feature any more I created the below query and downloaded the CSV.
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=8PSG.FRK&datatype=csv&outputsize=full&apikey=demo
I then replaced "," with ";" and after that "." with "," for Portfolio Performance to be able to read the data. But after importing the CSV and selecting semicolon as delimiter the following happens:

![image](https://github.com/portfolio-performance/portfolio/assets/42713332/d5e1ca94-70ec-4870-a971-c6b914380132)

**To Reproduce**
1. Download the attached CSV
2. Import -> Import CSV
3. Select semicolon as delimiter

**Expected behavior**
The data is being split into columns

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Version: 0.65.3

[daily_8PSG.FRK.csv](https://github.com/portfolio-performance/portfolio/files/12817154/daily_8PSG.FRK.csv)

**Comment by kmietas** [comment]
Thank you, I oversaw that. Which means, it is a feature :). Case closed.

But by the occasion, as mentioned above, Alphavantage doesn't support function=TIME_SERIES_DAILY_ADJUSTED as a free feature any more. Should I create a bug for that? Probably it's just enough to switch to TIME_SERIES_DAILY instead.

**Comment by OnkelDok** [comment]
> But by the occasion, as mentioned above, Alphavantage doesn't support function=TIME_SERIES_DAILY_ADJUSTED as a free feature any more. Should I create a bug for that? Probably it's just enough to switch to TIME_SERIES_DAILY instead.

@kmietas, some months ago there was also a report about ``TIME_SERIES_DAILY`` and ``TIME_SERIES_DAILY_ADJUSTED``: #3275
At that time ``TIME_SERIES_DAILY`` was premium and ``TIME_SERIES_DAILY_ADJUSTED`` not. And @buchen changed it: https://github.com/portfolio-performance/portfolio/commit/e9e6e0097a7c09d12e4b1d0dbe51600ec3bbcd13
But yes, create an issue and we can discuss there how to deal with the situation that Alphavatage is changing the premium functions from time to time.
