### ISSUE TITLE
issues with rpmbuild/striping libaries

### ISSUE THREAD

**Issue by uvolmer** [portfolio-performance/portfolio#3586]
**Describe the bug**
I regulary take your linux tar ball and create an rpm from that.
rpmbuild will try to strip binaries/libraries per default.
This is broken with the new release 0.65.4.

I got

/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/sunos-sparc/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/sunos-sparcv9/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-ppc/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-riscv64/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-ppc64le/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-armel/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-s390x/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-aarch64/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-loongarch64/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-mips64el/libjnidispatch.so'
/usr/bin/strip: Unable to recognise the format of the input file `/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/linux-arm/libjnidispatch.so'

system gave me information of this files like

le /home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/sunos-sparc/libjnidispatch.so
/home/ulf/rpmbuild/BUILDROOT/PortfolioPerformance-0.65.4-1.x86_64/opt/portfolio/plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/sunos-sparc/libjnidispatch.so: ELF 32-bit MSB shared object, SPARC32PLUS, V8+ Required, total store ordering, version 1 (Solaris), dynamically linked, not stripped

The rpmbukld will be successful if I disable the striping.
But the resulting installation will crash. (logfile attached)

**To Reproduce**

1. run rpmbuild with the attached PortfolioPerformance-nostrip.spec
rpmbuild -v -ba --define "_sourcedir $(pwd)" --define "_srcrpmdir $(pwd)" --define "_rpmdir $(pwd)" --define "_builddir /tmp/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PortfolioPerformance-nostrip.spec
3. rpm -Uhv x86_64/PortfolioPerformance-0.65.4-1.x86_64.rpm
4. /opt/portfolio/PortfolioPerformance

 - OS: Linux, Fedora 38 x86_64
 - Version 0.65.4
[1696670723512.log](https://github.com/portfolio-performance/portfolio/files/12837316/1696670723512.log)
[spec-files.zip](https://github.com/portfolio-performance/portfolio/files/12837321/spec-files.zip)

**Comment by uvolmer** [comment]
The resulting installation will NOT longer crash, if the executing user has write rights to the path:

sudo chown -R ulf: /opt/portfolio

Solves the issue for the moment.
Is this expected behavior?

**Comment by Morpheus1w3** [comment]
@uvolmer
Tough, you're asking if the behaviour is expected for a private compilation wich is out of scope. In fact, using of `rpmbuild` is upon your own risk.

**Comment by uvolmer** [comment]
Thanks for information.
Just to make it clear: To have a shared installation for multiple users where the installation path is owned by root is also a not supported configuration?

**Comment by uvolmer** [comment]
No idea? Should I open a new report to address this issue?

**Comment by l-ray** [comment]
Having the same issue building the Portfolio-Performance Copr for RPM-based Linux-Distriutions.

**Comment by l-ray** [comment]
@uvolmer - when I build v. 065.4 using the attached spec (no-strip), it also finished successful but trying to install leads to the following error:
```
Problem: cannot install the best update candidate for package portfolio-performance-0.65.3-1.fc39.x86_64
  - nothing provides libc.so.1 needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1()(64bit) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SISCD_2.3) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SUNW_0.7) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SUNW_0.7)(64bit) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SUNW_0.9) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SUNW_0.9)(64bit) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SUNW_1.1) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SUNW_1.1)(64bit) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SUNW_1.22) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SUNW_1.22)(64bit) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.1(SYSVABI_1.3) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.7 needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.7()(64bit) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.7(FBSD_1.0) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.7(FBSD_1.0)(64bit) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.7(FBSD_1.3) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
  - nothing provides libc.so.7(FBSD_1.3)(64bit) needed by portfolio-performance-0.65.4-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:lray:PortfolioPerformance
```
IMO the issue of those bindings is `com.sun.jna_5.13.0.v20230812` as in your example above.

[PortfolioPerformance-spec.zip](https://github.com/portfolio-performance/portfolio/files/12861621/PortfolioPerformance-spec.zip)

**Comment by uvolmer** [comment]
Hello Lennart,

thanks for sharing. As I see, you are building from source.
I didn't do so. I just extract the binary linux-x64 tar ball and use 'Autoreqprov: no'.
Just cheating... ;-)

But I guess, the main issue we have it, that - after installation - the first start of portolio performance will try to store some files in the installation path and this is failing if the diretroy is woned by root.

**Comment by l-ray** [comment]
@uvolmer - does the issue still arise when you remove `~/.PortfolioPerformance` for the executing user?

**Comment by uvolmer** [comment]
Yes, that solves my issue. Thanks for the pointer.

**Comment by uvolmer** [comment]
I think, to solve your issue with Autoreqprov: the easiest fix will be to remove the folders with wrong architekture from plugins/com.sun.jna_5.13.0.v20230812-1000/com/sun/jna/ in your %build or %install section.

**Comment by l-ray** [comment]
Yepp, that's what I did. it starts up and :crossed_fingers: it won't choke somewhere during usage. Thank you @uvolmer
