### ISSUE TITLE
application name is 'NewApplication' instead of 'Portfolio Performance' in macOS status bar 

### ISSUE THREAD

**Issue by mknudsen** [portfolio-performance/portfolio#3595]
**Describe the bug**

Since the latest update Portfolio Performance no longer says "Portfolio Performance" on the status bar at the top left on mac OS but rather _NewApplication_.

**To Reproduce**
1. start PP
2. have it in foreground
3. look at top left / status bar, it reads _New Application_

**Expected behavior**
The name was _Portfolio Performance_

**Screenshots**

![Screenshot 2023-10-14 at 11 39 10](https://github.com/portfolio-performance/portfolio/assets/564654/11d7db12-6c78-41c2-b9ba-51b3b5b9d27a)

**Desktop**

OS 

OS: macOS 14.0 23A344 arm64 
Host: MacBookAir10,1 
Kernel: 23.0.0 
CPU: Apple M1 
GPU: Apple M1 
Memory: 9362MiB / 16384MiB 

Portfolio Performance

Version: 0.65.4 (Oct 2023)
Platform: macosx, aarch64
Java: 17.0.5+8-LTS, Azul Systems, Inc.

**Comment by Morpheus1w3** [comment]
@mknudsen 
It's seems to be that this happened if the system language is English, but @buchen has already notes this behaviour:
https://forum.portfolio-performance.info/t/macos-sonoma-not-displaying-name-of-application/25198/6

**Comment by Nirus2000** [comment]
Issue https://github.com/eclipse-platform/eclipse.platform.swt/issues/779
