### ISSUE TITLE
PDF-Import of OLB Wertpapierabrechnung + Ertägnisse

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio#3607]
Hi there,
Beyond the "Wertpapierabrechnung", they offer a document called "Eträgnisse"/xx You can find the dividends paid there. Would be great if that would be covered by Portfolio Performance as well.

```
PDFBox Version: 1.8.17
Portfolio Performance Version: 0.65.4
-----------------------------------------
Oldenburg, 16.05.2023
Es betreut Sie:
Ihr OLB Team
Postfach 26 05, 26016 Oldenburg 26121 Oldenburg
Tel.: 0441 999092-810
bco.regional-2@olb.de
Vom 16.05.2023
Seite 1 von 1
user name Depotnummer 4759079941
street 10
zip city
ERTRAGSAUSSCHÜTTUNG
Ausschüttung – iS.EO G.B.C.1.5-10.5y.U.ETF DE Inhaber-Anteile
ISIN (WKN) Stück/ Nominale Ausschüttung pro Stück Währung
DE000A0H0785 (A0H078) 71,851808 8,895903 EUR
Zahlbarkeitstag 15.05.2023
Bestandsstichtag 15.05.2023
Ex-Tag 15.05.2023
Geschäftsjahr 01.01.2023-31.12.2023
Dividendengutschrift 7,44 EUR
Ausmachender Betrag + 7,44 EUR
Verwahrart
GS Clearstream Frankfurt
Der ausmachende Betrag wird Ihnen auf Ihr Konto DE12345678901234 gutgeschrieben.
Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben
FNZ
Oldenburgische Landesbank AG | Stau 15/17 | 26122 Oldenburg
Vorsitzender des Aufsichtsrates: Axel Bartsch | Vorstand: Stefan Barth, Vorsitzender | Marc Ampaw | Aytac Aydin | Chris Eggert | Giacomo Petrobelli | Dr. Rainer Polster
Sitz der Gesellschaft: Oldenburg (Oldb) Registergericht: Oldenburg (Oldb) HR-Nummer: HRB 3003
Informationen zur Nutzung Ihrer Daten erhalten Sie auf www.olb.de/dsgvo und in jeder OLB-Filiale. Auf Wunsch schicken wir die Informationen auch gerne per Post zu.

```

_Originally posted by @somehowdifferent in https://github.com/portfolio-performance/portfolio/issues/3562#issuecomment-1777990681_

**Comment by Nirus2000** [comment]
Hello @somehowdifferent
if everything is in order, it should be included in the next release. The more PDF debug there is, the faster and better the PDF importer works.
Please always create a new ISSUE for new PDF debugs. This simplifies our work or post them in the forum under:
[Collection-Threat - PDF-Import von Oldenburgische Landesbank AG](https://forum.portfolio-performance.info/t/pdf-import-von-oldenburgische-landesbank-ag/25204)

Regards
Alex

**Comment by somehowdifferent** [comment]
Hi @Nirus2000 ,

thanks for your work and the informations.

In future i will open a New issue dor each pfd importer update request for OLB.

However, beyond "Eträgnisse" have you spotted and worked in the second request from yesterday?
