### ISSUE TITLE
Handling of transparent background of logo images (Windows)

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#3619]
Bug: image files with transparency are not handled correctly.

See discussion in forum: https://forum.portfolio-performance.info/t/dark-mode-fur-pp/3739/75
See discussion in pull request #3615 

My understanding is that the issue relates to Windows only. On other platforms it is okay (with the limitation outlined below). **Can someone confirm?**

Back then, I had to do special code for macOS and Linux to make the transparency work. You still see the "hack" in the ImageUtil class. Can someone enable this code for Windows and test how the transparency behaves there now. Maybe now all platforms behave the same way? @Nirus2000 @Morpheus1w3 

This is the relevant code fragment:
https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/util/ImageUtil.java#L183-L221

---

### macOS

Using the original file, I tested on macOS Sonoma.

The original logo file:
![](https://user-images.githubusercontent.com/45203494/278860615-5bc89688-046a-43a1-92d2-e290f36e915e.png)

Notice the transparency of the image is only around the circle - the center should always be white.
<img width="366" alt="Bildschirmfoto 2023-10-30 um 11 27 21" src="https://github.com/portfolio-performance/portfolio/assets/587976/dd9f287d-0add-4d85-9bc4-cc33755d3b51">

In **light mode** it looks okay:

<img width="184" alt="Bildschirmfoto 2023-10-30 um 11 29 52" src="https://github.com/portfolio-performance/portfolio/assets/587976/c14a78f0-c67b-4b11-962f-643a950cce4b">

But notice that on the gray lines, the center is also gray:

<img width="202" alt="Bildschirmfoto 2023-10-30 um 11 29 43" src="https://github.com/portfolio-performance/portfolio/assets/587976/6ccff7ef-ae50-4e2a-aa64-5ddb7798cfa0">

Which makes it super ugly in **dark mode**:

<img width="303" alt="Bildschirmfoto 2023-10-30 um 11 29 07" src="https://github.com/portfolio-performance/portfolio/assets/587976/f2daed4f-270a-4421-ab98-9061a776957a">

**Comment by Nirus2000** [comment]
> Back then, I had to do special code for macOS and Linux to make the transparency work. You still see the "hack" in the ImageUtil class. Can someone enable this code for Windows and test how the transparency behaves there now. Maybe now all platforms behave the same way?

I have tried this with Windows. Same result.

**Comment by buchen** [comment]
More observations:

The problem is the scaling of the images. If the image is not scaled, it the transparency looks fine:
<img width="410" alt="no scaling" src="https://github.com/portfolio-performance/portfolio/assets/587976/9cdc512c-8bf1-4f31-a40a-418e4603f226">

If we leave the scaling to the tree/table, then transparency is handled correctly as well:
<img width="314" alt="no scaling - in tree" src="https://github.com/portfolio-performance/portfolio/assets/587976/22f8c5b7-1756-480f-ae11-cbfebe174c00">

However, storing images in the original resolution in the XML file is no option IMHO.

**Comment by Nirus2000** [comment]
Zur Erinnerung
`
a

import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;

public class PNGScaler {
    public static void main(String[] args) {
        try {
            // Lade das ursprüngliche PNG-Bild
            BufferedImage originalImage = ImageIO.read(new File("original.png"));

            // Erstelle ein neues Bild mit der Zielgröße 16x16 und dem gleichen Transparenztyp
            BufferedImage scaledImage = new BufferedImage(16, 16, originalImage.getType());

            // Zeichne das ursprüngliche Bild auf das skalierte Bild, um die Transparenz beizubehalten
            scaledImage.getGraphics().drawImage(originalImage, 0, 0, 16, 16, null);

            // Speichere das skalierte Bild in einer neuen Datei
            ImageIO.write(scaledImage, "PNG", new File("scaled.png"));

            System.out.println("Bild erfolgreich skaliert und gespeichert.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
`
