### ISSUE TITLE
No tooltips on exernal monitor

### ISSUE THREAD

**Issue by curbaczek** [portfolio-performance/portfolio#3622]
Most of the diagrams show a tooltip with detailed information if I click the left mouse button on any item. This works fine on my laptop screen but if I move the PP window to an external monitor these tooltips does not show up anymore. Moving the window back to my laptop screen and they work again.

 - OS: macOS (Ventura 13.5.1) 
 - PP Version 0.65.4

**Comment by OnkelDok** [comment]
Hello @curbaczek, thank you for your report.
In german section of PP Forum was also an issue reported with the tooltip: https://forum.portfolio-performance.info/t/windows-11-mehr-als-2-bildschirme-vertikale-anordnungen/25132
There is the issue described where the tooltip is shown at the other (primary) monitor when PP is running on the secondary monitor when they are arranged vertically (primary below the secondary).

In which arrangement are you displays/monitors configured (vertical, horzontal, some other)?

**Comment by buchen** [comment]
My gut feeling: We create the tooltip with ```tip = new Shell(Display.getDefault().getActiveShell(), SWT.ON_TOP | SWT.TOOL);``` but somehow that display is not the right one. Maybe we have to use query the chart for the right display.

@OnkelDok do you have a setup to reproduce this?

**Comment by OnkelDok** [comment]
> @OnkelDok do you have a setup to reproduce this?

I can test it with two monitors on a Windows system.
Here my investigations:

### Horizontal arrangement

* Primary left, secondary right: 🟩 no issues (no matter on which monitor PP is running)
* Secondary left, primary right: 🟩 no issues (no matter on which monitor PP is running)

### Vertical arrangement

* Primary top, Secondary bottom: 🟩 no issues (no matter on which monitor PP is running)
* Secondary top, Primary bottom:
    * when PP runs on primary: 🟩 no issues
    * when PP runs on secondary: 🟥 tooltip is shown on other (primary) display

### Diagonal arrangement

I've tested only this: 
![grafik](https://github.com/portfolio-performance/portfolio/assets/90478568/edd1a5e2-0a85-4425-8563-4905e1752c86)

When PP is running on second monintor no tooltip is shown (🟥).

In case I find more time I will take a look into code.

**Comment by buchen** [comment]
Crazy that it works in horizontal arrangement but not on vertical 😒

@OnkelDok As you have a setup, can you test this quick and dirty code in the name.abuchen.portfolio.ui.util.chart.AbstractChartToolTip#showToolTip

```
        Display display;
        if (chartV10 != null)
            display = chartV10.getDisplay();
        else
            display = chartV13.getDisplay();

        tip = new Shell(display.getActiveShell(), SWT.ON_TOP | SWT.TOOL);
```

**Comment by OnkelDok** [comment]
> can you test this quick and dirty code

@buchen: I've tested it but the issue is still the same, also without calling ``getActiveShell()``.
Old and new code to get the display are both returning the same instance:
![grafik](https://github.com/portfolio-performance/portfolio/assets/90478568/2edae3ac-6689-45a7-912e-827a7b7c0f25)

Maybe the resaon for the issue is located in the ``calculateBounds`` method. My plan (after the report in the forum some weeks ago) was to analyze this deeper with some debugging output, but I havn't found time to do it yet.
I also wonder if this issue depends only on windows systems. Which is why I am looking forward to the answer from @curbaczek regarding the used arrangement.

**Comment by curbaczek** [comment]
@OnkelDok Sorry, notification got filtered. Thanks for your detailed review.

I have checked it and you are right: in a horizontal arrangement the popups are shown on both monitors. The popup is also shown, if I change the primary monitor to the external monitor (even in a vertical arrangement).

**Comment by buchen** [comment]
Thanks @OnkelDok - what a thing 🙃 I was under the impression that a negative value means the tooltip is shown off screen (because it is placed above the cursor, I wanted to move it down).
