### ISSUE TITLE
Wish to Santa Clause: Let me not just edit the line, but "copy it to a new item"

### ISSUE THREAD

**Issue by MichaelMeier99** [portfolio-performance/portfolio#3625]
Please look at the screenshot, where it would be useful to copy an existing dividend into a new booking line and THEN edit it.

In other words where is now one item

    edit the booking (= Buchung editieren)

it would be great to have 2 items

    edit the booking
    copy the booking in to a new one and edit it (= Buchung kopieren und editieren)

![copyAccountLine](https://github.com/portfolio-performance/portfolio/assets/49785471/f74c101d-182c-43be-86a6-a71d58ce8a8e)

**Comment by dylan09** [comment]
Nice idea. Something I would like also. Copy & Edit dividends, interest, taxes, ...
Maybe also for buy and sale transactions.

**Comment by buchen** [comment]
<img width="247" alt="Bildschirmfoto 2023-12-12 um 11 07 47" src="https://github.com/portfolio-performance/portfolio/assets/587976/e54b9960-7a31-4cb0-a2ab-e52e17e65162">

It is opening the edit dialog with the values of the current transaction preset.

**Comment by buchen** [comment]
I guess it was in time for Santa Clause (if I get to publish a new version by then... 😉)

**Comment by MichaelMeier99** [comment]
Thank you so very much!

And it is time to express:
We were grateful through the whole year and the years before, to have this software!
