### ISSUE TITLE
I18N support

### ISSUE THREAD

**Issue by johnfelipe** [portfolio-performance/portfolio#3640]
I want to contribute for translate into Spanish and italiano, pls tell me format for collaborate, .Po file or XML or JSON, only need strings for translate.

**Comment by Nirus2000** [comment]
Hello @johnfelipe 

1. [POEditor.com](https://poeditor.com/join/project?hash=4lYKLpEWOY)
2. Join translations
3. Login with your account
4. Start your translation in your language
5. Have fun....

Regards
Alex

**Comment by johnfelipe** [comment]
Can u share .Po files with path is more comfortable have file and translated it

**Comment by Morpheus1w3** [comment]
@johnfelipe 
https://poeditor.com/kb/import-options
https://poeditor.com/kb/export-options

**Comment by Nirus2000** [comment]
Hello @johnfelipe 
you need to join the team... then you can export and import...
![grafik](https://github.com/portfolio-performance/portfolio/assets/45203494/43a3ec64-339c-4ab0-9d16-3dfe1fb0a8d9)
