### ISSUE TITLE
import a complete portfolio for best tryout

### ISSUE THREAD

**Issue by johnfelipe** [portfolio-performance/portfolio#3645]
Is possible put a feature or file for import, and give a tryout and review all features of this app?

**Comment by Morpheus1w3** [comment]
@johnfelipe 
Tough, your question is unclear. If you just try out a demo portfolio for evaluation purposes, at the beginning/opening the program you are able to open two examples.

![landing_page](https://github.com/portfolio-performance/portfolio/assets/103072607/78418757-11ee-4753-ac1d-80d2d5095335)
