### ISSUE TITLE
Doesn't seem to be a way to see absolute/total return for a sold position

### ISSUE THREAD

**Issue by pfalcon** [portfolio-performance/portfolio#3657]
Absolute/total return (see #3585 regarding terminology) is an important metric of investment performance. Currently, it's seems that only the "Statement of Assets" view allows to add corresponding column to see it. But at the same time, that view shows only active holdings. The implication is that if security was bought and then fully sold, there doesn't seem to be a way to see what its total return during holding was.

An obvious solution would be to add a filter to Statement of Assets to also show sold out positions (i.e. where current share count is 0, but number of transactions != 0.

**Comment by chirlu** [comment]
Please refer to the Securities report for a complete evaluation of a security, with respect to the reporting period; or to the Trades report if interested in individual (closed) trades. The statement of assets, on the other hand, is a statement of assets, not a statement of no-longer-assets.
