### ISSUE TITLE
Signing GPG key expired

### ISSUE THREAD

**Issue by romichg** [portfolio-performance/portfolio#3663]
**Describe the bug**
The key used to sign the tarball distribution expired. 
 

**To Reproduce**
1. Download `https://github.com/portfolio-performance/portfolio/releases/download/0.65.6/PortfolioPerformance-0.65.6-linux.gtk.x86_64.tar.gz`
2. Download `https://github.com/portfolio-performance/portfolio/releases/download/0.65.6/PortfolioPerformance-0.65.6-linux.gtk.x86_64.tar.gz.asc`
3. Run ` gpg --verify ./PortfolioPerformance-0.65.6-linux.gtk.x86_64.tar.gz.asc`
4. See that the signing key has expired.
```
gpg: Signature made Sat 11 Nov 2023 07:50:18 AM EST
gpg:                using RSA key E46E6F8FF02E4C83569084589239277F560C95AC
gpg: Good signature from "Buchen Andreas <andreas.buchen@gmail.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: E46E 6F8F F02E 4C83 5690  8458 9239 277F 560C 95AC
```

5. Try to find an updated key with no success:
```
gpg  --locate-keys andreas.buchen@gmail.com
pub   rsa4096 2018-08-14 [SC] [expired: 2022-08-15]
      E46E6F8FF02E4C83569084589239277F560C95AC
uid           [ expired] Buchen Andreas <andreas.buchen@gmail.com>
```

**Expected behavior**
Successful verification

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Debian 12.2

**Comment by buchen** [comment]
I have now uploaded the key to keyserver.ubuntu.com and keys.opengpg.org and can see them there.
