### ISSUE TITLE
consors personal investment plan pdf import fails, no fee, no tax

### ISSUE THREAD

**Issue by o1o99** [portfolio-performance/portfolio#3665]
**Describe the bug**
Consors personal investement plan pdf import fails.
No fee, no tax, etc
See Kauf25.txt

So far I see it fails here:
CheckCurrenciesAction.java:
                return new Status(Status.Code.ERROR, MessageFormat.format(Messages.MsgCheckGrossValueUnitMissing,
                                transaction.getCurrencyCode(), securityCurrency));

BR

PS: Maybe "Sparplanname: SPNAME NN" import as note.

**To Reproduce**
Try to import pdf document.

**Expected behavior**
Pass

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.65.6

[Kauf25.txt](https://github.com/portfolio-performance/portfolio/files/13466704/Kauf25.txt)

![Kauf25](https://github.com/portfolio-performance/portfolio/assets/109805143/9efda3a7-84a4-42f1-941d-2a991f8ec28b)

**Comment by Morpheus1w3** [comment]
@o1o99 
Tough, your security currency is USD and trade currency is Euro. Furthermore, trading is via Tradegate exchange even in Euro. Their is no need to keep security currency USD as historical quotes are available in Euro as well.

**Comment by Nirus2000** [comment]
Hello @o1o99 
what @Morpheus1w3 says is correct.
Furthermore, there is no exchange rate in the PDF debug, so it cannot determine the foreign currency. The solution is therefore to create the security in the correct currency and also to obtain the prices in this currency.
