### ISSUE TITLE
No taskbar icon on Windows since 0.66.1

### ISSUE THREAD

**Issue by Ricent82** [portfolio-performance/portfolio#3670]
**Describe the bug**

Since updating from 0.65.5 to 0.66.1 on Windows, there is no loner any icon on PortfolioPerformance's entry on the taskbar. Here's a screenshot:

![2023-12-13 06 52 39](https://github.com/portfolio-performance/portfolio/assets/73326913/cfd82976-df1e-44ee-a156-5b359bbb3bb3)

OS: Windows 10 1809

**Comment by buchen** [comment]
I am not aware of any changes that should change the logo.

Did you use the installer for the Windows version?

**Comment by metal450** [comment]
Yep, used the installer.

But weird, nevermind - all of a sudden it seems to be mysteriously working now? So I guess it was a fluke. Feel free to close this issue (it doesn't give me the option to) :)

**Comment by Ricent82** [comment]
Yep, used the installer.

But weird, nevermind - all of a sudden it seems to be mysteriously working now? So I guess it was a fluke. Closing :)
