### ISSUE TITLE
Display Error message in "All securities" view if quote request URL is invalid

### ISSUE THREAD

**Issue by DamianMalik** [portfolio-performance/portfolio#3698]
It happens from time to time that the quote request URL changes. But this can only be noticed in edit mode. 

**Describe the solution you'd like**
If "Table on a website" is set as the price provider and the quote request URL returns an error, this error should be displayed in the "All securities" view. In the "All securities" view, under the menu item "Show / hide columns" and "Data quality", there should be a menu item "URL Valid". If the quote request is OK, then "URL OK" should be displayed in this column. In case of an error ("No prices"), then "URL invalid" should be displayed in this column, if possible with a yellow or red background. 

I would be happy if this feature request could be realised.

**Comment by Morpheus1w3** [comment]
@DamianMalik 
Their exist already a smarter way rather adding new but in most cases a meaningless value. Check the error log of PP regularly.

**Comment by chirlu** [comment]
Furthermore, there exists a column “Date of latest historical price”, and that field will be coloured yellow/orange when the latest price is more than a week old.

**Comment by DamianMalik** [comment]
> Furthermore, there exists a column “Date of latest historical price”, and that field will be coloured yellow/orange when the latest price is more than a week old.

Thank you
