### ISSUE TITLE
No icon in task bar (Linux / Ubuntu 20.04)

### ISSUE THREAD

**Issue by BlankerHans** [portfolio-performance/portfolio#3703]
**Describe the bug**
No icon when the application is running. Also it does not lay on top of the as favorite pinned icon application of PP.

**To Reproduce**
1. Run it on Ubuntu 20.04 (I guess)
2. Pin PP as favorite to task bar
3. Run PP via task bar

**Expected behavior**
Should have icon and should lay on top pinned icon.

**Screenshots**
![image](https://github.com/portfolio-performance/portfolio/assets/90455840/9c0a68a7-4cf3-4bd8-8e7c-6b8c72d96bca)

**Desktop (please complete the following information):**
Version: 0.67.0 (Dez. 2023)
Platform: linux, x86_64
Java: 17.0.9+9-Ubuntu-120.04, Private Build

**Comment by BlankerHans** [comment]
add StartupWMClass=Portfolio Performance to /usr/share/applications/portfolio.desktop

**Comment by chirlu** [comment]
Duplicate of #3671.
