### ISSUE TITLE
Import ignores source information for BuySellEntry type TRANSFER_IN

### ISSUE THREAD

**Issue by jimjaeger** [portfolio-performance/portfolio#3727]
**Describe the bug**
An importer imports an document filename as source information. If an importer provides an BuySellEntry TRANSFER_IN, the model contains the source filename but after import the source information is not shown in the UI.

**To Reproduce**
1. Create an importer that provides BuySellEntry TRANSFER_IN
2. Import a file with the importer
3. Goes to tranaction view 
4. See empty source information

**Expected behavior**
Source information for TRANSFER_IN

First of all it looks like the PortfolioClientFilter.convertTo(..) methods does not copy the source information. But after adding there
```clone.setSource(t.getSource());``` it sometimes (timing) imports the source and sometimes not.

**Comment by chirlu** [comment]
> If an importer provides an BuySellEntry TRANSFER_IN,

then said importer has a massive bug. As the name `BuySellEntry` indicates, it is only for *buy* and *sell* transactions.

**Comment by jimjaeger** [comment]
Ok. The importer uses the API like this: 
```
      final Transaction<BuySellEntry> pdfTransaction = new Transaction<>();
        firstRelevantLine.set(pdfTransaction);
        pdfTransaction.subject(() -> {
            BuySellEntry entry = new BuySellEntry();
            entry.setType(PortfolioTransaction.Type.TRANSFER_IN);
            return entry;
        });
```
If you say that is not correct. How would you code a release of a stock package e.g. an employee get stock units for a company?
  
´´´

**Comment by chirlu** [comment]
I don’t know the situation, but I do know it is not a *transfer*, which is about moving a security from one account to another (and therefore always must come in a pair).

And this is not a PP bug, closing.
