### ISSUE TITLE
Second application window when opening program

### ISSUE THREAD

**Issue by boredbede** [portfolio-performance/portfolio#3737]
**Describe the bug**
Upon opening the program, a second window with no content (just plain black w. title) opens. It carries the title "Performance Portfolio", and the main window with the actual user interface has no title. Other wise the program works fine and the secondary window closes when the program is closed.

**To Reproduce**
Open program

**Expected behavior**
Open only one program window.

**Screenshots**
![image](https://github.com/portfolio-performance/portfolio/assets/91589754/e2ea79a4-6778-4173-92a5-4e0393e97768)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.6.3

**Comment by chirlu** [comment]
Use “GUI zurücksetzen” from the “Hilfe” menu.
