### ISSUE TITLE
Diagram with strange peak (Vermögensafustellung - Historie (Standard))

### ISSUE THREAD

**Issue by icompas** [portfolio-performance/portfolio#3766]
**Describe the bug**
The diagram 'Vermögensafustellung - Historie (Standard)' sshows a peak in value, where I can't find any reason for.

**Expected behavior**
Should just show what is real.

**Screenshots**
![grafik](https://github.com/portfolio-performance/portfolio/assets/44095390/5124bd10-b9f4-457e-96cd-d236ca96b367)

**Desktop (please complete the following information):**
 - OS: macOS 14.3 (23D56)
 - Version 0.67.1 (Jan. 2024)

**Comment by Morpheus1w3** [comment]
@icompas 
 You have your stage already at https://forum.portfolio-performance.info/t/spikes-in-historical-graph/26826

As we already said, some of your mainted historical quotes are faulty.  If those ok, check if you've maintained a weak exchange rate at your side. https://help-portfolio--performance-info.translate.goog/de/waehrungen/?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp#wahrungsrechner

**Comment by icompas** [comment]
@Morpheus1w3  Thanks for the hint!

Issue identified and fixed.
