### ISSUE TITLE
French numpad emiting a dot as a decimal symbol.

### ISSUE THREAD

**Issue by DaveInDev** [portfolio-performance/portfolio#3780]
On my french keyboard, when I use the numpad to type a decimal symbol, I get a dot "." and the software is unhappy because it seems that in the french settings, it's expecting a ",".
But then if I change the language to english, the numpad still emits a dot ".", as you expect in english, and there is no more problems...

**Expected behavior**
When language is set to french,the numpad decimal should be interprated as a ",".

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Version 0.67.3

**Comment by mierin12** [comment]
Hello @DaveInDev , I do not have a solution, however it looks similar to this : https://github.com/portfolio-performance/portfolio/pull/2826
Would the French + Belgian setting be similar to your need ? I am actually now using this setting myself as it is indeed rather practical.

I have quickly checked, in such Belgian setting, a dot is accepted as a decimal separator in _most_ (but not all) locations:

- [x] Deposit/ Removal / Interest / Interest Charge / Fees / Fees Refund / Taxes / Transfer : comma and dot are accepted as decimal separator 

- Buy/Sell : 
- [x] Share / Gross value / Fee /Taxe: comma and dot are accepted as decimal separator
- [ ] Quote : Only comma is accepted as decimal separator

- Dividende : 
- [x] Share / Gross value /Fee / Taxe : comma and dot are accepted as decimal separator
- [ ] dividend payment per share / dividente par part : Only comma is accepted as decimal separator
- Taxonomy:
- [ ]  Weight/Allocation : Only comma is accepted as decimal separator
- Security Historical Quote 
- [ ] direct modification : Only comma is accepted as decimal separator
- [x] Add.. : comma and dot are accepted as decimal separator

![2024-03-01 19_28_01-Portfolio Performance](https://github.com/portfolio-performance/portfolio/assets/160436107/c4783939-2913-4ecd-b138-d31bdd212546)
![2024-03-01 19_30_08-Portfolio Performance](https://github.com/portfolio-performance/portfolio/assets/160436107/cb082376-3f4c-4576-b0b6-6508b05dcefb)
![2024-03-01 19_34_35-Portfolio Performance](https://github.com/portfolio-performance/portfolio/assets/160436107/7b270c28-75d7-4ab8-bf4a-24a4a53c04a0)
![2024-03-01 19_35_51-Portfolio Performance](https://github.com/portfolio-performance/portfolio/assets/160436107/fb72cae7-96b8-4c61-bfa8-b7f65ceb5b51)
![Capture d'écran 2024-03-01 194845](https://github.com/portfolio-performance/portfolio/assets/160436107/04fb7d64-5292-4518-872f-37776839ca5f)

**Comment by DaveInDev** [comment]
I'll try this setting, thanks.

**Comment by DaveInDev** [comment]
hi, alas I still do not find a solution for this problem. In french, or french/belgium, the decimal separator is still a comma, and my french numerical keyboard still emits a dot... 
Maybe, could it be possible to add a setting defining the decimal separator used as input and also display ?
For the moment, I have to use the software with an english setting, that uses the dot as a decimal separator.

**Comment by mierin12** [comment]
Done since [release 0.70.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.70.0) with https://github.com/portfolio-performance/portfolio/pull/4178
