### ISSUE TITLE
Include Import from Zerodha

### ISSUE THREAD

**Issue by xrewati** [portfolio-performance/portfolio#3834]
Please plan to Include Import from Zerodha transactions report.

**Comment by Morpheus1w3** [comment]
@xrewati 
Well, without any example it's impossible to develop an import interface. If your report is a PDF, Portfolio Performance is having a debugging feature close to where you're important the PDF (via the menue).

**Comment by xrewati** [comment]
[tradebook-GB8512-EQ(3) - Copy.csv](https://github.com/portfolio-performance/portfolio/files/14549790/tradebook-GB8512-EQ.3.-.Copy.csv)

This is a tradebook report from broker Zerodha, includes infor on the trading carried out.
Hope it helps.

**Comment by Sn1kk3r5** [comment]
This is a csv. We need to have an PDF, please.

**Comment by xrewati** [comment]
Hi, They dont provide PDF, Either Excel xlsx or CSV.

**Comment by xrewati** [comment]
1.Possible to have option to add .NS to the import of ticker symbol ? Yahoo finance needs "tickersymbol.NS" so that performace portflio can get quotes.

2.Also the imported security has the ISIN instead of Name of security.
https://prnt.sc/Zw--rhjScaf9

3.The csv does not have total value but per share price. Hence, the imported entries have skewed values.

Regards

**Comment by Morpheus1w3** [comment]
Except the required total value (which could be added upfront via Excel) could be already assigned, if these information are in your CSV file.
