### ISSUE TITLE
Why to allow open in binary portfolio? 

### ISSUE THREAD

**Issue by saatsazov** [portfolio-performance/portfolio#3837]
I've been always using the app on my mac and windows and used xml format and store it on a icloud. When I read about the release of the app I was exited, but please allow xml format as well so it's possible to sync. And easy to handle text files as people might use git for it as well. I'm considering as well.

**Comment by saatsazov** [comment]
Thank you for the app and for this exited ios release

**Comment by Sn1kk3r5** [comment]
You can still work the same way as before. Just save as one time as binary and you’ll be good to go. 
large xml files needs more resources, that’s why binary is preferred. 

Cheers

**Comment by saatsazov** [comment]
Ok I got it. thanks for clarification. I did saved it as binary and tried.Looks great so far
