### ISSUE TITLE
CoinGecko free API limited to querying historical data to past 365 day

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio#3896]
@buchen 
https://forum.portfolio-performance.info/t/kryptowahrung-ckb-nervos-network-kurse-werden-nicht-dargestellt-coingecko/27981/6

**Comment by Sn1kk3r5** [comment]
Just FYI

a workoaround is available. During creation of a Crypto Currency, deactivate the auto download. Create a manual historic quote (Less than 365 days in the past), reactivate auto download.

**Comment by buchen** [comment]
I limit it now to max 365 days. I tested locally and then I can load historical prices.
