### ISSUE TITLE
Automatically add Swiss Valor numbers to securities

### ISSUE THREAD

**Issue by typorian** [portfolio-performance/portfolio#3904]
# Add Swiss Valor numbers automatically to securities

At the moment, securities by default only come with ISIN, WKN and Symbol information. It would be nice to also have Valor Numbers attached to them automatically.

## Source for valor numbers

A good potential source for the valor numbers I was able to identify is the ICTax website which provides zipped xml files that contain isin/valor combinations.

https://www.ictax.admin.ch/extern/en.html#/xml

## Alternatives

My current solution is adding an additional property field where I need it and manually add it.

**Comment by Morpheus1w3** [comment]
Basically their is no need to search at a database. If the ISIN start with CH, the valor number is at the 3rd until 11th position coded.

**Comment by typorian** [comment]
@Morpheus1w3 that is true, but having valor Information available is also important for other securities without ch isins

**Comment by Nirus2000** [comment]
The WKN can be used for this purpose. This offers an alternative. 
We also use this for the PDF importer, as well as the SEDOL, CUSIP, VALOR, FIGI and so on... 
There is currently no added value in implementing all these identifiers. 
The ISIN is the international standard and we offer WKN (securities identification number) as an alternative.

**Comment by Nirus2000** [comment]
I create a feature request...
https://github.com/portfolio-performance/portfolio/issues/3908

**Comment by typorian** [comment]
> The WKN can be used for this purpose. This offers an alternative. We also use this for the PDF importer, as well as the SEDOL, CUSIP, VALOR, FIGI and so on... There is currently no added value in implementing all these identifiers. The ISIN is the international standard and we offer WKN (securities identification number) as an alternative.

Thank you for the feedback. For anyone having to file taxes in Switzerland there is added value, but I can appreciate that this is a very small set of users.

**Comment by typorian** [comment]
Hi @Nirus2000 I'm sorry maybe I'm misunderstanding what you're saying. Is there a valor field for securities that gets populated from pdf imports? I have only looked at the securities definitions themselves because I specifically need the valor number to file my taxes and  the tax forms don't take any other input.

**Comment by Nirus2000** [comment]
> Is there a valor field for securities that gets populated from pdf imports?

No, there is no separate field for this.
However, if no WKN is available, the importers write the SEDOL, CUSIP or security number in the WKN field.

However, you can use this for a different purpose or use the Notes column (field). All information can be entered there.
