### ISSUE TITLE
The UI MessageBlock does not work dynamically to the content

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio#3905]
The UI MessageBlock does not work dynamically to the content.

![grafik](https://github.com/portfolio-performance/portfolio/assets/45203494/813236cf-4f27-4de1-9283-f36456458623)

**Comment by buchen** [comment]
I believe this to be a limitation of the framework. The only option is to shorten the message show on top. Or write our own base dialogs.
