### ISSUE TITLE
"Save as" binary ends with loss of prices from the future 

### ISSUE THREAD

**Issue by ProgFriese** [portfolio-performance/portfolio#3935]
**Describe the bug**
If you import a csv with quotes in the future
[quotes_in_future.csv.zip](https://github.com/portfolio-performance/portfolio/files/14967736/quotes_in_future.csv.zip)
into an xml file everything is fine. Save the xml as binary and the future quotes are lost.

**To Reproduce**
If you import the csv with the prices from the future into the file test.xml, save and close the file, the future prices are still there after reopening the file test.xml (as expected).
Now save as binary test.portfolio, then close and reopen. Now the quotes from the future have disappeared into nirvana.

**Expected behavior**
I would have expected the future quotes to remain in binary format as well

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.68.3

Also described by other people: https://forum.portfolio-performance.info/t/kurse-in-der-zukunft-aus-csv-importieren/28090/15

**Comment by buchen** [comment]
it's a bug. Only via CSV, it is possible to insert future prices. I will fix it so that the prices are kept.

**Comment by buchen** [comment]
Fixed.
