### ISSUE TITLE
Raisin Pension Rürup PDF Import

### ISSUE THREAD

**Issue by Sep21-2009** [portfolio-performance/portfolio#3971]
Ich hab das neuste update bei mir kommt leider der Fehler [date, name, amount, tax1, tax2] Nur 0 von 2 Pattern erkannt: ........
Es geht um Raisin Pension Rürup Portfolio

![Screenshot 2024-05-01](https://github.com/portfolio-performance/portfolio/assets/104714997/7119b3b5-f4fd-4f8e-b552-a4ef1eadc506)

**Comment by Morpheus1w3** [comment]
Da hst dich anscheinend das Format des PDF's geändert, daher bitte https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren

**Comment by Nirus2000** [comment]
No PDF-Debug... :-(
