### ISSUE TITLE
Proposal: change meaning of "inactive" instruments to also mean prices are not downloaded

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#4001]
Background:
> In my opinion, this behavior is very unintuitive. As a user, I would expect that inactive securities are really inactive and thus no longer updated. Neither prices nor events from DivvyDiary.

Proposal:
When making an instrument "inactive", then
a) no prices are updated (but the download configuration remains)
b) the instrument does not show up in dialogs (unless editing an historic transaction with this instrument)

In order to support the change, PP will check if users have inactive instruments that have an active download configuration and propose to activate the instruments.

See also discussion in #3951

Thoughs? Feedback?

**Comment by mierin12** [comment]
Hello, which prices are we talking about ? Historical prices or latest price ? 
Historical prices are already not updated for inactive securitiy, aren't they ? https://forum.portfolio-performance.info/t/neues-nennenswertes/23/91

Is this about automatic vs "forced" ? I can still get update of historical prices of inactive securitiy through : Menu Online/ Upades Quotes or right clicking on a Security Quotes/updated quotes online or juste opening the Edit Security wizard and selecting Historical Quotes tab (in this last case thé prices are fetched but if I do not click ok it is not updated for real).
Does this proposition mean that even with Update quotes/updated quotes online nothing happen for inactive Security ?

I do not use Latest quote so I am unsure of the current behavior.

**Comment by Sn1kk3r5** [comment]
Hi @buchen,

I guess the answer to question a) depends on the individual expectation. No matter of the expectation, the behavior must be self explainable and consistent. How does a user understand the different behavior between quote updates during the start of the program and the timely auto quotes vs. manually triggered. So in my opinion, quotes should either be updated or not.

Regarding b) this is a common behavior and basically the main reason for setting something on inactive.


Back to inactive flag and quotes. Maybe we need to introduce a user option, where users can change the behavior for inactive quotes.
Something like.

Get quotes for inactive securities --> YES/NO

Cheers

**Comment by buchen** [comment]
@mierin12 writes:
> Historical prices are already not updated for inactive security, aren't they ?

🫣🙃

You are right. I totally forgot. Instruments marked as "retired" are only updated if either the user triggers "update all prices" or "update prices of this instrument". They are not updated when opening the file nor are they updated on a regular interval nor are they updated if the user picks "update all prices (only active)".

With the same behavior, I will handle the dividend payments from DivvyDiary. FYI @kimmerin 

@Sn1kk3r5  writes:
> How does a user understand the different behavior between quote updates during the start of the program and the timely auto quotes vs. manually triggered.

It is hard for me to argument that it is "self explainable and consistent" if I, myself, do not remember... but. I think the behavior is okay as it is and is explained that way also in the UI.

<img width="511" alt="Bildschirmfoto 2024-05-10 um 08 56 23" src="https://github.com/portfolio-performance/portfolio/assets/587976/56be1576-585b-48c4-a805-fe7bb42f3740">

**Comment by Sn1kk3r5** [comment]
Good Morning @buchen,

that's correct. But keep in mind, this information is only visible when a user opens the EDIT dialog. When a user makes use of the context menu, he only gets the information, “Möchten Sie das Wertpapier wirklich auf inaktiv setzten?”

And now assuming a user likes to perform this action for like 10 securities, I highly doubt he does this via the EDIT dialog but makes use of the context menu.

So probably the same information should be displayed when setting inactive via context menu?!

Cheers

**Comment by kimmerin** [comment]
> So probably the same information should be displayed when setting inactive via context menu?!

Could be added as part of the "are you sure"-message

**Comment by Sn1kk3r5** [comment]
> > So probably the same information should be displayed when setting inactive via context menu?!
> 
> Could be added as part of the "are you sure"-message

Was my intention as well. And while considering this, it would probably make sense to provide an option in the filter settings.

Today you can only filter for active securities but not for inactive once:
![image](https://github.com/portfolio-performance/portfolio/assets/78857191/9c82dfb4-7dbb-4d9a-8277-b1a707162141)

**Comment by mierin12** [comment]
> Was my intention as well. And while considering this, it would probably make sense to provide an option in the filter settings.
> 
> Today you can only filter for active securities but not for inactive once: ![image](https://private-user-images.githubusercontent.com/78857191/329494387-9c82dfb4-7dbb-4d9a-8277-b1a707162141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjYxMzcsIm5iZiI6MTcxNTMyNTgzNywicGF0aCI6Ii83ODg1NzE5MS8zMjk0OTQzODctOWM4MmRmYjQtN2RiYi00ZDlhLTgyNzctYjFhNzA3MTYyMTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA3MjM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMzc5MWU4YTEyNjkzNTFjYTAzYjhhNmU0NTY5MGU5YTMyODc3MDJjYTkxMmVhN2MwNmZjYzgzYTg1NjQ5YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_b0oLPSCCPJHnO0LvDfW1ily5Eq0vpwx9_hc5Xx9oQ)

I got the same thought when I saw this issue : 
https://github.com/portfolio-performance/portfolio/pull/4007
