### ISSUE TITLE
Discreet mode not working in taxonomies section's stacked area charts

### ISSUE THREAD

**Issue by pinzutu** [portfolio-performance/portfolio#4020]
**Describe the bug**
View > Options > Discreet mode does not hide absolute values in the taxonomies section's stacked area charts when leaving the mouse clicked.

**To Reproduce**
1. Top Menu > Activate View > Options > Discreete
2. Navigate to Side Menu > Taxonomies > {Asset Classes/Regions/...} > Stacked Area Chart
3. Hold the click on the chart to see not hidden absolute values

**Expected behavior**
The absolute values should be starred, just as in the Side Menu > Reports > Statement of Assets > Chart section.

**Screenshots**
![Untitled](https://github.com/portfolio-performance/portfolio/assets/170082460/bce6cc1b-aa90-4ee0-9606-aa831f1619b4)

**Desktop (please complete the following information):**
 - OS: W10
 - v0.68.4

**Comment by mierin12** [comment]
Hello pinzutu, thanks for reporting the bug, I believe PR 4031 should fix it !

**Comment by pinzutu** [comment]
@mierin12 many thanks for the fix!
