### ISSUE TITLE
GBp (penny) quotes from Yahoo Finance interpreted as GBP (pound)

### ISSUE THREAD

**Issue by leezu** [portfolio-performance/portfolio#4038]
**Describe the bug**
While PP supports the GBX symbol for accounts denominated in British pence (https://github.com/portfolio-performance/portfolio/issues/406), brokers such as Interactive Brokers usually denominate accounts in British pounds and not pence. Importing GBX (also called GBp) or GBP transactions from the Interactive Brokers XML files to PP is therefore only possible to GBP accounts. Attempting to import to an GBX account does not import any transaction due to GBP not matching GBX. Importing to a GBP account works however correctly, with PP reading the correct GBP denominated purchase price from the XML file.

When PP queries current/historic quotes from Yahoo Finance, it receives a GBp response. See for example https://query1.finance.yahoo.com/v8/finance/chart/LSEG.L which begins with `{"chart":{"result":[{"meta":{"currency":"GBp","symbol":"LSEG.L","exchangeName":"LSE","fullExchangeName":"LSE","instrumentType":"EQUITY",` and contains quotes in pence (as indicated by the currency name "GBp". Unfortunately, PP interprets this GBp quote as GBP, leading to current and historic values being off by 100. 

For historic reasons, it seems that all quotes for London listed stocks are in GBp and there should be no situation in which Yahoo Finance actually returns a GBP quote. This issue is not only Yahoo Finance specific, though at least Yahoo Finance includes the "GBp" currency information in the API response. Other providers, like alphavantage.co do not provide the currency symbol in the response and simply return "GBp" instead of "GBP". https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=LSEG.L&apikey=demo

**To Reproduce**

Add a GBP stock purchase to a GBP denominated PP account. For example, LSEG.L. Provide the purchase price in GBP. Observe that PP obtains the GBp quotes from Yahoo and reports the value of the investment as 100x the true value.

**Expected behavior**
PP distinguishes between GBp and GBP. When Yahoo Finance provides a GBp quote for a GBP security, PP correctly converts from GBp to GBP and reports the accurate value.

**Workaround**
Obtain alphavantage.co API key. Setup manual JSON source for the security:

![image](https://github.com/portfolio-performance/portfolio/assets/946903/0b18231f-58f0-4f5a-bdd0-8ead72eb4d33)

where the URL is https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=SYMBOL.L&apikey=APIKEY and disabling historical data.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.68.4

**Comment by kgoderis** [comment]
@leezu When I apply the above, for WISE.L, I do get a response from the server, but the JSON is not parsed (well, I don't see a result). Here is what I have


Server:

{
  "Global Quote": {
    "01. symbol": "WISE.L",
    "02. open": "694.0000",
    "03. high": "694.0000",
    "04. low": "676.0000",
    "05. price": "685.0000",
    "06. volume": "2734817",
    "07. latest trading day": "2024-06-27",
    "08. previous close": "689.5000",
    "09. change": "-4.5000",
    "10. change percent": "-0.6526%"
  }
}

Config:

![image](https://github.com/portfolio-performance/portfolio/assets/5459062/f2f1381d-bc04-46e0-b547-301688b0fdf0)


What am I missing here?

**Comment by buchen** [comment]
Fixed with #4415
