### ISSUE TITLE
Search with Ctrl+F

### ISSUE THREAD

**Issue by metal450** [portfolio-performance/portfolio#4051]
Currently if you want to search (on any of the pages), you have to manually take the mouse and click in the "Search" box at the top left - the standard "Ctrl+F" (or F3) keyboard shortcuts do not work.  It would be nice if you could just hit Ctrl+F, and it would put the cursor in the "Search" box, so you could search without needing to rely on the mouse.

**Comment by netsho** [comment]
Issue solved in [commit](https://github.com/portfolio-performance/portfolio/commit/e1012c159e6c62d66800300404370b6dd066a78f), which was initiated in this [PR](https://github.com/portfolio-performance/portfolio/pull/4102)

@buchen, It can be closed now.

**Comment by metal450** [comment]
Awesome, thanks! Will close.
