### ISSUE TITLE
IB Flex Importer "witholding tax"

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio#4062]
@Nirus2000, Hello, I am new to the forum, the IB importer helps me a lot, thanks. When matching the dividends to taxes, I found a small issue, as I have many dividends of the same security payment paid in 2 parts, one in "Dividend", and one in form of "Payment In Lieu Of Dividends". The current importer matches the dividend to taxes from the "Payment In Lieu Of Dividends" instead of "Dividends". The taxes for "Payment In Lieu Of Dividends" is a separate items. It does not impact the final cash account numbers but I just want to let you know this is the case. I attach a test xml file for your reference. And thanks again for your IB importer.
[ibkr_test.zip](https://github.com/user-attachments/files/15568984/ibkr_test.zip)

_Originally posted by @mixplus708 in https://github.com/portfolio-performance/portfolio/issues/3177#issuecomment-2148173590_

**Comment by Nirus2000** [comment]
Hello @mixplus708
I don't quite understand the problem yet.
The taxes are due because they are type=“Withholding Tax”.

**Comment by mixplus708** [comment]
In IB, I participated in the stock yield enhancement program where I lend my stocks to someone. When I received dividend, it some times will split into 2 payments. One is dividend to ordinary shares (type is "Dividend), one for the stocks that I lend out, the borrower is responsible to pay me the dividend and this payment is in the form of dividend payment in lieu (Type is "Payment in lieu". In the attached IB xml report, there are 2 such as examples (GDV and AOD). 

For example: AOD, I own 500 shares, there are 329 shares that I would receive ordinary dividend of USD 36.19 and taxes of USD 10.86 and 171 shares of dividend in the form ,(Type) of "payment in lieu", of USD18.81 with taxes of USD 5.64. The current importer matches the dividend from the ordinary with the taxes from the payment in lieu as one transaction and there are a separate dividend cash transaction of USD 18.81 and a separate taxes deduction transaction of USD 10.86. 

The overall cash balance is not affected, but it is something I would like to let you know. I hope I explain it well so you can understand my points. I attached some screenshots and an test file for your reference. Let me know if you have any further questions. Thanks.

[IB importer.zip](https://github.com/user-attachments/files/15754264/IB.importer.zip)

**Comment by Nirus2000** [comment]
I have imported your test file to check this.
I have not found any entries that match your invoice or amounts. Unfortunately we do not have all banks, documents or entries for all banks in the world, so we have to understand what you mean and work with concrete facts and sources. Please create your example on original documents, refrain from unnecessary explanations. (Would have, could have, if, but)
Also, your statement does not apply to AOD, but to GDV.
What should we believe now and what not?
Please understand that we are sacrificing our “own” free time for this and are working on a voluntary basis - so it is not worth spending hours trying to understand incomplete, incorrect and erroneous explanations and instructions.

- What is the result so far... (calculation example + minimal example + screenshot)
- How is it correct... (if necessary with calculation example on the example file)
- Why is this correct.

So, create a minimal example. Take screenshots
Add a concrete calculation example, justify your statements and then we will work on this.

![grafik](https://github.com/portfolio-performance/portfolio/assets/45203494/3d83ea7a-e0f2-4e34-b7ff-000da7f62f9b)

![grafik](https://github.com/portfolio-performance/portfolio/assets/45203494/897e05c5-64b9-4025-9d90-ba09989ada68)

**Comment by mixplus708** [comment]
@Nirus2000, 
I am really sorry about my mistake, I attached the incorrect file and make you all the trouble. I have now checked and please use the screen shoots and test file (ibkr_test) provided and import with "Interactive Brokers: Activity Flex Query in PP.
[IB importer test file.zip](https://github.com/user-attachments/files/15756941/IB.importer.test.file.zip)

**Comment by Nirus2000** [comment]
NO DESCRIPTION WITH BENEFIT... ROUND.
