### ISSUE TITLE
Track absolute value on performance chart

### ISSUE THREAD

**Issue by DaveInDev** [portfolio-performance/portfolio#4079]
I often want to track rapidly the absolute value of my whole portfolio in the past. I cannot find how to do it.

I can do it by account using the accounts / security account / chart feature, but it's one chart per account.

It would be nice to have this same chart for the whole portofolio, with the same useful "tooltip" floating window you got when you click the chart and naviguate around.

And by the way, in the previously mentioned chart, I do not understand why the invested capital is affected (negatively) by the dividends that are served on the deposit account.

**Comment by mierin12** [comment]
Hello, the security account/chart tab was added recently, and of course you can also track your total portfolio:
in **Statement of Assets/Chart** : at this location you can plot whatever you want ! Whole portfolio is "Total". You can also plot individual accounts there.
![2024-06-16 00_49_55-Portfolio Performance](https://github.com/portfolio-performance/portfolio/assets/160436107/b7d90eb4-542f-4b3d-a24e-7bf7740728da)

You can also view the total it under Taxonomy
![2024-06-16 00_52_18](https://github.com/portfolio-performance/portfolio/assets/160436107/a12a5ff8-b1b7-4630-a0ed-d0534ce30f30)

Regarding 
> And by the way, in the previously mentioned chart, I do not understand why the invested capital is affected (negatively) by the dividends that are served on the deposit account.

I am not quite sure myself; I think the subject was mentioned there, https://forum.portfolio-performance.info/t/investiertes-kapital-sinkt-mit-dividendenentnahme-von-konto/4149, but I did not understood everything. With the recent addition of the security account/chart tab, it would be worth asking again in the forum maybe. 
We can compare the behavior with Performance/Payment/Saving. In the example kommer file, when selecting Brokerage Account, we do see the dividend are negatively counted, and the final savings value matches the final value of security account/chart /invested capital. But when selecting Brokerage Account+Deposit Account, the invested capital value is a bit different. We can also see this difference in the widgets. 
![2024-06-16 01_07_13-Portfolio Performance](https://github.com/portfolio-performance/portfolio/assets/160436107/5e10c987-f267-4424-893b-458fd1584e60)

![2024-06-16 01_12_54-](https://github.com/portfolio-performance/portfolio/assets/160436107/a9162bef-90b6-4f35-8d80-fffa71a9fa35)

![2024-06-16 01_09_28-](https://github.com/portfolio-performance/portfolio/assets/160436107/f8cf9e41-7305-4368-be50-72ff099e527b)

![2024-06-16 01_11_03-Portfolio Performance](https://github.com/portfolio-performance/portfolio/assets/160436107/b0defa2a-83a1-49ab-8894-f558d7e67c6f)
we can also see it in the different way performance calculation are done for Brokerage Account only or Brokerage Account +Deposit Account. 
![2024-06-16 01_18_58-Portfolio Performance](https://github.com/portfolio-performance/portfolio/assets/160436107/2fc527a1-152a-4c12-99b4-552d1bb2cc28)
Maybe the invested capital of "Brokerage Account +Deposit Account" could be added to security account/chart datas as an option, if it makes sense.
