### ISSUE TITLE
Einstandskurs wird nicht korrekt berechnet

### ISSUE THREAD

**Issue by mbs2016** [portfolio-performance/portfolio#408]
in der Performance-Berechnung wird m.E. der Einstandskurs eines Wertpapiers nicht korrekt bestimmt, da Ordergebühren nicht in der Berechnung einfließen.

Der Einstandskurs wird in der Regel wie folgt definiert: "Der Kurs eines Wertpapiers, der zu seinem Kauf inklusive aller Nebenkosten aufgewendet wurde".

**Comment by buchen** [comment]
Bisher habe ich den Einstandskurs ohne Nebenkosten berechnet - siehe auch Tooltip der Spalte:

<img width="322" alt="bildschirmfoto 2016-01-17 um 11 39 16" src="https://cloud.githubusercontent.com/assets/587976/12377056/024b5072-bd0f-11e5-8870-f78a070069ce.png">

Im Prinzip kann ich das ändern, bzw. kann ich auch beide Einstandkurse anbieten.

> Der Einstandskurs wird in der Regel wie folgt definiert: "Der Kurs eines Wertpapiers, der zu seinem Kauf inklusive aller Nebenkosten aufgewendet wurde".

Wo hast Du die Definition her? Dann könnte ich direkt darauf verlinken/verweisen.

**Comment by mbs2016** [comment]
Die Definition habe ich hier gefunden:
http://boerse.ard.de/boersenwissen/boersenlexikon/einstandskurs-100.html
Auch meine Depotbank (DAB) wendet diese Definition an.

**Comment by buchen** [comment]
Danke für den Link. Ich überlege mir das mal - und wie ich damit für existierende Verwender umgehe. Ich lasse den Issue deswegen mal offen.

**Comment by buchen** [comment]
Ich habe gerade mal nachgeschaut. Bei meinem Broker wird der Einstandskurs ebenfalls inklusive aller Kosten berechnet. Ein Argument mehr.

**Comment by Beluk** [comment]
Bei der IngDiba wird auch der Einstandskurs inklusiver Kosten berechnet (außer den Stückzinsen). Es wäre auch schön wenn man diesen Kurs im Wertpapierdiagramm als horizontale Linie sehen könnte.

**Comment by mierin12** [comment]
Completed in release [0.73.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.73.0) from https://github.com/portfolio-performance/portfolio/commit/f541d2544fe2d18290cd3a541618e01e090b60ae and https://github.com/portfolio-performance/portfolio/pull/4310
(Was previously available in Trades section but only in FIFO mode).
