### ISSUE TITLE
Trade Republic Dividend PDF import error

### ISSUE THREAD

**Issue by sczech** [portfolio-performance/portfolio#4083]
**Describe the bug**
When trying to import a Dividend PDF from Trade Republic I'm getting the following error message:
`Keine der 3 Bereiche wurde gefunden: [name, currency, isin, nameContinued] Nur 0 von 3 Pattern erkannt: [^(?<name>.*) [\.,\d]+ (Stk\.|titre\(s\)|Pz\.|Pcs\.) [\.,\d]+ (?<currency>[\w]{3}) [\.,\d]+ [\w]{3}$, ^(?<nameContinued>.*)$, ^(ISIN([\s])?:([\s])?)?(?<isin>[A-Z]{2}[A-Z0-9]{9}[0-9])$] (pb363613816399254462731216111.pdf, 1..24);
[name, nameContinued, isin, currency] Nur 0 von 4 Pattern erkannt: [^[\d] Kapitalmaßnahme (?<name>.*) [\.,\d]+ Stk\.$, ^(?<nameContinued>.*)$, ^(?<isin>[A-Z]{2}[A-Z0-9]{9}[0-9])$, ^[\d] Barausgleich [\.,\d]+ (?<currency>[\w]{3})$] (pb363613816399254462731216111.pdf, 1..24);
[name, nameContinued, isin, currency] Nur 0 von 5 Pattern erkannt: [^[\d] Reinvestierung (?<name>.*) [\.,\d]+ Stk\.$, ^(?<nameContinued>.*)$, ^(?<isin>[A-Z]{2}[A-Z0-9]{9}[0-9])$, ^[\d] Reinvestierung .*$, ^[\d] Bruttoertrag [\.,\d]+ (?<currency>[\w]{3})$] (pb363613816399254462731216111.pdf, 1..24) [1..24]`

**To Reproduce**

This is the PDF I am trying to import:
```
PDFBox Version: 1.8.17
Portfolio Performance Version: 0.69.0
-----------------------------------------
TRADE REPUBLIC BANK GMBH  BRUNNENSTRASSE 19-21  10119 BERLIN
Max Mustermann SEITE 1 von 1
Musterstrasse 1A DATUM 17.06.2024
12345 Berlin DEPOT 0123456789
DIVIDENDE
ÜBERSICHT
Dividende mit Ex-Datum22.05.2024.
POSITION ANZAHL ERTRAG BETRAG
MSCI World USD (Dist) 123.45 USD
IE00BK1PV551 123 Stücke 0.36 USD
GESAMT 123.45 USD
ABRECHNUNG
POSITION BETRAG
Zwischensumme 123.45 USD
Zwischensumme 1.0894 EUR/USD 111.11 EUR
Kapitalertragssteuer 1.0894 EUR/USD -11.11 EUR
Solidaritätszuschlag 1.0894 EUR/USD -1.11 EUR
GESAMT 99.99 EUR
BUCHUNG
VERRECHNUNGSKONTO DATUM DER ZAHLUNG BETRAG
DE00000000000000000000 07.06.2024 99.99 EUR
Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.
Wird keine Umsatzsteuer ausgewiesen, handelt es sich um eine umsatzsteuerfreie Leistung gemäß § 4 Nr. 8 UStG
Trade Republic Bank GmbH www.traderepublic.com Sitz der Gesellschaft: Berlin DirektorenBrunnenstraße 19-21 service@traderepublic.com AG Charlottenburg HRB 244347 B Andreas Torner10119 Berlin Umsatzsteuer-ID DE307510626 Gernot Mittendorfer

```

**Desktop (please complete the following information):**
 - OS: macosx, aarch64
 - Version: 0.69.0

**Comment by MUCstar7** [comment]
I have the very same problem. I think TR changed in the pdf something...
