### ISSUE TITLE
APP crashes without any apparent reason

### ISSUE THREAD

**Issue by damagr** [portfolio-performance/portfolio#4131]
**Describe the bug**
APP suddenly crashes, when I try to access to any report, any account.

**To Reproduce**
1. Click on any section of the APP.
2. APP crashes.

**Expected behavior**
Don't crash...

**Log**
Here's the log: [hs_err_pid25.log](https://github.com/user-attachments/files/16078424/hs_err_pid25.log)

**Desktop (please complete the following information):**
 - OS: Linux Mint 
 - Version 21.3 Cinnamon

**Comment by damagr** [comment]
I've tried to create a new portfolio file, while I was creating it, it crashed again, that file was empty.

[hs_err_pid25.log](https://github.com/user-attachments/files/16106059/hs_err_pid25.log)

**Comment by 97gamjak** [comment]
Was there any progress on this issue?

**Comment by damagr** [comment]
Nothing I still have the same problem.

**Comment by 97gamjak** [comment]
Same for me. It would be really helpful to receive some feedback or an update on the status of this issue from the developers. So far, there hasn't been any response from them, which is quite frustrating.

**Comment by JDaw1d** [comment]
Hi all, 
was there any progress on this issue?
Br

**Comment by damagr** [comment]
Well seems that nobody will try to fix this.

**Comment by mierin12** [comment]
I think you will get more visibility by opening a thread on the forum. There are several topics related to Linux which have been solved.
https://forum.portfolio-performance.info/t/pp-freezes-every-three-minutes-on-linux-mint-vanessa/27785
https://forum.portfolio-performance.info/t/pp-sturzt-unter-linux-mint-ab/25837
