### ISSUE TITLE
PP 0.69 | TR PDF-Import Dividende broken

### ISSUE THREAD

**Issue by WolfOnTour** [portfolio-performance/portfolio#4133]
**Describe the bug**
The dividend import via PDF from Trade Republic is broken

**To Reproduce**
1. Go to 'Konto -TR'
2. Right Click on 'Konto -TR'
3. Scroll down to 'PDF Import'
4. Select the PDF
5. Click Open

**Expected behavior**
Keine der 3 Bereiche wurde gefunden: [name, currency, isin, nameContinued] Nur 0 von 3 Pattern erkannt: [^(?<name>.*) [\.,\d]+ (Stk\.|titre\(s\)|Pz\.|Pcs\.) [\.,\d]+ (?<currency>[\w]{3}) [\.,\d]+ [\w]{3}$, ^(?<nameContinued>.*)$, ^(ISIN([\s])?:([\s])?)?(?<isin>[A-Z]{2}[A-Z0-9]{9}[0-9])$] (pb1719415451533782006257776914.pdf, 1..27);
[name, nameContinued, isin, currency] Nur 0 von 4 Pattern erkannt: [^[\d] Kapitalmaßnahme (?<name>.*) [\.,\d]+ Stk\.$, ^(?<nameContinued>.*)$, ^(?<isin>[A-Z]{2}[A-Z0-9]{9}[0-9])$, ^[\d] Barausgleich [\.,\d]+ (?<currency>[\w]{3})$] (pb1719415451533782006257776914.pdf, 1..27);
[name, nameContinued, isin, currency] Nur 0 von 5 Pattern erkannt: [^[\d] Reinvestierung (?<name>.*) [\.,\d]+ Stk\.$, ^(?<nameContinued>.*)$, ^(?<isin>[A-Z]{2}[A-Z0-9]{9}[0-9])$, ^[\d] Reinvestierung .*$, ^[\d] Bruttoertrag [\.,\d]+ (?<currency>[\w]{3})$] (pb1719415451533782006257776914.pdf, 1..27) [1..27]

**Screenshots**
![grafik](https://github.com/portfolio-performance/portfolio/assets/8594585/f8a88af1-9906-4e17-bb2f-5ba6d08a96d8)

![grafik](https://github.com/portfolio-performance/portfolio/assets/8594585/b56bf3d3-d946-4dfb-a323-e310cf48ab93)

**Desktop (please complete the following information):**
 - OS: [Windows 10.0.19045]
 - Version [PP 0.69]

**Comment by Nirus2000** [comment]
Hallo @WolfOnTour 

Bitte das Tutorial-Video genau anschauen und einen “*vollständigen*” PDF-Debug posten.

- **Ansonsten bitte keine anderen Daten verändern oder löschen.**
- **Die persönlichen Daten sind 1 zu 1 zu ersetzen.**
- **Sonstige Änderungen, wie das ersetzen des Datums o.ä. ist ebenso kontraproduktiv.**
- **!! NUR DIE EIGENEN PERSÖNLICHEN DATEN !!**
- **Kein PDF's welche aus einem Browser o. ä. in PDF Konvertiert werden**
- **Keine selber gescannten Papierzettel**

z. B.
- *Name → Max Mustermann und so weiter…*
- *Adresse → Blumenstraße*
- *IBAN und Depotnummern: Die Zahlen 1 zu 1.*

Nicht mehr und nicht weniger... pro PDF-Debug bitte einen post. 
Ende.

**Video-Tutorial:**
[PDF-Dokumente für die Fehlersuche extrahieren](https://forum.portfolio-performance.info/t/buchungen-aus-pdf-dateien-importieren/38#tutorial-extrahieren)


--> https://forum.portfolio-performance.info/t/pdf-import-von-trade-republic/

Vielleicht ist ja bereits das Problem behoben.
