### ISSUE TITLE
Add Spanish language to the Trade Republic PDF import

### ISSUE THREAD

**Issue by blastik** [portfolio-performance/portfolio#4137]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
It seems that currently Spanish is not a supported language to do a PDF import of a Trade Republic statement

**Describe alternatives you've considered**
I tried to change my smartphone system language to german and then do the PDF export but the statement as still in Spanish.

**Additional context**
NA

**Comment by Sn1kk3r5** [comment]
Hi @blastik 

@Nirus2000 will need a pdf debug in order to make this work. So the best way would be a post including your PDF debugs (Purchae, sell, dividends, etc.) here: https://forum.portfolio-performance.info/t/pdf-import-von-trade-republic/5107/585

**Comment by blastik** [comment]
thank you @Sn1kk3r5 . done! https://forum.portfolio-performance.info/t/pdf-import-von-trade-republic/5107/587?u=blastik
