### ISSUE TITLE
Importing from deGiro is broken since very long

### ISSUE THREAD

**Issue by MichaelMeier99** [portfolio-performance/portfolio#4139]
**Describe the bug**
importing the transaction.pdf from deGiro does not work any more
The debug-ASCII-files were sent to Andreas several times.

**To Reproduce**
import any transaction.pdf from deGiro by dragging it into the PP with the mouse, result: screenshot
It stopped working about one year ago.
Before it was perfect. About one year ago.

**Expected behavior**
I shall work as it did before
To my mind the reason is very simple: PP looks for English fields, - but they are German.
Do it looks for "date" where it shall be looked for "Datum".

**Screenshots**
attached

**Desktop (please complete the following information):**
Windows 10
All PP versions since long including the latest version.
The bug found into the source several versions before.
About one year ago this worked fine.
![PP_DeGiroProblem](https://github.com/portfolio-performance/portfolio/assets/49785471/38e20b23-bc6b-4f0b-96e5-978e051fd389)

**Comment by Morpheus1w3** [comment]
@Nirus2000 will need a pdf debug in order to make this work. So the best way would be a post including your PDF debugs (Purchae, sell, dividends, etc.) here: https://forum.portfolio-performance.info/t/pdf-import-von-trade-republic/5107/585
