### ISSUE TITLE
Import low/high values from Yahoo Finance API

### ISSUE THREAD

**Issue by halfdan** [portfolio-performance/portfolio#4142]
**Is your feature request related to a problem? Please describe.**

Yahoo Finance returns daily/low high values for stocks/exchange rates. I'd like to see them in the charts.

**Describe the solution you'd like**

Portfolio Performance already supports low/high for other securities from other providers. The API returns the correct data already but it's not imported:

![Screenshot 2024-07-12 at 12 07 59](https://github.com/user-attachments/assets/52fee99a-cd3f-4b05-a0c3-b5bc25d3b52a)

https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio/src/name/abuchen/portfolio/online/impl/YahooFinanceQuoteFeed.java#L274-L289

**Describe alternatives you've considered**

**Additional context**
 
Happy to work on this myself as a first contribution.

**Comment by Morpheus1w3** [comment]
Well, low/high prices is requested since years but will not supported, because focusing performance calculations relay on end of day figures. Furthermore, their exist plenty of websites who could support charting better than PP

**Comment by halfdan** [comment]
I'm not sure I understand your reply. Why does the table display the columns at all if there's no intention of supporting them at least at a very basic level?

**Comment by Sn1kk3r5** [comment]
Becasue the same view is used when making use of jsone as quote provider.

**Comment by halfdan** [comment]
Got it! Thanks for the thorough explanation.

**Comment by pfalcon** [comment]
@halfdan : Note that there's always some smaller things to in "that direction" (of giving user more/easier to understand price data). For example, those today's high/low numbers - they're currently displays as boring numbers. It would be cool to have it displayed as a de-facto standard widget, where there's a horizontal bar, with low value on the left, high on the right, and current price graphically shown between them.
