### ISSUE TITLE
Vermögensaufstellung: Stückzahl mit mehr Nachkommastellen ausgeben

### ISSUE THREAD

**Issue by mbs2016** [portfolio-performance/portfolio#419]
bitte unter Berichte - Vermögensaufstellung jeweils Stückzahl mit 4 (anstatt 3) Nachkommastellen ausgeben.

**Comment by buchen** [comment]
Intern wird die Stückzahl mit 6 Nachkommastellen gerechnet (das sieht man auch in dem Tooltip wenn man über der Zelle mit dem Mauszeiger steht). Angezeigt werden aber nur 3 Nachkommastellen - ich bin davon ausgegangen, dass man a) meistens ganze Stücke hat und b) die Stücke untereinander an dem Komma ausrichten möchte. Und dann geht doch einiges an "whitespace" in der Spalte einfach so drauf.

Ich kann es mal ausprobieren, vielleicht auch konfigurierbar machen, oder man richtet die Werte nach den längsten Nachkommastellen aus.

**Comment by mbs2016** [comment]
Die reguläre Ordergebühren für ETFs sind bei meinem Broker relativ hoch, die Ordergebühren für einen Sparplan dahingegen deutlich niedriger, wenn es sie überhaupt gibt. Die wenige nicht-sparplanfähige ETFs im Depot erwerbe ich, ganzzählig, über XETRA. Mein Broker speichert die Stückzahl eines WPs mit vier Nachkommastellen. Du hast natürlich recht, dass so natürlich viel "white space" drauf geht.

**Comment by mierin12** [comment]
Done since [release 0.49.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.49.0) with https://github.com/portfolio-performance/portfolio/pull/1766
