### ISSUE TITLE
Unwanted modification of Quote values.

### ISSUE THREAD

**Issue by NMV0** [portfolio-performance/portfolio#4196]
**Describe the bug**
When Buying a Securities or Editing a transaction, and _Shares_ and _Quote_ doesn't produce a round number, the value of the _Quote_ is modified compare to the original entered value (with no manual override possible).

**To Reproduce**
This is a situation that often occurs for Cryptocurrencies. That's why I'm going to do the example with Bitcoin (All Securities > New Cryptocurrency... > BTC (The first yellow one) > Ok).
1. On Bitcoin Securities : Buy...
2. Add a transaction with: _Shares 0.00123 x Quote **54,123**_
3. Save
4. Now you can see that the Quote price is **_54,121.95_**

When you go on the record and _Edit Transaction..._, you can modify the wrong value and save the Quote, but the modification of the value doesn't apply, the Quote price is still the same and not the one I wish.

Besides the rounding, the biggest problem is that **it distorts my transaction history which is no longer a source of truth** (even before calculation/statistics).

**Expected behavior**
I would like the values entered not to be modified automatically. When rounding is necessary, it would be more relevant in the _Debit Note_ (or directly in the total at the end of the line) rather than modify my recording compared to the real values (which are no longer available after automatic modification).

Thanks.

**Desktop:**
 - OS: macOS Sonoma 14.6.1
 - Version: 0.70.3 (August 2024)

**Comment by Morpheus1w3** [comment]
The default behavior in PP prioritizes shares and total value to prevent rounding discrepancies. The quote price per share is always calculated when needed in the report or somewhere else.
