### ISSUE TITLE
Website download link points to 0.71.0 while application advertises 0.71.1

### ISSUE THREAD

**Issue by zieren** [portfolio-performance/portfolio#4248]
The downloads on https://www.portfolio-performance.info/ are only for 0.71.0. The application advertises 0.71.1, which is only available via "other downloads".

Looks like a different data source is used both times, which makes this problem possible.

**Comment by Sn1kk3r5** [comment]
Fine again with latest version: 0.71.2
![image](https://github.com/user-attachments/assets/5ca31bca-c3e9-4a6a-b7bb-c24f63651f60)

**Comment by zieren** [comment]
Thanks for the update! I'm just wondering: Why doesn't the app check which download is actually available? By having just a single source of truth this kind of bug would be impossible.

**Comment by Nirus2000** [comment]
Thx
