### ISSUE TITLE
Feature request: Weekly, Bi-weekly Interval (Investment Plan)

### ISSUE THREAD

**Issue by DiamondHanz** [portfolio-performance/portfolio#4330]
**Is your feature request related to a problem? Please describe.**
There is currently no option to schedule weekly or bi-weekly investment plans. The only option is the monthly interval.

**Describe the solution you'd like**
Add the option to schedule weekly and bi-weekly interval using the investment plan. Or if possible custom interval.

**Describe alternatives you've considered**
None available

**Additional context**
N/A

**Comment by Sn1kk3r5** [comment]
A possible workaround can be the creation of multiple saving plans with a two-week difference between both starting points.
Not the most convenient way, but it works.

**Comment by DiamondHanz** [comment]
> A possible workaround can be the creation of multiple saving plans with a two-week difference between both starting points. Not the most convenient way, but it works.

Thanks for your comment. 
Sure, it's a workaround but not a good and clean solution. I see discussions requesting more investment plan intervals since august 2020 and never been resolved correctly.

**Comment by mierin12** [comment]
Hello, 
What would be the definition of biweekly ?
- each two Mondays/Tuesdays etc -> 52 weeks/2= 26 operations per year
- twice a month (ex : each 1st and 15th days of each month) -> 2*12 months = 24 operations a year

I think the first way may be easier to do. And the first definition is where the workaround with several monthly plans does not work anymore. But I do not know which one makes more sense in reality.

**Comment by mierin12** [comment]
Done on [release 0.72.0 and 0.72.1](https://github.com/portfolio-performance/portfolio/releases/tag/0.72.0) from https://github.com/portfolio-performance/portfolio/pull/4347
