### ISSUE TITLE
PDF-Import of Trade Republic "Kontoauszug" does not import interests on purpose

### ISSUE THREAD

**Issue by somehowdifferent** [portfolio-performance/portfolio#4365]
Dear team,

Lot's of things are working really awesome. However, the when I import the Kontoauszug PDF from Trade Republic, "interests" are excluded from the import on purpose. It says, it would be imported from a different source.

![Bildschirmfoto von 2024-11-23 13-37-26](https://github.com/user-attachments/assets/27f694cf-0343-45c0-8ab5-364ee31a3fab)

What would be that source? I didn't found any other useful pdf document from Trade Republic that lists interests. Could you either point me to the document or even better, just reenable the import of interests from this "Kontoauszug" listing.

Thank you very much.
somehow.different

PS: Here's a current pdf export that technically imports completely but ignores the interest lines

```
PDFBox Version: 1.8.17
Portfolio Performance Version: 0.71.2
-----------------------------------------
NAME NAME DATUM 01 Mai 2024 - 31 Okt. 2024
Musterstraße 01, 01234 IBAN DE1234123412341234
Musterstadt, DE BIC TRBKDEBBXXX
KONTOÜBERSICHT
PRODUKT ANFANGSSALDO ZAHLUNGSEINGANG ZAHLUNGSAUSGANG ENDSALDO
Depotkonto 4.364,11 € 6.049,52 € 0,00 € 10.413,63 €
UMSATZÜBERSICHT
DATUM TYP BESCHREIBUNG ZAHLUNGSEINGANG ZAHLUNGSAUSGANG SALDO
01 Mai 2024 Zinszahlung Your interest payment 5,36 € 4.369,47 €
29 Mai 2024 Überweisung Einzahlung akzeptiert: DE1234123412341234 auf DE567856785678 1.000,00 € 5.369,47 €
01 Juni 2024 Zinszahlung Your interest payment 5,67 € 5.375,14 €
01 Juli 2024 Zinszahlung Your interest payment 6,60 € 5.381,74 €
01 Aug. 
2024 Zinszahlung Your interest payment 6,83 € 5.388,57 €
05 Aug. 
2024 Überweisung Incoming transfer from name name 5.000,00 € 10.388,57 €
01 Sept. 
2024 Zinszahlung Your interest payment 12,36 € 10.400,93 €
01 Okt. 
2024 Zinszahlung Your interest payment 12,70 € 10.413,63 €
Seite 1 von 2
Erstellt am 23 Nov. 2024
Trade Republic Bank GmbH
HAFTUNGSAUSSCHLUSS
Sehr geehrte Kundin, sehr geehrter Kunde
Bitte überprüfe unbedingt deine Buchungen, Berechnungen und den Schlusssaldo auf dem Kontoauszug, der gleichzeitig deinen Rechnungsabschluss 
darstellt. Der Rechnungsabschluss gilt als anerkannt, wenn du innerhalb von sechs Wochen nach Zugang keine Einwendungen erhebst. Einwendungen 
gegen Kontoauszüge sind schriftlich an uns zu richten. Guthaben sind einlagefähig im Sinne des Einlagensicherungsgesetzes (EinSiG). Weitere 
Informationen entnehme bitte dem Merkblatt für den Einleger, das zusammen mit unseren Allgemeinen Geschäftsbedingungen eingesehen werden kann.
Trade Republic Bank GmbH Kontakt Sitz der Gesellschaft: Berlin
Brunnenstraße 19-21 www.traderepublic.com AG Charlottenburg HRB 244347 B
10119 Berlin service@traderepublic.com Umsatzsteuer-ID DE307510626
Seite 2 von 2
Erstellt am 23 Nov. 2024
Trade Republic Bank GmbH

```

**Comment by Nirus2000** [comment]
Hello @somehowdifferent 
Yes, the interest postings are provided via another Trade Republic document.
Any taxes and fees are then also processed in this document. This has been done internally by Trade Republic as a result of the changeover.
The document should also be available to you (ABRECHNUNG ZINSEN) and can be imported without any problems.
See in this [folder](https://github.com/portfolio-performance/portfolio/blob/master/name.abuchen.portfolio.tests/src/name/abuchen/portfolio/datatransfer/pdf/traderepublic/) --> ZinsabrechnungXX.txt (PDF debugs)

So... check this out.

Regards
Alex
