### ISSUE TITLE
Historical Quotes Binance Crypto Exchange 400 Bad request

### ISSUE THREAD

**Issue by znahas** [portfolio-performance/portfolio#4369]
**Describe the bug**
When choosing Historical Quotes Binance Crypto Exchange 400 Bad request.
Example below. Please advice on how to fix that?

**Screenshots**
![image](https://github.com/user-attachments/assets/65936776-d08d-4146-b14a-82e87f5d4660)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.71.2 (October 2024)

**Comment by Morpheus1w3** [comment]
@znahas
According to https://api.binance.com/api/v3/exchangeInfo
 the symbol should be BEAMXUSDT, not BEAMX.
