### ISSUE TITLE
Durchschnittlicher Einstandskurs

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#440]
Bin mir noch nicht sicher, scheint aber in der Schweiz steuerlich relevant zu sein.

Name?

> Kauf 500 zu 3.94 = BEP 3.94
> Kauf 1200 zu 3.20 = BEP 3.42
> Kauf 275 zu 2.86 = BEP 3.34
> Kauf 720 zu 2.75 = BEP 3.18
> Kauf 1300 zu 1.49 = BEP 2.63
> Kauf 1900 zu 1.57 = BEP 2.29
> Kauf 3200 zu 1.45 = BEP 1.54
> Verkauf 3200 zu 1.56 = BEP 2.22 
> Verkauf 3300 zu 1.65 = BEP 2.94

**Comment by votacom** [comment]
Auch in Österreich ist der durchschnittliche Einstandswert (im Gesetz als "gleitender Durchschnittspreis" bezeichnet) die steuerlich relevante Größe. (Im Gegensatz zu Deutschland, wo nach dem FIFO-Pronzip besteuert wird)
