### ISSUE TITLE
Swissquote - PDF - Buy of Fractional-Shares can't be importet (Error message)

### ISSUE THREAD

**Issue by bc-Ned** [portfolio-performance/portfolio#4419]
**Describe the bug**
An import of  a Swissquote - PDF transaction, can't be processed. The buy of Fractional-Shares shows the following error message (attached screenshot):

**To Reproduce**
Steps to reproduce the behavior, start Portfolio Performance:
1. Go to "File"
2. Click "Import"
3. Click "PDF Bank document"
4. Choose the local PDF file
5. See error

**Expected behavior**
The fractional buy should be imported without error.

**Screenshots**
![error-message](https://github.com/user-attachments/assets/9aa43643-90b9-43dc-8d0a-7673ea1ff239)

**Desktop (please complete the following information):**
 - OS: [Windows 11, newest HF)

**Comment by Nirus2000** [comment]
Hello @bc-Ned 

Please watch the tutorial video carefully and post a “complete” PDF debug.

    Otherwise, please do not change or delete any other data.
    The personal data must be replaced 1 to 1.
    Other changes, such as replacing the date or similar, are also counterproductive.
    **!! ONLY YOUR OWN PERSONAL DATA !!!
    No PDFs which are converted to PDF from a browser or similar
    No self-scanned paper slips

z. B.

    Name → Max Mustermann and so on…
    Address → Blumenstraße
    IBAN and deposit numbers: The numbers 1 to 1.*

No more and no less… One post per PDF debug please.
End.

Video tutorial:
Extract PDF documents for debugging 3

Regards
Alex

**Comment by bc-Ned** [comment]
Hello Alex @Nirus2000 
as requested:

```
PDFBox Version: 1.8.17
Portfolio Performance Version: 0.72.2
-----------------------------------------
TRANSAKTIONSBELEG
Kunde: 0950311 - TRADING
IBAN: CH1111111000212241300
Herrn mPvWQ AeiLRqW
xNjXWfhLGdRrFgC 633
CH-6873 wgnl
Gland, 15.11.2024
Kauf Unsere Referenz: 699111111 
Am 15.11.2024 haben wir folgende Transaktionen vorgenommen:
Titel Börse
AMAZON COM ORD ISIN: US0231351067 NASDAQ New York 
NKN: 645156
Anzahl Preis Betrag
0.4683 202.57 USD 94.86
Total USD 94.86
Abgabe (Eidg. Stempelsteuer) USD 0.14
Zu Ihren Lasten USD 95.00
Betrag belastet auf Kontonummer  999999301, Valutadatum 18.11.2024
Dieser Transaktionsbeleg sowie die aufgeführte Transaktion unterliegen der Vereinbarung über den Handel mit fraktionalen Instrumenten für
Trading-Konten.
Bitte beachten Sie, dass Swissquote Bank AG das betreffende Finanzinstrument als Treuhänder hält und Ihnen einen Treuhandanteil im Verhältnis
zu dem Ihnen zugeteilten Anteil gewährt.
Wenn Sie mehrere Transaktionen über den Erwerb oder die Veräusserung von Treuhandanteilen eingegangen sind und nach diesen Transaktionen
Ihre kumulierten Treuhandanteile an einem einzigen Finanzinstrument eine ganze Einheit (oder mehr) ausmachen, wandeln wir Ihre
Treuhandanteile im Allgemeinen in das Halten einer ganzen Einheit des Finanzinstruments gemäss der Vereinbarung über den Handel mit
fraktionalen Instrumenten für Trading-Konten.
Die Angabe einer Börse oder eines anderen Ausführungsplatzes wird nur zu Informationszwecken angegeben und bedeutet nicht, dass Ihr Auftrag
dort ausgeführt wurde. Zum Zeitpunkt der Ausführung Ihres Auftrags haben wir das betreffende Finanzinstrument möglicherweise noch nicht
erworben oder veräussert. Die Buchung dieser Transaktion ist gemäss der Vereinbarung über den Handel mit Fraktionalen Instrumenten für
Trading-Konten für einige Tage möglicherweise vorläufig. Bitte setzen Sie sich mit uns in Verbindung, wenn Sie weitere Informationen dazu
benötigen.
Die Angabe einer Börse oder eines anderen Ausführungsplatzes wird nur zu Informationszwecken angegeben und bedeutet nicht, dass Ihr Auftrag 
Vielen Dank für Ihren Auftrag.
Swissquote Bank AG, 33 chemin de la Crétaux, CH-1196 Gland  Formular ohne Unterschrift | SE&O.
Customer Care : 0848 25 88 88 (Aus dem Ausland +41 44 825 88 88)
MwSt n° CHE-116.310.079 

```

I've changed Name, Address and the Kunden/Konto-Nummern, nothing else.

Lg, Jan
