### ISSUE TITLE
Portfolio Turnover Ratio

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#476]
Aus dem [Wertpapier Forum](http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__1018682):

> Die Portfolio Turnover Ratio wäre doch eine schöne Ergänzung zur bestehenden Übersicht auf der "Performance" Seite. Wenn ich wüsste, wie ich an den monatlichen Stand des Gesamtvermögens in PP käme, hätte ich mich mal an der Berechnung für mein Portfolio versucht. Ich glaube über die letzten 12 Jahre dürfte er bei 5% p.a. liegen.

[aus Wikipedia](https://de.wikipedia.org/wiki/Portfolio_Turnover_Ratio): Die **Portfolio Turnover Ratio** (Besser: Portfolio Turnover Rate, Abkürzung: PTR) gibt an, wie viele Transaktionen auf Basis einer meistens jährlichen Berechnung im Vermögen eines Investmentfonds oder eines Wertpapierportfolios vorgenommen wurden. Vorschlag für eine deutsche Bezeichnung: Umschlagsrate. Wenn PTR = 100 %, dann ist das Portfolio ein Mal in der Berichtsperiode umgeschlagen worden.

Je näher sich die so ermittelte Kennzahl gegen 0 richtet, umso direkter stehen die getätigten Transaktionen im Zusammenhang mit der Ausgabe und Rücknahme von Anteilscheinen. Transaktionen mit Derivaten werden in die Berechnung der PTR nicht mit einbezogen.

Die PTR ist ein wichtiges Maß für die Kosten, die das Fondsmanagement verursacht.

PTR-Formel

![602043c9a4d996417d2886e8732a2e11](https://cloud.githubusercontent.com/assets/587976/13930441/479f9954-ef9f-11e5-9cbe-990608211aee.png)

min: Minimumfunktion
X = Wert der Käufe von Wertpapieren (im Jahr)
Y = Wert der Verkäufe von Wertpapieren (im Jahr)
M = (Monatlicher) Durchschnitt des Gesamtvermögens

**Comment by simpsus** [comment]
Wenn die Periode der Selektionszeitraum ist dann sollte das nicht so schwer sein.
Dann könnte man darüber nachdenken den Reiter "Kennzahlen" zu nennen. Denn wir haben jetzt schon Performance und Risikozahlen dort.

**Comment by simpsus** [comment]
Macht es hier Sinn ebenfalls ein Widget für das Dashboard zu erstellen?

**Comment by buchen** [comment]
Genau, wenn dann als Widget. Ich kann persönlich nicht sagen wie aussagekräftig der Wert wird.
