### ISSUE TITLE
Vermögensaufstellung - Diagramm - investiertes Kapital

### ISSUE THREAD

**Issue by bartho1** [portfolio-performance/portfolio#482]
Hallo,

in der Diagrammdarstellung der Vermögensaufstellung wird das investierte Kapital dem Depotwert zu Beginn der Zeitdarstellung gleich gesetzt, das entspricht aber je nach gewähltem Zeitausschnitt nicht der eigentlichen Kapitaleinlage. Wenn ich jetzt aber einen WP-Sparvertrag habe und z.B. monatlich Geld einzahle wäre es schön zu sehen, wie sich der Depotwert im Verhältnis zum eingezahlten Geld verhält. Hierfür wäre eine eigene Datenreihe z.B. "Kapitaleinlage" sehr schön, ist das möglich zu realisieren?

Danke und Grüße!

**Comment by buchen** [comment]
Um das über den ganzen Sparplan hinweg zu sehen, müsstest Du in der Tat den Berichtszeitraum entsprechend lange auswählen. Aber in der Tat könnte man auch eine absolute Linie eintragen - also nicht auf den Zeitraum bezogen.
