### ISSUE TITLE
Yahoo Symbol automatisch auflösen wenn ISIN erfasst wurde

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#540]
Idee: wenn man eine ISIN hat, dann könnte der Kursdownload nach einem passenden Ticker Symbol suchen um die automatische Kursabfrage zu vereinfachen.

Aus dem [Wertpapier Forum](http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__1033158)

> > Yahoo ist die einzige Quelle für historische Kurse auf die ich per API zugreifen kann. Und ohne das Ticker Symbol geht da nicht viel. Man kann zwar auf Yahoo auch nach einer ISIN suchen, aber für die programmatischen Aufrufe reicht ISIN leider nicht.
> 
> Was ich meinte war: Wenn man eine ISIN oder WKN eingibt, ist es dann eventuell möglich, programmatisch die fehlenden Werte (Ticker) nachzureichen? Das würde die Bedienung deutlich einfacher machen.

**Comment by jayD** [comment]
Finde die Idee gut!

**Comment by mammuth** [comment]
Das würde zB. auch das Usability Problem aus #357 lösen.

**Comment by codeofsumit** [comment]
Das wäre super. Bin eben auch über #357 gestolpert

**Comment by phiresky** [comment]
Wollte anmerken, dass das grundsätzlich per OpenFIGI API möglich ist, zB

```
curl 'https://api.openfigi.com/v2/mapping' --request POST --header 'Content-Type: application/json' --data '[{"idType":"ID_ISIN","idValue":"IE00BD45KH83","micCode": "XETR"}]' | jq '.[].data[].ticker'
```

gibt das ticker symbol `IBC3` für die isin IE00BD45KH83 an der börse XETR zurück. ohne micCode:XETR gibt es die ticker symbole an allen börsen zurück.
