### ISSUE TITLE
Wertpapier hinzufügen: Ticker/Börsenplatz automatisch im Namen aufnehmen

### ISSUE THREAD

**Issue by megabugman** [portfolio-performance/portfolio#544]
PP:
![name](https://cloud.githubusercontent.com/assets/17204819/16284835/74c25480-38d3-11e6-9904-197d30014861.png)
yahoo:
![xetra2](https://cloud.githubusercontent.com/assets/17204819/16284842/7a5424f0-38d3-11e6-8982-c1313529be3a.PNG)
enhancement:
![wie_yahoo](https://cloud.githubusercontent.com/assets/17204819/16284847/8604bd32-38d3-11e6-9909-3439046e042b.PNG)

**Comment by buchen** [comment]
Bei dem initiale Anlegen eines Wertpapiers könnte ich das machen, aber ich will das nicht dauerhaft in den Namen mit aufnehmen - man kann ja den Börsenplatz auch relativ einfach wieder ändern. Und dann kann ich nicht mehr automatisch den Namen ändern (der Benutzer kann den ja frei editieren).

Was ich aber machen kann ist den Ticker und auch den Handelsplatz in die Überschrift von dem Kursdiagramm aufnehmen. Dann taucht das allerdings "nur" im Diagramm auf und nicht in den anderen Dialogen.
