### ISSUE TITLE
Dashboard: Widget bei kleinen Fenster abgeschnitten

### ISSUE THREAD

**Issue by Beluk** [portfolio-performance/portfolio#564]
Windows 10:

![dashboard](https://cloud.githubusercontent.com/assets/10911904/16714778/074dc214-46ce-11e6-8714-752a9350b4bd.png)

**Comment by buchen** [comment]
Yep, auch bei den Heatmaps ist das noch nicht optimal. Ich hab die Version trotzdem schon mal veröffentlicht. Da kommt bestimmt noch mehr 😄
