### ISSUE TITLE
Dashboard: Alle Widget auf einmal ändern

### ISSUE THREAD

**Issue by Beluk** [portfolio-performance/portfolio#565]
Es wäre schön wenn man auf das Dashbord selber klicken könnte und damit Änderungen an allen Widget auf einmal durchführen könnte.

**Comment by buchen** [comment]
Welche Änderungen meinst Du?

Den Berichtszeitraum kann man ja oben rechts global ändern. Vielleicht die Datenreihe anpassen? Da die nicht bei allen Widgets gleicht ist, habe ich das erst mal gelassen.

**Comment by Beluk** [comment]
Die Datenreihe meinte ich.

Mein Vorgehen war folgendermaßen:
1.	Habe zuerst die Standardansicht zweimal dupliziert: Einmal für Fremdkapital (Anleihen) und einmal für Eigenkapital (Aktien). 
2.	Danach wollte ich die jeweiligen Datenreihen aus der Klassifizierung zu allen Widget auf der jeweiligen Ansicht zuordnen. 

Ist wahrscheinlich etwas, wenn die Ideen ausgehen, da nach einmaligen Zusammenklicken man wahrscheinlich nichts mehr oder nicht mehr viel ändern wird. ;-)
