### ISSUE TITLE
Nach Aktualisierung suchen ... - ev doch ein Problem

### ISSUE THREAD

**Issue by JosScha** [portfolio-performance/portfolio#578]
Ich hatte das Problem schon mal mit #502 gemeldet.

Heute ist die Version 0.24.2 veröffentlicht worden. Nach dem mein PP noch gelaufen ist, habe ich wieder versucht die Funktion "Nach Aktualisierung suchen" zu verwenden. Ich bin aber zum gleichen Ergebnis gekommen.

![1_ueber2 4 1](https://cloud.githubusercontent.com/assets/17599939/16899461/05e85efc-4c05-11e6-8bff-06e84a4910de.PNG)

![2_nachaktualisierungsuchen](https://cloud.githubusercontent.com/assets/17599939/16899463/0c8d8d40-4c05-11e6-9090-f2c7419f66be.PNG)

![3_fehlerprotokoll](https://cloud.githubusercontent.com/assets/17599939/16899465/13af53ce-4c05-11e6-9ff0-9734bfa0d09b.PNG)

![4_einstellungurl](https://cloud.githubusercontent.com/assets/17599939/16899466/1d965c02-4c05-11e6-9ee8-d24e113f5cec.PNG)

Ich hatte das gleich auch von 0.24.0 auf 0.24.1.
Ich habe seit #502 von Windows 7 auf Windows 10 umgestellt.

**Comment by etzelc** [comment]
Kann ich bestätigen.
Wenn es PP neu gestartet wird, kommt sofort der Updatehinweis "Eine neue Version ist verfügbar".

**Comment by buchen** [comment]
Das sind mir die liebsten Tierchen: keine Fehlermeldung aber es tut nicht... 😁 
Ich habe eine Win10 Installation in einer VM - da werde ich das noch mal ausprobieren.
@etzelc ist das bei Dir ebenfalls Win10?

Ansonsten wäre es hilfreich wenn ich mal das komplette PP Verzeichnis einer sich nicht selbst updateten Version als ZIP bekommen könnte. Z.B. per Dropbox oder so.

**Comment by etzelc** [comment]
Ja, Windows 10. PP lief seit 14.7, der Rechner war zwischendurch im Standby und Hybernate. 
Leider hatte ich vergessen vor dem PP Neustart in den Fehlerlog zu schauen und nach dem Neustart zeigt PP das gewünschte Verhalten. 
Beim nächsten Update werde ich darauf achten.

**Comment by JosScha** [comment]
Kannst du mir eine Mailadresse schicken.

Bei mir ist es auch so, dass ich immer wieder in den standby wechsle.

**Comment by buchen** [comment]
portfolio.performance.help@gmail.com

Keine Ahnung ob die Email das verträgt - es sollten ca. 34MB sein. Ich meinte mit Dropbox auch die "öffentlichen Link" die ja vom Dropbox Server bereitgestellt werden.

**Comment by JosScha** [comment]
Hab den Link via Mail geschickt.

**Comment by buchen** [comment]
👍 Schaue ich mir an - wird allerdings etwas dauern.

**Comment by buchen** [comment]
Mmmmh..

Meine drei Experimente unter Win10 64bit waren alle erfolgreich: 0.22.0, 0.22.3 und 0.24.1 konnten problemlos aktualisiert werden.

Das ZIP beinhaltet keine Hinweise.

@JosScha Könntest Du mir noch mal das Verzeichnis ~/AppData/Local/PortfolioPerformance zippen und schicken? Vielleicht ist da was zu erkennen.

**Comment by buchen** [comment]
Note to myself:

Wenn überhaupt, sind diese Meldungen auffällig (kurz danach wird das Modell erfolgreich aktualisiert -> sprich die neue Version läuft):

```
!ENTRY org.eclipse.equinox.p2.touchpoint.natives 2 0 2016-07-10 19:17:03.117
!MESSAGE Could not remove temporary backup directory (it is safe to manually delete it and its contents): C:\Users\XYZ\AppData\Local\Temp\DefaultProfile_2abab9fe33a0_c0a8011eeaa5
```
oder auch:
```
!ENTRY org.eclipse.equinox.p2.touchpoint.natives 2 0 2016-07-18 20:38:51.239
!MESSAGE Could not remove temporary backup directory (it is safe to manually delete it and its contents): C:\Users\XYZ\AppData\Local\Temp\DefaultProfile_2abfe9b6c0e0_c0a8011ef6fa
```

**Comment by etzelc** [comment]
Ich habe das nochmal versucht und das Problem kann ich bei mir folgendermaßen reproduzieren (Win 10, 0.23.2 64 bit mit JDK 8_74; 0.24.2 32 bit mit JRE 8_101; 0.24.2 64 bit mit JDK 8_74):

1. Alle Internetverbindungen trennen (kein aktives LAN und WLAN)

2. Starte Portfolio Performance

3. Prüfe auf Updates (Menü "Hilfe" --> "Nach Aktualisierungen suchen ...")
   - Ergebnis "Keine Updates vorhanden" + Fehlerprotokolleintrag (siehe unten)

4. Aktiviere Internetverbindung (hier über LAN)

5. Prüfe auf Updates (Menü "Hilfe" --> "Nach Aktualisierungen suchen ...")
   - Ergebnis "Keine Updates vorhanden", KEIN Fehlerprotokolleintrag

6. Portfolio Performance schließen

7. Portfolio Performance starten

8. Nach wenigen Sekunden kommt der Hinweis auf die neue Version (zur Zeit 0.25.0)

Eigentlich sollte das Programm bereits bei Schritt 5 die neue Version finden.

Fehlerprotokolleintrag bei Schritt 3:

`!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2016-10-05 13:28:09.352
!MESSAGE Connection to http://updates.abuchen.name/portfolio/p2.index failed on updates.abuchen.name. Retry attempt 0 started
!STACK 0
java.net.UnknownHostException: updates.abuchen.name
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1077)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:1068)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:1064)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

**Comment by buchen** [comment]
Der Fehler bei Schritt 3 ("unkown host") ist verständlich, aber in Schritt 5 sollte er - mit Internetverbindung - schon wieder was finden... 🤔 Ich werde mal versuchen mit den gleichen Schritten dem auf die Spur zu kommen.

**Comment by etzelc** [comment]
Mein Fix ist mit der Codebasis von Version 0.33.0 getestet worden (da ich keinen eigenen Updateserver aufsetzen wollte) und zeigt jetzt das gewünschte Verhalten. Vermutlich arbeite ich nur um einen Eclipse-Bug ([https://bugs.eclipse.org/bugs/show_bug.cgi?id=520461](https://bugs.eclipse.org/bugs/show_bug.cgi?id=520461)) herum.
Der Workaround könnte für mehr Last auf dem Updateserver sorgen, da der lokale Cache bei jeder Aktualisierung verworfen und neu geladen wird. Fällt mir schwer genau zu beurteilen.
