### ISSUE TITLE
Dashboard Heatmap der Jahresrenditen

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#585]
Aus dem [Wertpapier-Forum](http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__1039058):

> Die Heatmap der Monatsrenditen habe ich auch gleich in das Dashboard übernommen. Von hier wäre es doch auch ein kleiner Schritt zur Heatmap der Jahresrenditen und man hätte so in komprimierter Form die selbigen, statt 10mal oder mehr ein Widget einzufügen für die Zeiträume?

**Comment by buchen** [comment]
Und [wieder](http://www.wertpapier-forum.de/topic/38306-portfolio-performance-mein-neues-programm/page__view__findpost__p__1049374):

> Noch ist die PP-Nutzungsdauer relativ kurz, aber das ändert sich. Ich fände es gut, wenn das Monatsrenditenwidget eine weitere Spalte mit der Jahresrendite bekommen würde. Vermutlich wird auch mal ein Jahresrenditenwidget interessant.

**Comment by hajo62** [comment]
Gibt es das Jahresrenditen-Widget nicht bereits?
<img width="335" alt="image" src="https://github.com/portfolio-performance/portfolio/assets/15800980/3fe8adff-0df7-4753-bb8b-28cca657c292">
Oder meinst Du etwas anderes?
