### ISSUE TITLE
"Delta (Gesamtsumme - Investiertes Kapital)" für einzelnes Portfolio

### ISSUE THREAD

**Issue by th23x** [portfolio-performance/portfolio#605]
Klasse ist die Möglichkeit die Linien des Diagrams unter Vermögensaufstellung für einzelne Portfolio-Cah-Kombinationen anzeigen zu lassen :+1: 

Was ich dann aber vermisse, ist diese Möglichkeit auch für die Gewinn/Verlust Anzeige, also das "Delta (Gesamtsumme - Investiertes Kapital)". Dieses wäre noch eine tolle Ergänzung!?

**Comment by buchen** [comment]
Vermutlich sowohl für die Portfolio als auch die Portfolio + Cash Kombination.
Es fehlen die Datenreihe für das investiertes Kapital (```INVESTED_CAPITAL```) und das Delta (```ABSOLUTE_DELTA```).

**Comment by th23x** [comment]
Vielen Dank für die schnelle Antwort und Berücksichtigung!

Korrekt, bei diesen beiden Werten konnte ich die entsprechenden Datenreihen auch nicht auswählen - bei allen anderen die ich eingestellt habe (TWROR, IZF, ...) war es möglich.

Damit wäre dann die Verwaltung mehrerer Portfolios in einer Datei möglich, zB eine langfristige Anlage, ein Riester-Depot, ... - und über "Gesamt-Portfolio" auch alle Investments zusammen zu betrachten :-)

**Comment by mierin12** [comment]
Delta for any data series is now available in the Assets graph with release [0.73.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.73.0) from https://github.com/portfolio-performance/portfolio/pull/4403
