### ISSUE TITLE
Rebalancing: Spalte mit relativem Verhältnis der Positionen

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#642]
Aus dem Wertpapier Forum:

> Ich vermisse eine Spalte "Delta % (relativ)", die das Verhältnis aus "IST %" und "Aufteilung" darstellt. Wenn z.B. meine Aktien-ETFs im Verhältnis USA/EU/EM 40/35/25 aufgeteilt sein sollen und das Ist-Verhältnis ist 39/35/26, soll die Spalte -2,5%/0%/4% anzeigen, unabhängig von der Soll/Ist-Aufteilung des Aktienanteils bezogen auf das Gesamtportfolio.

**Comment by myrdd** [comment]
This issue can be closed. As @buchen wrote in https://github.com/portfolio-performance/portfolio/pull/1038, the feature is actually already implemented as "Delta %".

Still, https://github.com/portfolio-performance/portfolio/pull/1038 introduces "Delta % (relative)". The implementation of that new column (and the naming confusion) is discussed in https://github.com/portfolio-performance/portfolio/issues/1554.

**Comment by Nirus2000** [comment]
Done
