### ISSUE TITLE
automatische Spaltenbreite Anpassung mittels Doppelklick Fehler

### ISSUE THREAD

**Issue by megabugman** [portfolio-performance/portfolio#653]
normalerweise wird durch Doppelklick die Spaltenbreite automatisch angepasst. 
Bei Bestand funktioniert das nicht (richtig).
![spaltenbreite](https://cloud.githubusercontent.com/assets/17204819/20327303/cba9787e-ab8c-11e6-8eb4-b909834c1573.PNG)

**Comment by buchen** [comment]
Die "Bestand" Spalte behandele ich besonders. Warum? Ich blende die Nachkommastellen aus wenn es keine Bruchteile gibt. Das ist damit ein "user drawn label" und ich muss die Breite manuell berechnen. Auf macOS funktioniert das korrekt. Unter Windows aber anscheinend nicht. Ist das Windows 10?

**Comment by megabugman** [comment]
Nein, es handelt sich hier um Win 7 64 Bit
