### ISSUE TITLE
Vereinfachung beim Import von (vielen) PDF Dokumenten

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#692]
* Mehr Hilfe biet Anonymisieren

* PDF Dokumente (optional) an eine andere Stelle kopieren wenn man es erfolgreich importieren konnte

* PDF Dokumente automatisch erkennen - keine Auswahl der Bank mehr

**Comment by Nirus2000** [comment]
This issue is done...

**Comment by siprbaum** [comment]
> * PDF Dokumente (optional) an eine andere Stelle kopieren wenn man es erfolgreich importieren konnte

Just wondering, how can this be activated? E.g. how to copy the imported PDFs to another folder?
No need to reopen if this is not available, I understand that there is some cleanup activities ongoing after the move to the new organization.

**Comment by Nirus2000** [comment]
Outdated views of the importers...
done...
