### ISSUE TITLE
Dividende wird nicht depotweise berücksichtigt

### ISSUE THREAD

**Issue by linusvanp** [portfolio-performance/portfolio#696]
Bei der Berechnung der Performance für ein einzelnes Depot, werden Erträge nicht auf den Bestand des Depots runtergerechnet.
Beispiel (vgl. Anhang): Wertpapier in Depot A mit Bestand 100 und in Depot B mit Bestand 1. Wird dann ein Betrag für 101 Stück gebucht, dann erscheint der in voller Höhe bei der Berechnung der Performance für beide Depots.
Das führt für Debot B natürlich zu großen Ergebnissen.

Zu sehen ist der Effekt besonders einfach im Diagramm, aber auch unter "Berechnung".

[dividend_depot_split.xml.zip](https://github.com/buchen/portfolio/files/690951/dividend_depot_split.xml.zip)

**Comment by buchen** [comment]
Yep, das ist ein Problem. Ich ordne eine Dividendenzahlung zwar einem Wertpapier zu, aber nicht einem Depot. Das "löse" ich normalerweise über das Referenzkonto auf. Wenn aber ein und dasselbe Konto bei zwei Depots als Referenzkonto angegeben ist, dann schlägt das fehl.

Eine mögliche Lösung könnte sein: die Dividendenzahlung nur dann dem Depot zuordnen, wenn a) Referenzkonto stimmen und die Anzahl der Stücke stimmen. Historisch gesehen habe ich die Anzahl der Stücke aber erst sehr viel später als Datenfeld eingeführt. Es können als potentiell Buchungen bei Benutzern existieren, die keine Stücke haben - die sollten aber nicht direkt rausfallen. Da muss ich mir also was überlegen.

Alternativ könnte ich das Depot auch zwingend bei der Dividendenbuchung erfassen. Und das existierende Datenmodell migrieren.

Beides ist aufwändig und darum nicht mal eben zu machen - ich bin mir aber des Problems bewußt.

Ganz konkret könntest Du das nur lösen/umgehen, indem Du ein zweites "virtuelles" Referenzkonto anlegest und so die Buchungen separierst. Nicht ganz elegant - das verstehe ich.

**Comment by linusvanp** [comment]
Vielen Dank für den Hinweis. 
Hab' einfach neue Referenzkonten eingeführt und einiges umgebucht. Jetzt funktioniert's.
