### ISSUE TITLE
Im Browser öffnen: intelligente Ersetzungslogik für Ticker, ISIN und WKN

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#698]
Problem:

> Wenn man dies mit einem Titel tut, der
bereits ein konfiguriertes Ticker-Symbol
hat, dann verwendest Du dieses für den
Link zu Yahoo Finance:

> https://de.finance.yahoo.com/q?s=SIE.DE

> führt zur Siemens-Aktie an der Börse XETRA.

> Hat der Titel jedoch kein konfiguriertes
Ticker-Symbol, dann lässt Du diese einfach
leer:

> https://de.finance.yahoo.com/q?s=

> führt zu einer Yahoo-Finance-Seite mit dem
Text: "Geben Sie Unternehmens-Namen oder
Aktien-Symbol in das Eingabefeld oben ein,
um einen Kurs zu erhalten".

> Was Du leider nicht tust, das ist, eine
bereits konfigurierte ISIN zu verwenden.
Nach dieser kann man nämlich ebenfalls suchen:

> https://de.finance.yahoo.com/lookup?s=DE0007236101

> führt zu einer Seite, die eine Liste aller
Börsenplätze der Siemens-Aktie anzeigt.
(Und diese Liste enthält mehrere verschiedene
Ticker-Symbole!)

Vielleicht könnte man URLs wie folgende erlauben:
```
https://de.finance.yahoo.com/lookup?s={ticker,isin,wkn}
```
Und dann wird die ISIN genommen wenn es keinen Ticker gibt.

**Comment by buchen** [comment]
Die (triviale) Ersetzungslogik ist hier: https://github.com/buchen/portfolio/blob/74d4e35092717b621618a700fbef90835c211b79/name.abuchen.portfolio/src/name/abuchen/portfolio/model/Bookmark.java#L43-L51

**Comment by sunnylars** [comment]
Hallo,
bei meinen Tests bezüglich der Ersetzungslogik habe ich bei yahoo keine ergebnisse bekommen.

Das Problem ist wohl, das yahoo z.b. bei einem gesetzten ticker und wkn, was dann so aussehen würde : s=TICKERWKN keine ergebnisse liefert.

ich habe das mal umgebaut, sodass die reihenfolge der ersetzungen gleichzeitig die priorität ist und nach der ersten ersetzung keine weitere ersetzung stattfindet.

**Comment by sunnylars** [comment]
@buchen ich schlage mich gerade mit github rum, da ich mit github noch nicht gearbeitet habe. darf ich denn dazu einen pull request erstellen? oder willst du den vorschlag erstmal anders sehen?

**Comment by buchen** [comment]
Klar - einfach eine Pull Request erstellen. Das ist der Weg sich den Vorschlag anzuschauen!
