### ISSUE TITLE
Version 1.0.26

### ISSUE THREAD

**Issue by Bundesberti** [portfolio-performance/portfolio#703]
Hallo, 
in der Version 0.26.0 wird beim Öffnen einer Datei das Programm erneut gestartet. Man hat dann der Programm zweimal geöffnet, was nicht sehr sinnvoll ist - also vermutlich ein Bug.
Grüße 
Bundesberti

**Comment by buchen** [comment]
Sind dann zwei Fenster gleichzeitig sichtbar?

Könntest Du mal versuchen über das "Hilfe" Menü "Debug: GUI zurücksetzen" aufrufen?
