### ISSUE TITLE
Datenreihe: investiertes Kapital pro Depot (oder Filter?)

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#707]
https://forum.portfolio-performance.info/t/dashboard-grafiken/457?u=andreasb

**Comment by lsolesen** [comment]
@buchen I think this might be what I am asking for in the forum also - https://forum.portfolio-performance.info/t/is-it-possible-to-show-invested-capital-only-for-some-of-the-portfolio/8957

Any planned work on this issue? Thanks a lot for creating this free software btw. Has recommended it to many people.

**Comment by mierin12** [comment]
Invested Capital for any data series (any combination if account, Taxonomies) is now available in the Assets graph with release [0.73.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.73.0) from https://github.com/portfolio-performance/portfolio/pull/4403
