### ISSUE TITLE
Ein "ordentliches" Wiki erstellen?

### ISSUE THREAD

**Issue by ghost** [portfolio-performance/portfolio#727]
Hallo,

1. Super Software! Verwende es schon länger, Top!

2. Mir ist aufgefallen das die Information bzgl Funktion / Bedienen und Menü sehr verstreut ist. Zum einen findet sich vieles im Wertpapier-Forum.de, dann ein bisschen was hier und ein bisschen was auf deiner Homepage, wieder in Form eines Forums. Resultat sind unzählige Fragen die immer wieder gestellt werden, da keiner 100+ Seiten ließt.
Wäre es hier nicht sinnvoller ein Wiki oder PDF zu schreiben (gerne im Rahmen eines Gemeinschaftsprojektes)?

**Comment by buchen** [comment]
Hi @3mg4,

ja, das ist in der Tat eine Problem... Anfangs gab es mal hier das WIKI im Github (ist aber zu technisch für die meisten Benutzer mit dem Source Code drumherum), aber das habe ich selber grösstenteils editiert und ich bin kein Schreiberling für Dokumentation. 😒 

Das Wertpapier-Forum habe ich über Jahre genutzt. Allerdings ist das immer ein "Faden" und damit für Neulinge sehr schwer zu durchblicken. [Thomas](https://forum.portfolio-performance.info/users/thomas/summary) hat dann das Discours Forum aufgesetzt. Das nutze ich selbst primär. Da kann man Beiträge auch als WIKI umwandeln, z.B. diesen Beitrag zum [Rebalancing](https://forum.portfolio-performance.info/t/rebalancing-mit-portfolio-performance/19). In dem Forum kann man Thread auch schliessen und damit einen "geordneten" Thread anlegen - wie bei [Neues und Nennenswertes](https://forum.portfolio-performance.info/t/neues-nennenswertes/23/7). Und natürlich habe ich noch die Github Issues die ich eher für technische, Code-bezogene Punkte weiterverwende.

Wenn ich mir das überlege, könnte man im Forum auch einen "Einstiegs" - WIKI machen und die relevanten Diskussionen verlinken. Ich sehe auch das Problem dass oft nach Installationsproblemen gefragt wird obwohl die schon mehrfach (auch in den FAQ) verlinkt sind.

Alles steht und fällt an dem Inhalt. Der ist sehr zeitaufwändig zu erstellen. Den ggf. aus einem Discourse WIKI zu etwas anderen zu bewegen kommt dann später. Thomas würde da bestimmt noch was installieren oder betreiben.

Ich weiß nicht in welchen Richtung Du gedacht hast.

Andreas.

**Comment by 3mg4** [comment]
Verzeih die späte Antwort!
Der Grund für die Frage nach einem Wiki kam auf als ich selbst Informationen über das Programm suchte und dann auf zwei bzw. drei Seiten suchen musste.
Prinzipiell finde ich das Forumsthema nicht schlecht, es ist nur ähnlich wie in anderen „Gruppen“-> Man findet sehr schwer etwas, da es extrem abhängig von den Suchbegriffen ist, und selbst dann muss man meist noch viel lesen, und Leute sind faul, wie man an den unendlichen doppelten Fragen erkennen kann.;-)
Das Forum auf der Portfolio Performance Seite mit der Umwandlungsmöglichkeit auf ein Wiki finde ich sehr gut.
Das mit dem Code auf GitHub um ein Wiki zu erstellen ist sicher eine Hürde. Wenn auch keine unüberwindbare, aber da gehe ich wsl zu stark von meinen Interessen aus.
Eine einfache Lösung, die glaube ich auch gratis wäre, wäre natürlich das GitHub Wiki, um ein bisschen „coden“ wird man wsl nirgends rumkommen.
Eine genaue Vorstellung hab ich nicht, hab mir nur gedacht dieses Programm verdient ein schönes Wiki;-)
