### ISSUE TITLE
Statement of assets' purchase price, but including commissions

### ISSUE THREAD

**Issue by hakasedev** [portfolio-performance/portfolio#792]
Hi!
First of all, thanks for this project! I have installed at least 50 android apps, signed up on a dozen websites and looked at various other stuff and nothing was close to what I was looking for. I found this by chance in Archlinux's AUR and it's amazing!

I have a very very small amount of money, and a very expensive broker, so the commissions on my trades are very significant. For this reason, is it possible to have, in the statement of assets, an average purchase price that includes the broker fees? That figure looks deceptively good in my case, but if I add my transaction costs it becomes much more reasonable.

Thanks!

**Comment by megabugman** [comment]
hey, in statement of assets apparently fees are not displayed and there seems not to be any option to do so.
but under securities you find the fees for each security and under performance calculation you'll find the total fees. 
![securities](https://user-images.githubusercontent.com/17204819/28639943-52302e90-724a-11e7-920d-eebc43aa8fd2.png)
in your case maybe you should consider investing in a ETF saving plan. Many broker offer free saving plans: dunno where you live but check this comparison for instance:
https://www.justetf.com/de-en/etf-sparplan/sparplan-vergleich.html
total cost (TER) of ETFs are pretty low, usually bellow 0,5%.

Disclaimer: I am not affiliated in any way with the website and thus I (unfortunately) don't get any bugs, bitcoins nor free beer from them. 🥇

**Comment by hakasedev** [comment]
Hi! That's exactly what I was looking for, thanks.

>in your case maybe you should consider investing in a ETF saving plan

Thanks for the advice! Right now I'm calculating how much money I should accumulate before buying an ETF considering the historical returns% of that etf vs how much fees% I have to pay, but once in a while there's something I think is an opportunity and I want to try and put a bit of money there; this time it was AMD at 12.15: I really like what AMD is doing with their new processors (and even if their GPUs aren't that good, crypto miners are going to buy them until they become good enough for games and workstations anyway). I plan to hold mostly ETFs with the occasional individual stock now and then.

I plan to go with Exante or Interactive Brokers as soon as I have the 10000€ needed to open the account (which is, unfortunately, probably not until a couple of years from today).


... and I just realized I just wrote ten thousands words about stuff no one cares about :)

Thanks for the help, @megabugman!

**Comment by Ragas13** [comment]
It's a pitty that you've closed your issue.

I'm also interested to know the handling fee and taxable amount by asset or at least by security.

Let's see if I'm able to add this information to one of the next PP updates.

TY 4 the good idea.

Br
Ragas

**Comment by hakasedev** [comment]
I'm temporarily reopening the issue, but I'm not sure what you are looking for: as megabugman suggested, you can go in Reports -> Performance -> Securities, and you can add a Fee column. You can see how to do that in the image they posted. Let me know if that solves the problem so I can close again.

**Comment by Ragas13** [comment]
You're basically right as megabugman's solution is may solving your case but this reminds me to add this gross avrg. price also to  the "security accounts" as well as average line per each security chart.

I think it's could be interesting to see visually the buying rate against market price.
