### ISSUE TITLE
Alpha Vantage integration: Not all Symbols are available in the Market EUR

### ISSUE THREAD

**Issue by stasee** [portfolio-performance/portfolio#887]
Wenn man Alpha Vantage verwendet kann man das symbol editieren.
Leider sind nicht alle symbols in allen markets verfügbar.

Zum Beispiel: EOS ist nicht verfügbar im market EUR, das gibt es nur im market ETH.

Eine mögliche Lösung sieht so aus:
1. Ein Edit Feld neben dem symbol, dort konfiguriert man 'market'
2. Der default value für market ist currency (EUR).
3. Wenn der wert von market nicht der selbe wie currency ist, dann lade die daten von Alpha Vantage für symbol in market (e.g. EOS in ETH).
4. Zusätzlich lade die Daten für  market in currency (e.g. ETH in EUR).
5. Berechne aus den beiden Datenreihen das Ergebnis symbol in currency (EOS in EUR).

**Comment by buchen** [comment]
Wenn ich das richtig sehe, steht ```market``` als Parameter nur bei den Crypto Currencies zur Verfügung. Das API nutze ich noch gar nicht (nur TIME_SERIES_INTRADAY und TIME_SERIES_DAILY).

Aber nur das ich es richtig verstehe - Dir geht es darum den Wert des Wertpapieres (oder der Crypto Währung) nicht in USD sondern in EUR zu haben, richtig?

**Comment by stasee** [comment]
Hallo,
es geht darum, dass man mit market die Währung für den Kurs übergibt.
Jede Cryptowährung steht nur in bestimmten Währungspaaren zur Verfügung.
z.b. EOS steht nur in der Währung ETH zur Verfügung.

Beispiel:
https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_DAILY&symbol=EOS&market=EUR&apikey=XXX
liefert: "Error Message": "Invalid API call ....

https://www.alphavantage.co/query?function=DIGITAL_CURRENCY_DAILY&symbol=EOS&market=ETH&apikey=XXX
das geht, resultat ist 
{
    "Meta Data": {
        "1. Information": "Daily Prices and Volumes for Digital Currency",
        "2. Digital Currency Code": "EOS",
        "3. Digital Currency Name": "EOS",
        "4. Market Code": "ETH",
        "5. Market Name": "Ethereum",
        "6. Last Refreshed": "2017-11-12 (end of day)",
        "7. Time Zone": "UTC"
    },
    "Time Series (Digital Currency Daily)": {
        "2017-11-12": {
            "1a. open (ETH)": "0.00370029",
            "1b. open (USD)": "1.16136331",
            "2a. high (ETH)": "0.00379956",
            "2b. high (USD)": "1.18034895",
            "3a. low (ETH)": "0.00342204",
            "3b. low (USD)": "1.04224333",
            "4a. close (ETH)": "0.00360426",
            "4b. close (USD)": "1.10246967",
            "5. volume": "6138850.00328359",
            "6. market cap (USD)": "6767895.93930800"
        }
}

Da steht zwar auch USD drin, ich weis aber nicht ob man sich darauf verlassen kann, die Doku von Alpha Vantage sagt nichts über die result strukturen.
Bei meinen Tests kann ich nur sicher sagen, dass z.b. "4a. close (ETH)" immer in der gewünschten Zielwährung (market) ist.

Ich hab im Moment mal einen kleinen nodejs server gebastelt, der die Umrechnung macht und das als html tabelle ausgibt (Tabelle auf einer Webseite).
Wenns interessiert kann ich das ja mal hochladen.

**Comment by stasee** [comment]
https://github.com/stasee/alphavantage_pp
Konvertiert die Alphavantage Crypto Werte z.b. von EOS in ETH und dann in EUR und stellt diese als html Tabelle zur Verfügung

**Comment by ffidan61** [comment]
@stasee gibt es keinen Weg das direkt in Portfolio Performance zu machen?

**Comment by stasee** [comment]
Klar gibt es schon, nur dass ich in java nicht so schnell bin wie in anderen sprachen. Wenn ich mal ein bisschen Zeit habe kann ich ja mal reinschauen. 
@buchen könntest du dir das vorstellen? Sollen wir uns mal darüber austauschen, wie du das gerne hättest?
Ich würde vermutlich eine Option AlphaVantage Crypto einführen, bei der es dann zwei Inputfelder gibt (Symbol und Intermediate Symbol). Das ganze wäre für mich insofern überschaubar, als dass ich nur deiner Implementierung von AlphaVantage folgen müsste ohne zusätzliche Komplexität hinein zu bekommen.
