### ISSUE TITLE
Avira Historische daten import

### ISSUE THREAD

**Issue by TZocker** [portfolio-performance/portfolio#934]
Wollte nur zur info geben das man wie folgt zz. auch bei ariva an historische daten rann kommen kann.

Zuerst suchen wir uns den Chart zb. Hdax

http://www.ariva.de/hdax-index/historische_kurse

Als nächstes benötigt man die avira interne ID die findet man wenn man auf den depot button klickt bzw auswertet:

http://www.ariva.de/depot/private/add_multiple.m?ags=56714

=> 56714

Download der Datei 
http://www.ariva.de/quote/historic/historic.csv?secu=56714&boerse_id=12&clean_split=1&clean_payout=0&clean_bezug=1&min_time=8.1.2017&max_time=8.1.2018&trenner=%3B&go=Download

gut im schlüssel gibt noch weiter Einstellungen aber das muss nur 1 mal fest gelegt werden ^^

Musste leider darauf zurückgreifen da yahoo zz keine historischen hdax daten liefer warum auch immer und bei vanguard finde ich das symbol nicht mal.

mfg

**Comment by megabugman** [comment]
eine einfachere Lösung könnte darin bestehen die Kurse einfach runterzuladen:
![20180109230432](https://user-images.githubusercontent.com/17204819/34745652-824392c8-f591-11e7-9101-0a9caf033a69.PNG)

beim Testen habe ich einen unbehandelten Fehler gefunden. Beim Versuch eine leere CSV zu importieren, passiert das: 
![historisch03](https://user-images.githubusercontent.com/17204819/34745851-340d9b8e-f592-11e7-9d86-23640efd7454.png)

[nullpointer.zip](https://github.com/buchen/portfolio/files/1616861/nullpointer.zip)
