### ISSUE TITLE
can't generate target plattform - buchen.github.io/maven-repo not accessible

### ISSUE THREAD

**Issue by sschroep** [portfolio-performance/portfolio#959]
Followed the instructions in the README.md and run "mvn clean install -Dgenerate-target-platform=true -Dtycho.disableP2Mirrors". Maven wants to download 
buchen.github.io/maven-repo/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom but can't access it since buchen.github.io/maven-repo is not existing/accessible

**Comment by Ragas13** [comment]
We had end/2017 a similar issue and previously root cause sounds of a missconfiguration of MAVEN. Please review #959.

However, which Platform, Java and MAVEN version is in use at your PC?

By the way, could you kindly upload the MAVEN log file?

**Comment by sschroep** [comment]
Thank you for the hint with issue #911. It seems like i have the same Problem.

[INFO] Scanning for projects...
Downloading: http://buchen.github.io/maven-repo/org/eclipse/tycho/tycho-maven-plugin/1.0.0/tycho-maven-plugin-1.0.0.pom
[INFO] I/O exception (java.net.SocketException) caught when processing request to {}->http://buchen.github.io:80: Network is unreachable (connect failed)
[INFO] Retrying request to {}->http://buchen.github.io:80
[INFO] I/O exception (java.net.SocketException) caught when processing request to {}->http://buchen.github.io:80: Network is unreachable (connect failed)
[INFO] Retrying request to {}->http://buchen.github.io:80

maven is only trying to request buchen.github.io but is not switching to apache-maven 

I've no experience with maven so maybe you could help me fixing my maven config

p.s. mvn -V output:

Maven home: /usr/share/maven
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-7.b01.fc27.x86_64/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.13.9-300.fc27.x86_64", arch: "amd64", family: "unix"

**Comment by Ragas13** [comment]
Sorry for my late response. 

I'm not familiar with Linux but I assume that your installed Java version is may the reason.

I don't know if you're OpenJDK version is matching with the JDK (Java SE Development Kit).

Furthermore your version 8.144 is outdated as the current release is 8.172

https://java.com/en/download/help/linux_x64_install.xml
