### ISSUE TITLE
Windows Installer für PP

### ISSUE THREAD

**Issue by buchen** [portfolio-performance/portfolio#963]
Feedback war: Java Installation mit 32 oder 64 bit macht es recht kompliziert.

Idee:
* Java als Bundle einpacken
* Installer per NSIS für Windows generieren

**Comment by buchen** [comment]
@Ragas13 @sebasbaumh @megabugman @akoch 
Mag einer von Euch die Installer testen? Unter Windows wird PP inklusive JRE unter "Program Files" installiert (mit Nachfrage). Unter macOS kann man das aus der DMG nach "Applications" ziehen.

**Win 64bit**
[PortfolioPerformance-0.30.2-SNAPSHOT-win-x86_64-setup.exe](https://www.dropbox.com/s/nkp1qhcszk61um1/PortfolioPerformance-0.30.2-SNAPSHOT-win-x86_64-setup.exe?dl=0)

**Win32**
[PortfolioPerformance-0.30.2-SNAPSHOT-win-x86-setup.exe](https://www.dropbox.com/s/v4dsibars6qzunf/PortfolioPerformance-0.30.2-SNAPSHOT-win-x86-setup.exe?dl=0)

**macOS**
[PortfolioPerformance-0.30.2-SNAPSHOT.dmg](https://www.dropbox.com/s/yonbsi8uxi5ql8o/PortfolioPerformance-0.30.2-SNAPSHOT.dmg?dl=0)

**Comment by akoch** [comment]
Ich hab mal den 64Bit Windows installer getestet. Schaut soweit gut aus bei mir.

Eine Kleinigkeit ist, dass bei der ersten Seite des Installers, vermutlich das Performance, abgeschnitten wird, bzw. man sieht ja dass da drunter eigentlich noch was steht.
![installer](https://user-images.githubusercontent.com/1712469/39416970-5e01fe56-4c51-11e8-8a55-f38a54259f09.PNG)

**Comment by sebasbaumh** [comment]
Ich habe hier auch ein 64 bit-Windows 7.

Beim Download hat mein Chrome gesagt, dass es "ungewöhnliche Software" ist - wahrscheinlich eine Sicherheitsvorkehrung, da die EXE-Datei von Dropbox geladen wurde.

Der Text "Performance" ist bei mir auch abgeschnitten, wie beim Screenshot von @akoch .
Ansonsten schaut es nach der Installation gut aus.
Benutzt wird das durch das Setup mitinstallierte JRE laut Sysinternals Process Explorer.
Für das Update brauchst Du dann wahrscheinlich auch jeweils ein Setup bzw. zumindest Adminrechte, da die Installation ja nach `C:\Program Files` geht (nur, dass es nicht vergessen wird).

Das Icon zum Deinstallieren (Systemsteuerung->Programme und Funktionen) passt aber nicht ganz:
![programme_und_funktionen_2018-04-30_09-42-15](https://user-images.githubusercontent.com/670885/39418475-ea9d0c94-4c5a-11e8-8e6f-f294d18f48aa.png)

**Comment by buchen** [comment]
Vielen Dank @akoch @sebasbaumh 

> Der Text "Performance" ist bei mir auch abgeschnitten

Das konnte ich beheben - habe endlich den Parameter gefunden.

> Für das Update brauchst Du dann wahrscheinlich auch jeweils ein Setup bzw. zumindest Adminrechte

Auf meiner VMWare Windows 10 Installation hat ein Update funktioniert.
Ohne das ich was besonderes machen musste.
Beim Start schreibt Eclipse auch Dateien in das "configuration" Verzeichnis. Wenn PP das kann, dann sollte auch ein Update funktionieren. Gibt es unter "configuration" ein Verzeichnis "org.eclipse.osgi" bei Dir?


Was ich noch nicht hinbekommen habe ist beim Deinstallieren auch das Verzeichnis unter "%LOCALAPPDATA%" zu löschen. Aber damit kann ich erst mal leben.

**Comment by buchen** [comment]
> Das Icon zum Deinstallieren (Systemsteuerung->Programme und Funktionen) passt aber nicht ganz

Ist jetzt auch angepasst.

**Comment by sebasbaumh** [comment]
Es gibt den Ordner `C:\Program Files\Portfolio Performance\configuration\org.eclipse.osgi`.
Allerdings hat dort der normale Benutzer nur Leserechte.
Ich denke aber, es wird nach `C:\Users\%USERNAME%\AppData\Local\PortfolioPerformance\workspace\.metadata` geschrieben - zumindest landet dort das Log und ein paar andere Timestamps schauen auch so aus.

**Comment by Ragas13** [comment]
Der Installer ist eine coole Idee, aber es sicherlich nicht ohne Risiko wenn Dateien oder Verzeichnisse ausserhalb des Installers gelöscht werden sollen (siehe http://nsis.sourceforge.net/Reference/RMDir ).

Der App Ordner ist ja nicht das einzige Objekt was nicht gelöscht wird. Ich meine die kleinen Dateien bei PP-Updates werden ja auch nicht gelöscht (Windows Suffix P2BU).

Was mir persönlich nicht gefällt ist das der Installer Adminn Rechte möchte, ohne das dies mE notwendig ist. Lässt sich das evtl gem https://stackoverflow.com/questions/45467280/nsis-installer-without-admin-privileges noch ändern?

**Comment by Ragas13** [comment]
Was mir gerade noch aufgefallen ist, MAVEN  lädt jetzt explizit Java JAR's zur Version 8.171. Ist das beabsichtigt oder hängt es damit zusammen das die JRE eingebunden wird?

**Comment by buchen** [comment]
> Der Installer ist eine coole Idee, aber es sicherlich nicht ohne Risiko wenn Dateien oder Verzeichnisse ausserhalb des Installers gelöscht werden sollen

Ist ein Argument. Das Installationsverzeichnis an sich wird nur gelöscht wenn es tatsächlich leer ist. Also wenn man alles nach "Program Files" installiert, lösche ich nicht auch "Program Files".

> Ich meine die kleinen Dateien bei PP-Updates werden ja auch nicht gelöscht (Windows Suffix P2BU).

Interessant. Das sind die Backup Dateien von P2 - siehe auch https://wiki.eclipse.org/Equinox/p2/Engine/Touchpoint_Instructions_35#Backup

Eigentlich sollten die nach erfolgreicher Installation automatisch gelöscht werden. Aber wenn das nicht geht, dann bleiben die liegen. Auf meinem Mac habe ich das aber noch nicht beobachtet.

> Was mir gerade noch aufgefallen ist, MAVEN lädt jetzt explizit Java JAR's zur Version 8.171. Ist das beabsichtigt oder hängt es damit zusammen das die JRE eingebunden wird?

Ja. Ich habe jetzt zwei "Produkte" definiert - eines mit JRE und eines ohne. Wer also Java separat installieren will (auf Linux z.B.) kann das weiterhin tun.

Das zweite Produkt wird nur gebaut wenn ein Maven Profil aktiviert ist:
```
mvn clean verify -Dtycho.disableP2Mirrors -Ppackage-distro
```
