### ISSUE TITLE
Yahoo Historic Courses Import Broken

### ISSUE THREAD

**Issue by SimonStolz** [portfolio-performance/portfolio#974]
ISIN queries in Yahoo Finance seem to be broken in most current version PortfolioPerformance-0.31.0-win32.win32.x86_64. Also discussed in https://forum.portfolio-performance.info/t/quellen-fuer-historische-kurse/46 (see comment by "DanielS")

For example having specified new asset "Wertpapier" for stock Alphabet (ISIN US02079K3059)
Right click > Open in browser > OnVista correctly yields the page "https://www.onvista.de/aktien/Alphabet-Inc-A-ehemals-Google-Aktie-US02079K3059" 
Right click > Open in browser > Yahoo Finance yields a forwarding error page "de.finance.yahoo.com/q?s="

Similarly historic cannot be obtained anymore under "Edit" ISIN lookup.

**Comment by buchen** [comment]
Danke. Die Onvista "Im Browser öffnen" URL muss ich wohl mal wieder korrigieren. Vermutlich sollte ich mal durch alle URLs gehen.

**Comment by gsthys** [comment]
alphadvantage hat scheinbar auch was geändert:
Thu May 31 19:46:15 CEST 2018
Unerwartetes Feld in Serverantwort: {
    "Error Message": "Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY."
}

java.io.IOException: Unerwartetes Feld in Serverantwort: {
    "Error Message": "Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY."
}
	at name.abuchen.portfolio.online.impl.AlphavantageQuoteFeed.updateLatestQuotes(AlphavantageQuoteFeed.java:143)
	at name.abuchen.portfolio.ui.UpdateQuotesJob$1.run(UpdateQuotesJob.java:229)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
