### ISSUE TITLE
Limitation: Mehrfachauswahl Veschieben nicht möglich

### ISSUE THREAD

**Issue by megabugman** [portfolio-performance/portfolio#977]
es wird lediglich ein Papier verschoben:
![limitation](https://user-images.githubusercontent.com/17204819/39898549-7bc04768-54b7-11e8-9f95-ceb167e9850d.gif)

**Comment by mierin12** [comment]
Done since [release 0.36.0](https://github.com/portfolio-performance/portfolio/releases/tag/0.36.0) with https://github.com/portfolio-performance/portfolio/commit/4d5dde5afa82d8e1c05d3b9296372b213e82ee36 from https://github.com/portfolio-performance/portfolio/pull/1046
